package willatendo.fossilslegacy.server.tags;

import net.minecraft.tags.TagKey;
import willatendo.fossilslegacy.server.analyzer_result.AnalyzerResult;
import willatendo.fossilslegacy.server.registry.FARegistries;
import willatendo.fossilslegacy.server.utils.FAUtils;
import willatendo.simplelibrary.server.util.TagRegister;

public class FAAnalyzerResultTags {
    private static final TagRegister<AnalyzerResult> ANALYZER_RESULT_TAGS = TagRegister.create(FARegistries.ANALYZER_RESULT, FAUtils.ID);

    public static final TagKey<AnalyzerResult> FOSSIL_RESULTS = ANALYZER_RESULT_TAGS.register("fossil");
    public static final TagKey<AnalyzerResult> RELIC_SCRAP_RESULTS = ANALYZER_RESULT_TAGS.register("relic_scrap");
    public static final TagKey<AnalyzerResult> FROZEN_MEAT_RESULTS = ANALYZER_RESULT_TAGS.register("frozen_meat");
    public static final TagKey<AnalyzerResult> AXOLOTL_BUCKET_RESULTS = ANALYZER_RESULT_TAGS.register("axolotl_bucket");
    public static final TagKey<AnalyzerResult> TROPICAL_FISH_BUCKET_RESULTS = ANALYZER_RESULT_TAGS.register("tropical_fish_bucket");
    public static final TagKey<AnalyzerResult> PORKCHOP_RESULTS = ANALYZER_RESULT_TAGS.register("porkchop");
    public static final TagKey<AnalyzerResult> BEEF_RESULTS = ANALYZER_RESULT_TAGS.register("beef");
    public static final TagKey<AnalyzerResult> CHICKEN_RESULTS = ANALYZER_RESULT_TAGS.register("chicken");
    public static final TagKey<AnalyzerResult> FEATHER_RESULTS = ANALYZER_RESULT_TAGS.register("feather");
    public static final TagKey<AnalyzerResult> BAMBOO_RESULTS = ANALYZER_RESULT_TAGS.register("bamboo");
    public static final TagKey<AnalyzerResult> SLIME_BALL_RESULTS = ANALYZER_RESULT_TAGS.register("slime_ball");
    public static final TagKey<AnalyzerResult> MUTTON_RESULTS = ANALYZER_RESULT_TAGS.register("mutton");
    public static final TagKey<AnalyzerResult> RAW_RABBIT_RESULTS = ANALYZER_RESULT_TAGS.register("raw_rabbit");
    public static final TagKey<AnalyzerResult> BONE_RESULTS = ANALYZER_RESULT_TAGS.register("bone");
    public static final TagKey<AnalyzerResult> EMERALD_RESULTS = ANALYZER_RESULT_TAGS.register("emerald");
    public static final TagKey<AnalyzerResult> GOAT_HORN_RESULTS = ANALYZER_RESULT_TAGS.register("goat_horn");
    public static final TagKey<AnalyzerResult> FROGLIGHT_RESULTS = ANALYZER_RESULT_TAGS.register("froglight");
    public static final TagKey<AnalyzerResult> LEATHER_RESULTS = ANALYZER_RESULT_TAGS.register("leather");
    public static final TagKey<AnalyzerResult> STRING_RESULTS = ANALYZER_RESULT_TAGS.register("string");
    public static final TagKey<AnalyzerResult> COD_RESULTS = ANALYZER_RESULT_TAGS.register("cod");
    public static final TagKey<AnalyzerResult> SALMON_RESULTS = ANALYZER_RESULT_TAGS.register("salmon");
    public static final TagKey<AnalyzerResult> WOOL_RESULTS = ANALYZER_RESULT_TAGS.register("wool");
    public static final TagKey<AnalyzerResult> ARMADILLO_SCUTE_RESULTS = ANALYZER_RESULT_TAGS.register("armadilo_scute");
    public static final TagKey<AnalyzerResult> RAW_BRACHIOSAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_brachiosaurus_result");
    public static final TagKey<AnalyzerResult> RAW_DILOPHOSAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_dilophosaurus_result");
    public static final TagKey<AnalyzerResult> RAW_MAMMOTH_RESULTS = ANALYZER_RESULT_TAGS.register("raw_mammoth_result");
    public static final TagKey<AnalyzerResult> RAW_MOSASAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_mosasaurus_result");
    public static final TagKey<AnalyzerResult> RAW_FUTABASAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_futabasaurus_result");
    public static final TagKey<AnalyzerResult> RAW_PTERANODON_RESULTS = ANALYZER_RESULT_TAGS.register("raw_pteranodon_result");
    public static final TagKey<AnalyzerResult> RAW_SMILODON_RESULTS = ANALYZER_RESULT_TAGS.register("raw_smilodon_result");
    public static final TagKey<AnalyzerResult> RAW_STEGOSAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_stegosaurus_result");
    public static final TagKey<AnalyzerResult> RAW_TRICERATOPS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_triceratops_result");
    public static final TagKey<AnalyzerResult> RAW_TYRANNOSAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_tyrannosaurus_result");
    public static final TagKey<AnalyzerResult> RAW_VELOCIRAPTOR_RESULTS = ANALYZER_RESULT_TAGS.register("raw_velociraptor_result");
    public static final TagKey<AnalyzerResult> RAW_CARNOTAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_carnotaurus_result");
    public static final TagKey<AnalyzerResult> RAW_CRYOLOPHOSAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_cryolophosaurus_result");
    public static final TagKey<AnalyzerResult> RAW_THERIZINOSAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_therizinosaurus_result");
    public static final TagKey<AnalyzerResult> RAW_PACHYCEPHALOSAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_pachycephalosaurus_result");
    public static final TagKey<AnalyzerResult> RAW_COMPSOGNATHUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_compsognathus_result");
    public static final TagKey<AnalyzerResult> RAW_DODO_RESULTS = ANALYZER_RESULT_TAGS.register("raw_dodo_result");
    public static final TagKey<AnalyzerResult> RAW_MOA_RESULTS = ANALYZER_RESULT_TAGS.register("raw_moa_result");
    public static final TagKey<AnalyzerResult> RAW_GALLIMIMUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_gallimimus_result");
    public static final TagKey<AnalyzerResult> RAW_SPINOSAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_spinosaurus_result");
    public static final TagKey<AnalyzerResult> RAW_ANKYLOSAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_ankylosaurus_result");
    public static final TagKey<AnalyzerResult> RAW_DIMETRODON_RESULTS = ANALYZER_RESULT_TAGS.register("raw_dimetrodon_result");
    public static final TagKey<AnalyzerResult> RAW_ICTHYOSAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_icthyosaurus_result");
    public static final TagKey<AnalyzerResult> RAW_ELASMOTHERIUM_RESULTS = ANALYZER_RESULT_TAGS.register("raw_elasmotherium_results");
    public static final TagKey<AnalyzerResult> RAW_DRYOSAURUS_RESULTS = ANALYZER_RESULT_TAGS.register("raw_dryosaurus_results");
    public static final TagKey<AnalyzerResult> RAW_BARYONYX_RESULTS = ANALYZER_RESULT_TAGS.register("raw_baryonyx_results");
}
