package willatendo.fossilslegacy.server.tags;

import net.minecraft.tags.TagKey;
import willatendo.fossilslegacy.server.pattern.pattern.Pattern;
import willatendo.fossilslegacy.server.registry.FARegistries;
import willatendo.fossilslegacy.server.utils.FAUtils;
import willatendo.simplelibrary.server.util.TagRegister;

public class FAPatternTags {
    private static final TagRegister<Pattern> PATTERN_TAGS = TagRegister.create(FARegistries.PATTERN, FAUtils.ID);

    public static final TagKey<Pattern> LOCKED = PATTERN_TAGS.register("locked");
    public static final TagKey<Pattern> HAS_PATTERNS = PATTERN_TAGS.register("has_patterns");

    public static final TagKey<Pattern> ANKYLOSAURUS_2024_SKINS = PATTERN_TAGS.register("skins/ankylosaurus_2024");
    public static final TagKey<Pattern> ANKYLOSAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/ankylosaurus_2024");
    public static final TagKey<Pattern> BRACHIOSAURUS_2024_SKINS = PATTERN_TAGS.register("skins/brachiosaurus_2024");
    public static final TagKey<Pattern> BRACHIOSAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/brachiosaurus_2024");
    public static final TagKey<Pattern> BRACHIOSAURUS_2011_SKINS = PATTERN_TAGS.register("skins/brachiosaurus_2011");
    public static final TagKey<Pattern> BRACHIOSAURUS_2011_PATTERNS = PATTERN_TAGS.register("patterns/brachiosaurus_2011");
    public static final TagKey<Pattern> CARNOTAURUS_2024_SKINS = PATTERN_TAGS.register("skins/carnotaurus_2024");
    public static final TagKey<Pattern> CARNOTAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/carnotaurus_2024");
    public static final TagKey<Pattern> CARNOTAURUS_2011_SKINS = PATTERN_TAGS.register("skins/carnotaurus_2011");
    public static final TagKey<Pattern> CARNOTAURUS_2011_PATTERNS = PATTERN_TAGS.register("patterns/carnotaurus_2011");
    public static final TagKey<Pattern> COMPSOGNATHUS_2024_SKINS = PATTERN_TAGS.register("skins/compsognathus_2024");
    public static final TagKey<Pattern> COMPSOGNATHUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/compsognathus_2024");
    public static final TagKey<Pattern> CRYOLOPHOSAURUS_2024_SKINS = PATTERN_TAGS.register("skins/cryolophosaurus_2024");
    public static final TagKey<Pattern> CRYOLOPHOSAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/cryolophosaurus_2024");
    public static final TagKey<Pattern> CRYOLOPHOSAURUS_2011_SKINS = PATTERN_TAGS.register("skins/cryolophosaurus_2011");
    public static final TagKey<Pattern> CRYOLOPHOSAURUS_2011_PATTERNS = PATTERN_TAGS.register("patterns/cryolophosaurus_2011");
    public static final TagKey<Pattern> DILOPHOSAURUS_2024_SKINS = PATTERN_TAGS.register("skins/dilophosaurus_2024");
    public static final TagKey<Pattern> DILOPHOSAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/dilophosaurus_2024");
    public static final TagKey<Pattern> DILOPHOSAURUS_2011_SKINS = PATTERN_TAGS.register("skins/dilophosaurus_2011");
    public static final TagKey<Pattern> DILOPHOSAURUS_2011_PATTERNS = PATTERN_TAGS.register("patterns/dilophosaurus_2011");
    public static final TagKey<Pattern> DIMETRODON_2024_SKINS = PATTERN_TAGS.register("skins/dimetrodon_2024");
    public static final TagKey<Pattern> DIMETRODON_2024_PATTERNS = PATTERN_TAGS.register("patterns/dimetrodon_2024");
    public static final TagKey<Pattern> DODO_2024_SKINS = PATTERN_TAGS.register("skins/dodo_2024");
    public static final TagKey<Pattern> DODO_2024_PATTERNS = PATTERN_TAGS.register("patterns/dodo_2024");
    public static final TagKey<Pattern> FUTABASAURUS_2024_SKINS = PATTERN_TAGS.register("skins/futabasaurus_2024");
    public static final TagKey<Pattern> FUTABASAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/futabasaurus_2024");
    public static final TagKey<Pattern> FUTABASAURUS_2011_SKINS = PATTERN_TAGS.register("skins/futabasaurus_2011");
    public static final TagKey<Pattern> FUTABASAURUS_2011_PATTERNS = PATTERN_TAGS.register("patterns/futabasaurus_2011");
    public static final TagKey<Pattern> GALLIMIMUS_2024_SKINS = PATTERN_TAGS.register("skins/gallimimus_2024");
    public static final TagKey<Pattern> GALLIMIMUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/gallimimus_2024");
    public static final TagKey<Pattern> ICHTHYOSAURUS_2025_SKINS = PATTERN_TAGS.register("skins/ichthyosaurus_2025");
    public static final TagKey<Pattern> ICHTHYOSAURUS_2025_PATTERNS = PATTERN_TAGS.register("patterns/ichthyosaurus_2025");
    public static final TagKey<Pattern> MAMMOTH_2024_SKINS = PATTERN_TAGS.register("skins/mammoth_2024");
    public static final TagKey<Pattern> MAMMOTH_2024_PATTERNS = PATTERN_TAGS.register("patterns/mammoth_2024");
    public static final TagKey<Pattern> MAMMOTH_2011_SKINS = PATTERN_TAGS.register("skins/mammoth_2011");
    public static final TagKey<Pattern> MAMMOTH_2011_PATTERNS = PATTERN_TAGS.register("patterns/mammoth_2011");
    public static final TagKey<Pattern> MOA_2024_SKINS = PATTERN_TAGS.register("skins/moa_2024");
    public static final TagKey<Pattern> MOA_2024_PATTERNS = PATTERN_TAGS.register("patterns/moa_2024");
    public static final TagKey<Pattern> MOSASAURUS_2024_SKINS = PATTERN_TAGS.register("skins/mosasaurus_2024");
    public static final TagKey<Pattern> MOSASAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/mosasaurus_2024");
    public static final TagKey<Pattern> MOSASAURUS_2011_SKINS = PATTERN_TAGS.register("skins/mosasaurus_2011");
    public static final TagKey<Pattern> MOSASAURUS_2011_PATTERNS = PATTERN_TAGS.register("patterns/mosasaurus_2011");
    public static final TagKey<Pattern> PACHYCEPHALOSAURUS_2024_SKINS = PATTERN_TAGS.register("skins/pachycephalosaurus_2024");
    public static final TagKey<Pattern> PACHYCEPHALOSAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/pachycephalosaurus_2024");
    public static final TagKey<Pattern> PTERANODON_2024_SKINS = PATTERN_TAGS.register("skins/pteranodon_2024");
    public static final TagKey<Pattern> PTERANODON_2024_PATTERNS = PATTERN_TAGS.register("patterns/pteranodon_2024");
    public static final TagKey<Pattern> PTERANODON_2011_SKINS = PATTERN_TAGS.register("skins/pteranodon_2011");
    public static final TagKey<Pattern> PTERANODON_2011_PATTERNS = PATTERN_TAGS.register("patterns/pteranodon_2011");
    public static final TagKey<Pattern> SMILODON_2024_SKINS = PATTERN_TAGS.register("skins/smilodon_2024");
    public static final TagKey<Pattern> SMILODON_2024_PATTERNS = PATTERN_TAGS.register("patterns/smilodon_2024");
    public static final TagKey<Pattern> SMILODON_2011_SKINS = PATTERN_TAGS.register("skins/smilodon_2011");
    public static final TagKey<Pattern> SMILODON_2011_PATTERNS = PATTERN_TAGS.register("patterns/smilodon_2011");
    public static final TagKey<Pattern> SPINOSAURUS_2024_SKINS = PATTERN_TAGS.register("skins/spinosaurus_2024");
    public static final TagKey<Pattern> SPINOSAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/spinosaurus_2024");
    public static final TagKey<Pattern> STEGOSAURUS_2024_SKINS = PATTERN_TAGS.register("skins/stegosaurus_2024");
    public static final TagKey<Pattern> STEGOSAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/stegosaurus_2024");
    public static final TagKey<Pattern> STEGOSAURUS_2011_SKINS = PATTERN_TAGS.register("skins/stegosaurus_2011");
    public static final TagKey<Pattern> STEGOSAURUS_2011_PATTERNS = PATTERN_TAGS.register("patterns/stegosaurus_2011");
    public static final TagKey<Pattern> THERIZINOSAURUS_2024_SKINS = PATTERN_TAGS.register("skins/therizinosaurus_2024");
    public static final TagKey<Pattern> THERIZINOSAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/therizinosaurus_2024");
    public static final TagKey<Pattern> THERIZINOSAURUS_2011_SKINS = PATTERN_TAGS.register("skins/therizinosaurus_2011");
    public static final TagKey<Pattern> THERIZINOSAURUS_2011_PATTERNS = PATTERN_TAGS.register("patterns/therizinosaurus_2011");
    public static final TagKey<Pattern> TRICERATOPS_2024_SKINS = PATTERN_TAGS.register("skins/triceratops_2024");
    public static final TagKey<Pattern> TRICERATOPS_2024_PATTERNS = PATTERN_TAGS.register("patterns/triceratops_2024");
    public static final TagKey<Pattern> TRICERATOPS_2011_SKINS = PATTERN_TAGS.register("skins/triceratops_2011");
    public static final TagKey<Pattern> TRICERATOPS_2011_PATTERNS = PATTERN_TAGS.register("patterns/triceratops_2011");
    public static final TagKey<Pattern> TYRANNOSAURUS_2024_SKINS = PATTERN_TAGS.register("skins/tyrannosaurus_2024");
    public static final TagKey<Pattern> TYRANNOSAURUS_2024_PATTERNS = PATTERN_TAGS.register("patterns/tyrannosaurus_2024");
    public static final TagKey<Pattern> TYRANNOSAURUS_2011_SKINS = PATTERN_TAGS.register("skins/tyrannosaurus_2011");
    public static final TagKey<Pattern> TYRANNOSAURUS_2011_PATTERNS = PATTERN_TAGS.register("patterns/tyrannosaurus_2011");
    public static final TagKey<Pattern> VELOCIRAPTOR_2024_SKINS = PATTERN_TAGS.register("skins/velociraptor_2024");
    public static final TagKey<Pattern> VELOCIRAPTOR_2024_PATTERNS = PATTERN_TAGS.register("patterns/velociraptor_2024");
    public static final TagKey<Pattern> VELOCIRAPTOR_2011_SKINS = PATTERN_TAGS.register("skins/velociraptor_2011");
    public static final TagKey<Pattern> VELOCIRAPTOR_2011_PATTERNS = PATTERN_TAGS.register("patterns/velociraptor_2011");
}
