package willatendo.fossilslegacy.server.sound;

import net.minecraft.core.registries.Registries;
import net.minecraft.sounds.SoundEvent;
import willatendo.fossilslegacy.server.utils.FAUtils;
import willatendo.simplelibrary.server.registry.SimpleHolder;
import willatendo.simplelibrary.server.registry.SimpleRegistry;

public final class FASoundEvents {
    public static final SimpleRegistry<SoundEvent> SOUND_EVENTS = SimpleRegistry.create(Registries.SOUND_EVENT, FAUtils.ID);

    public static final SimpleHolder<SoundEvent> DRUM_HIT = SOUND_EVENTS.register("block.drum.hit", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("block.drum.hit")));
    public static final SimpleHolder<SoundEvent> DRUM_TRIPLE_HIT = SOUND_EVENTS.register("block.drum.triple_hit", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("block.drum.triple_hit")));

    public static final SimpleHolder<SoundEvent> ANKYLOSAURUS_AMBIENT = SOUND_EVENTS.register("entity.ankylosaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.ankylosaurus.ambient")));
    public static final SimpleHolder<SoundEvent> ANKYLOSAURUS_HURT = SOUND_EVENTS.register("entity.ankylosaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.ankylosaurus.hurt")));
    public static final SimpleHolder<SoundEvent> ANKYLOSAURUS_DEATH = SOUND_EVENTS.register("entity.ankylosaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.ankylosaurus.death")));
    public static final SimpleHolder<SoundEvent> BARYONYX_AMBIENT = SOUND_EVENTS.register("entity.baryonyx.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.baryonyx.ambient")));
    public static final SimpleHolder<SoundEvent> BARYONYX_HURT = SOUND_EVENTS.register("entity.baryonyx.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.baryonyx.hurt")));
    public static final SimpleHolder<SoundEvent> BARYONYX_DEATH = SOUND_EVENTS.register("entity.baryonyx.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.baryonyx.death")));
    public static final SimpleHolder<SoundEvent> BRACHIOSAURUS_AMBIENT = SOUND_EVENTS.register("entity.brachiosaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.brachiosaurus.ambient")));
    public static final SimpleHolder<SoundEvent> BRACHIOSAURUS_HURT = SOUND_EVENTS.register("entity.brachiosaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.brachiosaurus.hurt")));
    public static final SimpleHolder<SoundEvent> BRACHIOSAURUS_DEATH = SOUND_EVENTS.register("entity.brachiosaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.brachiosaurus.death")));
    public static final SimpleHolder<SoundEvent> CARNOTAURUS_AMBIENT = SOUND_EVENTS.register("entity.carnotaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.carnotaurus.ambient")));
    public static final SimpleHolder<SoundEvent> CARNOTAURUS_HURT = SOUND_EVENTS.register("entity.carnotaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.carnotaurus.hurt")));
    public static final SimpleHolder<SoundEvent> CARNOTAURUS_DEATH = SOUND_EVENTS.register("entity.carnotaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.carnotaurus.death")));
    public static final SimpleHolder<SoundEvent> COMPSOGNATHUS_AMBIENT = SOUND_EVENTS.register("entity.compsognathus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.compsognathus.ambient")));
    public static final SimpleHolder<SoundEvent> COMPSOGNATHUS_HURT = SOUND_EVENTS.register("entity.compsognathus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.compsognathus.hurt")));
    public static final SimpleHolder<SoundEvent> COMPSOGNATHUS_DEATH = SOUND_EVENTS.register("entity.compsognathus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.compsognathus.death")));
    public static final SimpleHolder<SoundEvent> CRYOLOPHOSAURUS_AMBIENT = SOUND_EVENTS.register("entity.cryolophosaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.cryolophosaurus.ambient")));
    public static final SimpleHolder<SoundEvent> CRYOLOPHOSAURUS_HURT = SOUND_EVENTS.register("entity.cryolophosaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.cryolophosaurus.hurt")));
    public static final SimpleHolder<SoundEvent> CRYOLOPHOSAURUS_DEATH = SOUND_EVENTS.register("entity.cryolophosaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.cryolophosaurus.death")));
    public static final SimpleHolder<SoundEvent> DILOPHOSAURUS_AMBIENT = SOUND_EVENTS.register("entity.dilophosaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dilophosaurus.ambient")));
    public static final SimpleHolder<SoundEvent> DILOPHOSAURUS_CALL = SOUND_EVENTS.register("entity.dilophosaurus.call", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dilophosaurus.call")));
    public static final SimpleHolder<SoundEvent> DILOPHOSAURUS_HURT = SOUND_EVENTS.register("entity.dilophosaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dilophosaurus.hurt")));
    public static final SimpleHolder<SoundEvent> DILOPHOSAURUS_DEATH = SOUND_EVENTS.register("entity.dilophosaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dilophosaurus.death")));
    public static final SimpleHolder<SoundEvent> DIMETRODON_AMBIENT = SOUND_EVENTS.register("entity.dimetrodon.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dimetrodon.ambient")));
    public static final SimpleHolder<SoundEvent> DIMETRODON_HURT = SOUND_EVENTS.register("entity.dimetrodon.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dimetrodon.hurt")));
    public static final SimpleHolder<SoundEvent> DIMETRODON_DEATH = SOUND_EVENTS.register("entity.dimetrodon.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dimetrodon.death")));
    public static final SimpleHolder<SoundEvent> DODO_AMBIENT = SOUND_EVENTS.register("entity.dodo.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dodo.ambient")));
    public static final SimpleHolder<SoundEvent> DODO_HURT = SOUND_EVENTS.register("entity.dodo.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dodo.hurt")));
    public static final SimpleHolder<SoundEvent> DODO_DEATH = SOUND_EVENTS.register("entity.dodo.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dodo.death")));
    public static final SimpleHolder<SoundEvent> DODO_STEP = SOUND_EVENTS.register("entity.dodo.step", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dodo.step")));
    public static final SimpleHolder<SoundEvent> DRYOSAURUS_AMBIENT = SOUND_EVENTS.register("entity.dryosaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dryosaurus.ambient")));
    public static final SimpleHolder<SoundEvent> DRYOSAURUS_HURT = SOUND_EVENTS.register("entity.dryosaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dryosaurus.hurt")));
    public static final SimpleHolder<SoundEvent> DRYOSAURUS_DEATH = SOUND_EVENTS.register("entity.dryosaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.dryosaurus.death")));
    public static final SimpleHolder<SoundEvent> ELASMOTHERIUM_AMBIENT = SOUND_EVENTS.register("entity.elasmotherium.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.elasmotherium.ambient")));
    public static final SimpleHolder<SoundEvent> ELASMOTHERIUM_HURT = SOUND_EVENTS.register("entity.elasmotherium.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.elasmotherium.hurt")));
    public static final SimpleHolder<SoundEvent> ELASMOTHERIUM_DEATH = SOUND_EVENTS.register("entity.elasmotherium.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.elasmotherium.death")));
    public static final SimpleHolder<SoundEvent> MAMMOTH_AMBIENT = SOUND_EVENTS.register("entity.mammoth.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.mammoth.ambient")));
    public static final SimpleHolder<SoundEvent> MAMMOTH_HURT = SOUND_EVENTS.register("entity.mammoth.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.mammoth.hurt")));
    public static final SimpleHolder<SoundEvent> MAMMOTH_DEATH = SOUND_EVENTS.register("entity.mammoth.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.mammoth.death")));
    public static final SimpleHolder<SoundEvent> MOA_AMBIENT = SOUND_EVENTS.register("entity.moa.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.moa.ambient")));
    public static final SimpleHolder<SoundEvent> MOA_HURT = SOUND_EVENTS.register("entity.moa.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.moa.hurt")));
    public static final SimpleHolder<SoundEvent> MOA_DEATH = SOUND_EVENTS.register("entity.moa.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.moa.death")));
    public static final SimpleHolder<SoundEvent> FUTABASAURUS_AMBIENT = SOUND_EVENTS.register("entity.futabasaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.plesiosaurus.ambient")));
    public static final SimpleHolder<SoundEvent> FUTABASAURUS_HURT = SOUND_EVENTS.register("entity.futabasaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.futabasaurus.hurt")));
    public static final SimpleHolder<SoundEvent> FUTABASAURUS_DEATH = SOUND_EVENTS.register("entity.futabasaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.futabasaurus.death")));
    public static final SimpleHolder<SoundEvent> GALLIMIMUS_AMBIENT = SOUND_EVENTS.register("entity.gallimimus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.gallimimus.ambient")));
    public static final SimpleHolder<SoundEvent> GALLIMIMUS_HURT = SOUND_EVENTS.register("entity.gallimimus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.gallimimus.hurt")));
    public static final SimpleHolder<SoundEvent> GALLIMIMUS_DEATH = SOUND_EVENTS.register("entity.gallimimus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.gallimimus.death")));
    public static final SimpleHolder<SoundEvent> PACHYCEPHALOSAURUS_AMBIENT = SOUND_EVENTS.register("entity.pachycephalosaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.pachycephalosaurus.ambient")));
    public static final SimpleHolder<SoundEvent> PACHYCEPHALOSAURUS_HURT = SOUND_EVENTS.register("entity.pachycephalosaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.pachycephalosaurus.hurt")));
    public static final SimpleHolder<SoundEvent> PACHYCEPHALOSAURUS_DEATH = SOUND_EVENTS.register("entity.pachycephalosaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.pachycephalosaurus.death")));
    public static final SimpleHolder<SoundEvent> PTERANODON_AMBIENT = SOUND_EVENTS.register("entity.pteranodon.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.futabasaurus.ambient")));
    public static final SimpleHolder<SoundEvent> PTERANODON_HURT = SOUND_EVENTS.register("entity.pteranodon.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.pteranodon.hurt")));
    public static final SimpleHolder<SoundEvent> PTERANODON_DEATH = SOUND_EVENTS.register("entity.pteranodon.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.pteranodon.death")));
    public static final SimpleHolder<SoundEvent> SMILODON_AMBIENT = SOUND_EVENTS.register("entity.smilodon.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.smilodon.ambient")));
    public static final SimpleHolder<SoundEvent> SMILODON_HURT = SOUND_EVENTS.register("entity.smilodon.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.smilodon.hurt")));
    public static final SimpleHolder<SoundEvent> SMILODON_DEATH = SOUND_EVENTS.register("entity.smilodon.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.smilodon.death")));
    public static final SimpleHolder<SoundEvent> SPINOSAURUS_AMBIENT = SOUND_EVENTS.register("entity.spinosaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.spinosaurus.ambient")));
    public static final SimpleHolder<SoundEvent> SPINOSAURUS_HURT = SOUND_EVENTS.register("entity.spinosaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.spinosaurus.hurt")));
    public static final SimpleHolder<SoundEvent> SPINOSAURUS_DEATH = SOUND_EVENTS.register("entity.spinosaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.spinosaurus.death")));
    public static final SimpleHolder<SoundEvent> STEGOSAURUS_AMBIENT = SOUND_EVENTS.register("entity.stegosaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.stegosaurus.ambient")));
    public static final SimpleHolder<SoundEvent> STEGOSAURUS_HURT = SOUND_EVENTS.register("entity.stegosaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.stegosaurus.hurt")));
    public static final SimpleHolder<SoundEvent> STEGOSAURUS_DEATH = SOUND_EVENTS.register("entity.stegosaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.stegosaurus.death")));
    public static final SimpleHolder<SoundEvent> THERIZINOSAURUS_AMBIENT = SOUND_EVENTS.register("entity.therizinosaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.therizinosaurus.ambient")));
    public static final SimpleHolder<SoundEvent> THERIZINOSAURUS_HURT = SOUND_EVENTS.register("entity.therizinosaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.therizinosaurus.hurt")));
    public static final SimpleHolder<SoundEvent> THERIZINOSAURUS_DEATH = SOUND_EVENTS.register("entity.therizinosaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.therizinosaurus.death")));
    public static final SimpleHolder<SoundEvent> TRICERATOPS_AMBIENT = SOUND_EVENTS.register("entity.triceratops.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.triceratops.ambient")));
    public static final SimpleHolder<SoundEvent> TRICERATOPS_HURT = SOUND_EVENTS.register("entity.triceratops.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.triceratops.hurt")));
    public static final SimpleHolder<SoundEvent> TRICERATOPS_DEATH = SOUND_EVENTS.register("entity.triceratops.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.triceratops.death")));
    public static final SimpleHolder<SoundEvent> TYRANNOSAURUS_AMBIENT = SOUND_EVENTS.register("entity.tyrannosaurus.ambient", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.tyrannosaurus.ambient")));
    public static final SimpleHolder<SoundEvent> TYRANNOSAURUS_ATTACK = SOUND_EVENTS.register("entity.tyrannosaurus.attack", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.tyrannosaurus.attack")));
    public static final SimpleHolder<SoundEvent> TYRANNOSAURUS_HURT = SOUND_EVENTS.register("entity.tyrannosaurus.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.tyrannosaurus.hurt")));
    public static final SimpleHolder<SoundEvent> TYRANNOSAURUS_DEATH = SOUND_EVENTS.register("entity.tyrannosaurus.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.tyrannosaurus.death")));
    public static final SimpleHolder<SoundEvent> VELOCIRAPTOR_AMBIENT_TAME = SOUND_EVENTS.register("entity.velociraptor.ambient.tame", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.velociraptor.ambient.tame")));
    public static final SimpleHolder<SoundEvent> VELOCIRAPTOR_AMBIENT_WILD = SOUND_EVENTS.register("entity.velociraptor.ambient.wild", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.velociraptor.ambient.wild")));
    public static final SimpleHolder<SoundEvent> VELOCIRAPTOR_ATTACK = SOUND_EVENTS.register("entity.velociraptor.attack", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.velociraptor.attack")));
    public static final SimpleHolder<SoundEvent> VELOCIRAPTOR_HURT = SOUND_EVENTS.register("entity.velociraptor.hurt", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.velociraptor.hurt")));
    public static final SimpleHolder<SoundEvent> VELOCIRAPTOR_DEATH = SOUND_EVENTS.register("entity.velociraptor.death", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("entity.velociraptor.death")));

    public static final SimpleHolder<SoundEvent> MAGIC_CONCH_BLOW = SOUND_EVENTS.register("item.magic_conch.blow", () -> SoundEvent.createVariableRangeEvent(FAUtils.resource("item.magic_conch.blow")));
}
