project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: 1
files:
  - source: common/src/generated/resources/assets/fossilslegacy/lang/en_us.json
    translation: common/src/main/resources/assets/fossilslegacy/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        fr: fr_fr
        pt-BR: pt_br
