package willatendo.fossilslegacy.server.item;

import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Item;

public final class FAItemReferences {
    public static final ResourceKey<Item> LEPIDODENDRON_PLANKS = FAItemReferences.create("lepidodendron_planks");
    public static final ResourceKey<Item> LEPIDODENDRON_SAPLING = FAItemReferences.create("lepidodendron_sapling");
    public static final ResourceKey<Item> LEPIDODENDRON_LOG = FAItemReferences.create("lepidodendron_log");
    public static final ResourceKey<Item> STRIPPED_LEPIDODENDRON_LOG = FAItemReferences.create("stripped_lepidodendron_log");
    public static final ResourceKey<Item> LEPIDODENDRON_WOOD = FAItemReferences.create("lepidodendron_wood");
    public static final ResourceKey<Item> STRIPPED_LEPIDODENDRON_WOOD = FAItemReferences.create("stripped_lepidodendron_wood");
    public static final ResourceKey<Item> LEPIDODENDRON_LEAVES = FAItemReferences.create("lepidodendron_leaves");
    public static final ResourceKey<Item> LEPIDODENDRON_STAIRS = FAItemReferences.create("lepidodendron_stairs");
    public static final ResourceKey<Item> LEPIDODENDRON_PRESSURE_PLATE = FAItemReferences.create("lepidodendron_pressure_plate");
    public static final ResourceKey<Item> LEPIDODENDRON_FENCE = FAItemReferences.create("lepidodendron_fence");
    public static final ResourceKey<Item> LEPIDODENDRON_TRAPDOOR = FAItemReferences.create("lepidodendron_trapdoor");
    public static final ResourceKey<Item> LEPIDODENDRON_FENCE_GATE = FAItemReferences.create("lepidodendron_fence_gate");
    public static final ResourceKey<Item> LEPIDODENDRON_BUTTON = FAItemReferences.create("lepidodendron_button");
    public static final ResourceKey<Item> LEPIDODENDRON_SLAB = FAItemReferences.create("lepidodendron_slab");
    public static final ResourceKey<Item> SIGILLARIA_PLANKS = FAItemReferences.create("sigillaria_planks");
    public static final ResourceKey<Item> SIGILLARIA_SAPLING = FAItemReferences.create("sigillaria_sapling");
    public static final ResourceKey<Item> SIGILLARIA_LOG = FAItemReferences.create("sigillaria_log");
    public static final ResourceKey<Item> STRIPPED_SIGILLARIA_LOG = FAItemReferences.create("stripped_sigillaria_log");
    public static final ResourceKey<Item> SIGILLARIA_WOOD = FAItemReferences.create("sigillaria_wood");
    public static final ResourceKey<Item> STRIPPED_SIGILLARIA_WOOD = FAItemReferences.create("stripped_sigillaria_wood");
    public static final ResourceKey<Item> SIGILLARIA_LEAVES = FAItemReferences.create("sigillaria_leaves");
    public static final ResourceKey<Item> SIGILLARIA_STAIRS = FAItemReferences.create("sigillaria_stairs");
    public static final ResourceKey<Item> SIGILLARIA_PRESSURE_PLATE = FAItemReferences.create("sigillaria_pressure_plate");
    public static final ResourceKey<Item> SIGILLARIA_FENCE = FAItemReferences.create("sigillaria_fence");
    public static final ResourceKey<Item> SIGILLARIA_TRAPDOOR = FAItemReferences.create("sigillaria_trapdoor");
    public static final ResourceKey<Item> SIGILLARIA_FENCE_GATE = FAItemReferences.create("sigillaria_fence_gate");
    public static final ResourceKey<Item> SIGILLARIA_BUTTON = FAItemReferences.create("sigillaria_button");
    public static final ResourceKey<Item> SIGILLARIA_SLAB = FAItemReferences.create("sigillaria_slab");
    public static final ResourceKey<Item> CALAMITES_PLANKS = FAItemReferences.create("calamites_planks");
    public static final ResourceKey<Item> CALAMITES_SAPLING = FAItemReferences.create("calamites_sapling");
    public static final ResourceKey<Item> CALAMITES_LOG = FAItemReferences.create("calamites_log");
    public static final ResourceKey<Item> STRIPPED_CALAMITES_LOG = FAItemReferences.create("stripped_calamites_log");
    public static final ResourceKey<Item> CALAMITES_WOOD = FAItemReferences.create("calamites_wood");
    public static final ResourceKey<Item> STRIPPED_CALAMITES_WOOD = FAItemReferences.create("stripped_calamites_wood");
    public static final ResourceKey<Item> CALAMITES_LEAVES = FAItemReferences.create("calamites_leaves");
    public static final ResourceKey<Item> CALAMITES_STAIRS = FAItemReferences.create("calamites_stairs");
    public static final ResourceKey<Item> CALAMITES_PRESSURE_PLATE = FAItemReferences.create("calamites_pressure_plate");
    public static final ResourceKey<Item> CALAMITES_FENCE = FAItemReferences.create("calamites_fence");
    public static final ResourceKey<Item> CALAMITES_TRAPDOOR = FAItemReferences.create("calamites_trapdoor");
    public static final ResourceKey<Item> CALAMITES_FENCE_GATE = FAItemReferences.create("calamites_fence_gate");
    public static final ResourceKey<Item> CALAMITES_BUTTON = FAItemReferences.create("calamites_button");
    public static final ResourceKey<Item> CALAMITES_SLAB = FAItemReferences.create("calamites_slab");
    public static final ResourceKey<Item> ARCHAEOPTERIS_PLANKS = FAItemReferences.create("archaeopteris_planks");
    public static final ResourceKey<Item> ARCHAEOPTERIS_SAPLING = FAItemReferences.create("archaeopteris_sapling");
    public static final ResourceKey<Item> ARCHAEOPTERIS_LOG = FAItemReferences.create("archaeopteris_log");
    public static final ResourceKey<Item> STRIPPED_ARCHAEOPTERIS_LOG = FAItemReferences.create("stripped_archaeopteris_log");
    public static final ResourceKey<Item> ARCHAEOPTERIS_WOOD = FAItemReferences.create("archaeopteris_wood");
    public static final ResourceKey<Item> STRIPPED_ARCHAEOPTERIS_WOOD = FAItemReferences.create("stripped_archaeopteris_wood");
    public static final ResourceKey<Item> ARCHAEOPTERIS_LEAVES = FAItemReferences.create("archaeopteris_leaves");
    public static final ResourceKey<Item> ARCHAEOPTERIS_STAIRS = FAItemReferences.create("archaeopteris_stairs");
    public static final ResourceKey<Item> ARCHAEOPTERIS_PRESSURE_PLATE = FAItemReferences.create("archaeopteris_pressure_plate");
    public static final ResourceKey<Item> ARCHAEOPTERIS_FENCE = FAItemReferences.create("archaeopteris_fence");
    public static final ResourceKey<Item> ARCHAEOPTERIS_TRAPDOOR = FAItemReferences.create("archaeopteris_trapdoor");
    public static final ResourceKey<Item> ARCHAEOPTERIS_FENCE_GATE = FAItemReferences.create("archaeopteris_fence_gate");
    public static final ResourceKey<Item> ARCHAEOPTERIS_BUTTON = FAItemReferences.create("archaeopteris_button");
    public static final ResourceKey<Item> ARCHAEOPTERIS_SLAB = FAItemReferences.create("archaeopteris_slab");
    public static final ResourceKey<Item> GINKGO_PLANKS = FAItemReferences.create("ginkgo_planks");
    public static final ResourceKey<Item> GINKGO_SAPLING = FAItemReferences.create("ginkgo_sapling");
    public static final ResourceKey<Item> GINKGO_LOG = FAItemReferences.create("ginkgo_log");
    public static final ResourceKey<Item> STRIPPED_GINKGO_LOG = FAItemReferences.create("stripped_ginkgo_log");
    public static final ResourceKey<Item> GINKGO_WOOD = FAItemReferences.create("ginkgo_wood");
    public static final ResourceKey<Item> STRIPPED_GINKGO_WOOD = FAItemReferences.create("stripped_ginkgo_wood");
    public static final ResourceKey<Item> GINKGO_LEAVES = FAItemReferences.create("ginkgo_leaves");
    public static final ResourceKey<Item> GINKGO_STAIRS = FAItemReferences.create("ginkgo_stairs");
    public static final ResourceKey<Item> GINKGO_PRESSURE_PLATE = FAItemReferences.create("ginkgo_pressure_plate");
    public static final ResourceKey<Item> GINKGO_FENCE = FAItemReferences.create("ginkgo_fence");
    public static final ResourceKey<Item> GINKGO_TRAPDOOR = FAItemReferences.create("ginkgo_trapdoor");
    public static final ResourceKey<Item> GINKGO_FENCE_GATE = FAItemReferences.create("ginkgo_fence_gate");
    public static final ResourceKey<Item> GINKGO_BUTTON = FAItemReferences.create("ginkgo_button");
    public static final ResourceKey<Item> GINKGO_SLAB = FAItemReferences.create("ginkgo_slab");
    public static final ResourceKey<Item> ARAUCARIA_PLANKS = FAItemReferences.create("ginkgo_planks");
    public static final ResourceKey<Item> ARAUCARIA_SAPLING = FAItemReferences.create("ginkgo_sapling");
    public static final ResourceKey<Item> ARAUCARIA_LOG = FAItemReferences.create("ginkgo_log");
    public static final ResourceKey<Item> STRIPPED_ARAUCARIA_LOG = FAItemReferences.create("stripped_ginkgo_log");
    public static final ResourceKey<Item> ARAUCARIA_WOOD = FAItemReferences.create("ginkgo_wood");
    public static final ResourceKey<Item> STRIPPED_ARAUCARIA_WOOD = FAItemReferences.create("stripped_ginkgo_wood");
    public static final ResourceKey<Item> ARAUCARIA_LEAVES = FAItemReferences.create("ginkgo_leaves");
    public static final ResourceKey<Item> ARAUCARIA_STAIRS = FAItemReferences.create("ginkgo_stairs");
    public static final ResourceKey<Item> ARAUCARIA_PRESSURE_PLATE = FAItemReferences.create("ginkgo_pressure_plate");
    public static final ResourceKey<Item> ARAUCARIA_FENCE = FAItemReferences.create("ginkgo_fence");
    public static final ResourceKey<Item> ARAUCARIA_TRAPDOOR = FAItemReferences.create("ginkgo_trapdoor");
    public static final ResourceKey<Item> ARAUCARIA_FENCE_GATE = FAItemReferences.create("ginkgo_fence_gate");
    public static final ResourceKey<Item> ARAUCARIA_BUTTON = FAItemReferences.create("ginkgo_button");
    public static final ResourceKey<Item> ARAUCARIA_SLAB = FAItemReferences.create("ginkgo_slab");

    private static ResourceKey<Item> create(String name) {
        return FAItems.ITEMS.reference(name);
    }
}
