package willatendo.fossilslegacy.server.item;

import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.item.*;
import net.minecraft.world.item.equipment.ArmorType;
import net.minecraft.world.item.equipment.Equippable;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import willatendo.fossilslegacy.platform.FAModloaderHelper;
import willatendo.fossilslegacy.server.block.FABlocks;
import willatendo.fossilslegacy.server.entity.FAEntityTypes;
import willatendo.fossilslegacy.server.entity.entities.dinosaur.quaternary.Nautilus;
import willatendo.fossilslegacy.server.entity.entities.projectile.Dart;
import willatendo.fossilslegacy.server.entity.entities.vehicle.Jeep;
import willatendo.fossilslegacy.server.fluid.FAFluids;
import willatendo.fossilslegacy.server.item.items.EggItem;
import willatendo.fossilslegacy.server.item.items.*;
import willatendo.fossilslegacy.server.level.FALevels;
import willatendo.fossilslegacy.server.pregnancy_types.FAPregnancyTypes;
import willatendo.fossilslegacy.server.tags.FAModelTypeTags;
import willatendo.fossilslegacy.server.utils.FAUtils;
import willatendo.simplelibrary.server.registry.SimpleHolder;
import willatendo.simplelibrary.server.registry.SimpleRegistry;

import java.util.List;
import java.util.function.Function;

public final class FAItems {
    public static final SimpleRegistry<Item> ITEMS = SimpleRegistry.create(Registries.ITEM, FAUtils.ID);

    public static final SimpleHolder<Item> MESOZOIC_FOSSIL = FAItems.register("mesozoic_fossil", Item::new);
    public static final SimpleHolder<Item> PLANT_FOSSIL = FAItems.register("plant_fossil", Item::new);
    public static final SimpleHolder<AnimalDNAItem> TRICERATOPS_DNA = FAItems.register("triceratops_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.TRICERATOPS::get, FAModelTypeTags.TRICERATOPS, properties));
    public static final SimpleHolder<AnimalDNAItem> VELOCIRAPTOR_DNA = FAItems.register("velociraptor_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.VELOCIRAPTOR::get, FAModelTypeTags.VELOCIRAPTOR, properties));
    public static final SimpleHolder<AnimalDNAItem> TYRANNOSAURUS_DNA = FAItems.register("tyrannosaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.TYRANNOSAURUS::get, FAModelTypeTags.TYRANNOSAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> PTERANODON_DNA = FAItems.register("pteranodon_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.PTERANODON::get, FAModelTypeTags.PTERANODON, properties));
    public static final SimpleHolder<AnimalDNAItem> NAUTILUS_DNA = FAItems.register("nautilus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, FAEntityTypes.NAUTILUS::get, properties));
    public static final SimpleHolder<AnimalDNAItem> FUTABASAURUS_DNA = FAItems.register("futabasaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.FUTABASAURUS::get, FAModelTypeTags.FUTABASAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> MOSASAURUS_DNA = FAItems.register("mosasaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.MOSASAURUS::get, FAModelTypeTags.MOSASAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> STEGOSAURUS_DNA = FAItems.register("stegosaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.JURASSIC, FAEntityTypes.STEGOSAURUS::get, FAModelTypeTags.STEGOSAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> DILOPHOSAURUS_DNA = FAItems.register("dilophosaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.JURASSIC, FAEntityTypes.DILOPHOSAURUS::get, FAModelTypeTags.DILOPHOSAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> BRACHIOSAURUS_DNA = FAItems.register("brachiosaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.JURASSIC, FAEntityTypes.BRACHIOSAURUS::get, FAModelTypeTags.BRACHIOSAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> CARNOTAURUS_DNA = FAItems.register("carnotaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.CARNOTAURUS::get, FAModelTypeTags.CARNOTAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> CRYOLOPHOSAURUS_DNA = FAItems.register("cryolophosaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.JURASSIC, FAEntityTypes.CRYOLOPHOSAURUS::get, FAModelTypeTags.CRYOLOPHOSAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> THERIZINOSAURUS_DNA = FAItems.register("therizinosaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.THERIZINOSAURUS::get, FAModelTypeTags.THERIZINOSAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> PACHYCEPHALOSAURUS_DNA = FAItems.register("pachycephalosaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.PACHYCEPHALOSAURUS::get, FAModelTypeTags.PACHYCEPHALOSAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> COMPSOGNATHUS_DNA = FAItems.register("compsognathus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.JURASSIC, FAEntityTypes.COMPSOGNATHUS::get, FAModelTypeTags.COMPSOGNATHUS, properties));
    public static final SimpleHolder<AnimalDNAItem> GALLIMIMUS_DNA = FAItems.register("gallimimus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.GALLIMIMUS::get, FAModelTypeTags.GALLIMIMUS, properties));
    public static final SimpleHolder<AnimalDNAItem> SPINOSAURUS_DNA = FAItems.register("spinosaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.SPINOSAURUS::get, FAModelTypeTags.SPINOSAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> ANKYLOSAURUS_DNA = FAItems.register("ankylosaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.ANKYLOSAURUS::get, FAModelTypeTags.ANKYLOSAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> DIMETRODON_DNA = FAItems.register("dimetrodon_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.PERMIAN, FAEntityTypes.DIMETRODON::get, FAModelTypeTags.DIMETRODON, properties));
    public static final SimpleHolder<AnimalDNAItem> ICHTHYOSAURUS_DNA = FAItems.register("ichthyosaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.JURASSIC, FAEntityTypes.ICHTHYOSAURUS::get, FAModelTypeTags.ICHTHYOSAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> DRYOSAURUS_DNA = FAItems.register("dryosaurus_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.JURASSIC, FAEntityTypes.DRYOSAURUS::get, FAModelTypeTags.DRYOSAURUS, properties));
    public static final SimpleHolder<AnimalDNAItem> BARYONYX_DNA = FAItems.register("baryonyx_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.CRETACEOUS, FAEntityTypes.BARYONYX::get, FAModelTypeTags.BARYONYX, properties));
    public static final SimpleHolder<PlantDNAItem> CYCAD_DNA = FAItems.register("cycad_dna", properties -> new PlantDNAItem(GeologicalTimeScale.Period.QUATERNARY, properties));
    public static final SimpleHolder<PlantDNAItem> HORSETAIL_DNA = FAItems.register("horsetail_dna", properties -> new PlantDNAItem(GeologicalTimeScale.Period.QUATERNARY, properties));
    public static final SimpleHolder<PlantDNAItem> JURASSIC_FERN_DNA = FAItems.register("jurassic_fern_dna", properties -> new PlantDNAItem(GeologicalTimeScale.Period.JURASSIC, properties));
    public static final SimpleHolder<PlantDNAItem> LEPIDODENDRON_DNA = FAItems.register("lepidodendron_dna", properties -> new PlantDNAItem(GeologicalTimeScale.Period.PERMIAN, properties));
    public static final SimpleHolder<PlantDNAItem> SIGILLARIA_DNA = FAItems.register("sigillaria_dna", properties -> new PlantDNAItem(GeologicalTimeScale.Period.PERMIAN, properties));
    public static final SimpleHolder<PlantDNAItem> CALAMITES_DNA = FAItems.register("calamites_dna", properties -> new PlantDNAItem(GeologicalTimeScale.Period.PERMIAN, properties));
    public static final SimpleHolder<PlantDNAItem> ARCHAEOPTERIS_DNA = FAItems.register("archaeopteris_dna", properties -> new PlantDNAItem(GeologicalTimeScale.Period.CARBONIFEROUS, properties));
    public static final SimpleHolder<PlantDNAItem> GINKGO_DNA = FAItems.register("ginkgo_dna", properties -> new PlantDNAItem(GeologicalTimeScale.Period.QUATERNARY, properties));
    public static final SimpleHolder<SeedItem> CYCAD_CONE = FAItems.register("cycad_cone", properties -> new SeedItem(FABlocks.CYCAD_HEAD.get(), properties.useItemDescriptionPrefix()));
    public static final SimpleHolder<SeedItem> LEPIDODENDRON_CONE = FAItems.register("lepidodendron_cone", properties -> new SeedItem(FABlocks.LEPIDODENDRON_SAPLING.get(), properties.useItemDescriptionPrefix()));
    public static final SimpleHolder<SeedItem> SIGILLARIA_SPORE = FAItems.register("sigillaria_spore", properties -> new SeedItem(FABlocks.SIGILLARIA_SAPLING.get(), properties.useItemDescriptionPrefix()));
    public static final SimpleHolder<SeedItem> CALAMITES_SPORE = FAItems.register("calamites_spore", properties -> new SeedItem(FABlocks.CALAMITES_SAPLING.get(), properties.useItemDescriptionPrefix()));
    public static final SimpleHolder<SeedItem> ARCHAEOPTERIS_SPORE = FAItems.register("archaeopteris_spore", properties -> new SeedItem(FABlocks.ARCHAEOPTERIS_SAPLING.get(), properties));
    public static final SimpleHolder<SeedItem> GINKGO_SPORE = FAItems.register("ginkgo_spore", properties -> new SeedItem(FABlocks.GINKGO_SAPLING.get(), properties));
    public static final SimpleHolder<EggItem> TRICERATOPS_EGG = FAItems.register("triceratops_egg", properties -> new EggItem(FAEntityTypes.TRICERATOPS_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.NON_LEGACY_TRICERATOPS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> VELOCIRAPTOR_EGG = FAItems.register("velociraptor_egg", properties -> new VelociraptorEggItem(GeologicalTimeScale.Period.CRETACEOUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> TYRANNOSAURUS_EGG = FAItems.register("tyrannosaurus_egg", properties -> new EggItem(FAEntityTypes.TYRANNOSAURUS_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.NON_LEGACY_TYRANNOSAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> PTERANODON_EGG = FAItems.register("pteranodon_egg", properties -> new EggItem(FAEntityTypes.PTERANODON_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.NON_LEGACY_PTERANODON, properties.stacksTo(1)));
    public static final SimpleHolder<PlaceEntityItem<Nautilus>> NAUTILUS_EGGS = FAItems.register("nautilus_eggs", properties -> new PlaceEntityItem<>(GeologicalTimeScale.Period.QUATERNARY, FAEntityTypes.NAUTILUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> FUTABASAURUS_EGG = FAItems.register("futabasaurus_egg", properties -> new EggItem(FAEntityTypes.FUTABASAURUS_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.NON_LEGACY_FUTABASAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> MOSASAURUS_EGG = FAItems.register("mosasaurus_egg", properties -> new EggItem(FAEntityTypes.MOSASAURUS_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.NON_LEGACY_MOSASAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> STEGOSAURUS_EGG = FAItems.register("stegosaurus_egg", properties -> new EggItem(FAEntityTypes.STEGOSAURUS_EGG::get, GeologicalTimeScale.Period.JURASSIC, FAModelTypeTags.NON_LEGACY_STEGOSAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> DILOPHOSAURUS_EGG = FAItems.register("dilophosaurus_egg", properties -> new EggItem(FAEntityTypes.DILOPHOSAURUS_EGG::get, GeologicalTimeScale.Period.JURASSIC, FAModelTypeTags.DILOPHOSAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> BRACHIOSAURUS_EGG = FAItems.register("brachiosaurus_egg", properties -> new EggItem(FAEntityTypes.BRACHIOSAURUS_EGG::get, GeologicalTimeScale.Period.JURASSIC, FAModelTypeTags.NON_LEGACY_BRACHIOSAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> CARNOTAURUS_EGG = FAItems.register("carnotaurus_egg", properties -> new EggItem(FAEntityTypes.CARNOTAURUS_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.NON_LEGACY_CARNOTAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> CRYOLOPHOSAURUS_EGG = FAItems.register("cryolophosaurus_egg", properties -> new EggItem(FAEntityTypes.CRYOLOPHOSAURUS_EGG::get, GeologicalTimeScale.Period.JURASSIC, FAModelTypeTags.NON_LEGACY_CRYOLOPHOSAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> THERIZINOSAURUS_EGG = FAItems.register("therizinosaurus_egg", properties -> new EggItem(FAEntityTypes.THERIZINOSAURUS_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.NON_LEGACY_THERIZINOSAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> PACHYCEPHALOSAURUS_EGG = FAItems.register("pachycephalosaurus_egg", properties -> new EggItem(FAEntityTypes.PACHYCEPHALOSAURUS_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.PACHYCEPHALOSAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> COMPSOGNATHUS_EGG = FAItems.register("compsognathus_egg", properties -> new EggItem(FAEntityTypes.COMPSOGNATHUS_EGG::get, GeologicalTimeScale.Period.JURASSIC, FAModelTypeTags.COMPSOGNATHUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> GALLIMIMUS_EGG = FAItems.register("gallimimus_egg", properties -> new EggItem(FAEntityTypes.GALLIMIMUS_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.GALLIMIMUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> SPINOSAURUS_EGG = FAItems.register("spinosaurus_egg", properties -> new EggItem(FAEntityTypes.SPINOSAURUS_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.SPINOSAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> ANKYLOSAURUS_EGG = FAItems.register("ankylosaurus_egg", properties -> new EggItem(FAEntityTypes.ANKYLOSAURUS_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.ANKYLOSAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> DIMETRODON_EGG = FAItems.register("dimetrodon_egg", properties -> new EggItem(FAEntityTypes.DIMETRODON_EGG::get, GeologicalTimeScale.Period.PERMIAN, FAModelTypeTags.DIMETRODON, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> ICHTHYOSAURUS_EGG = FAItems.register("ichthyosaurus_egg", properties -> new EggItem(FAEntityTypes.ICHTHYOSAURUS_EGG::get, GeologicalTimeScale.Period.JURASSIC, FAModelTypeTags.ICHTHYOSAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> DRYOSAURUS_EGG = FAItems.register("dryosaurus_egg", properties -> new EggItem(FAEntityTypes.DRYOSAURUS_EGG::get, GeologicalTimeScale.Period.JURASSIC, FAModelTypeTags.DRYOSAURUS, properties.stacksTo(1)));
    public static final SimpleHolder<EggItem> BARYONYX_EGG = FAItems.register("baryonyx_egg", properties -> new EggItem(FAEntityTypes.BARYONYX_EGG::get, GeologicalTimeScale.Period.CRETACEOUS, FAModelTypeTags.BARYONYX, properties.stacksTo(1)));
    public static final SimpleHolder<Item> RAW_TRICERATOPS = FAItems.register("raw_triceratops", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_VELOCIRAPTOR = FAItems.register("raw_velociraptor", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_TYRANNOSAURUS = FAItems.register("raw_tyrannosaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_PTERANODON = FAItems.register("raw_pteranodon", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<PlaceEntityItem<Nautilus>> NAUTILUS = FAItems.register("nautilus", properties -> new PlaceEntityItem<>(FAEntityTypes.NAUTILUS, properties.stacksTo(1)));
    public static final SimpleHolder<Item> RAW_FUTABASAURUS = FAItems.register("raw_futabasaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_MOSASAURUS = FAItems.register("raw_mosasaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_STEGOSAURUS = FAItems.register("raw_stegosaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_DILOPHOSAURUS = FAItems.register("raw_dilophosaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_BRACHIOSAURUS = FAItems.register("raw_brachiosaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_SMILODON = FAItems.register("raw_smilodon", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_MAMMOTH = FAItems.register("raw_mammoth", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_CARNOTAURUS = FAItems.register("raw_carnotaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_CRYOLOPHOSAURUS = FAItems.register("raw_cryolophosaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_THERIZINOSAURUS = FAItems.register("raw_therizinosaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_PACHYCEPHALOSAURUS = FAItems.register("raw_pachycephalosaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_COMPSOGNATHUS = FAItems.register("raw_compsognathus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_DODO = FAItems.register("raw_dodo", properties -> new Item(properties.food(FAFoods.RAW_BIRD, FAConsumables.BIRD)));
    public static final SimpleHolder<Item> RAW_MOA = FAItems.register("raw_moa", properties -> new Item(properties.food(FAFoods.RAW_BIRD, FAConsumables.BIRD)));
    public static final SimpleHolder<Item> RAW_GALLIMIMUS = FAItems.register("raw_gallimimus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_SPINOSAURUS = FAItems.register("raw_spinosaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_ANKYLOSAURUS = FAItems.register("raw_ankylosaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_DIMETRODON = FAItems.register("raw_dimetrodon", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_ICHTHYOSAURUS = FAItems.register("raw_ichthyosaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_ELASMOTHERIUM = FAItems.register("raw_elasmotherium", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_DRYOSAURUS = FAItems.register("raw_dryosaurus", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> RAW_BARYONYX = FAItems.register("raw_baryonyx", properties -> new Item(properties.food(FAFoods.RAW_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_TRICERATOPS = FAItems.register("cooked_triceratops", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_VELOCIRAPTOR = FAItems.register("cooked_velociraptor", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_TYRANNOSAURUS = FAItems.register("cooked_tyrannosaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_PTERANODON = FAItems.register("cooked_pteranodon", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> SIO_CHIU_LE = FAItems.register("sio_chiu_le", properties -> new Item(properties.food(FAFoods.SIO_CHIU_LE)));
    public static final SimpleHolder<Item> COOKED_FUTABASAURUS = FAItems.register("cooked_futabasaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_MOSASAURUS = FAItems.register("cooked_mosasaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_STEGOSAURUS = FAItems.register("cooked_stegosaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_DILOPHOSAURUS = FAItems.register("cooked_dilophosaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_BRACHIOSAURUS = FAItems.register("cooked_brachiosaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_SMILODON = FAItems.register("cooked_smilodon", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_MAMMOTH = FAItems.register("cooked_mammoth", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_CARNOTAURUS = FAItems.register("cooked_carnotaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_CRYOLOPHOSAURUS = FAItems.register("cooked_cryolophosaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_THERIZINOSAURUS = FAItems.register("cooked_therizinosaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_PACHYCEPHALOSAURUS = FAItems.register("cooked_pachycephalosaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_COMPSOGNATHUS = FAItems.register("cooked_compsognathus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_DODO = FAItems.register("cooked_dodo", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_MOA = FAItems.register("cooked_moa", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_GALLIMIMUS = FAItems.register("cooked_gallimimus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_SPINOSAURUS = FAItems.register("cooked_spinosaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_ANKYLOSAURUS = FAItems.register("cooked_ankylosaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_DIMETRODON = FAItems.register("cooked_dimetrodon", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_ICHTHYOSAURUS = FAItems.register("cooked_ichthyosaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_DRYOSAURUS = FAItems.register("cooked_dryosaurus", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_ELASMOTHERIUM = FAItems.register("cooked_elasmotherium", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> COOKED_BARYONYX = FAItems.register("cooked_baryonyx", properties -> new Item(properties.food(FAFoods.COOKED_DINOSAUR_MEAT)));
    public static final SimpleHolder<Item> TYRANNOSAURUS_TOOTH = FAItems.register("tyrannosaurus_tooth", Item::new);
    public static final SimpleHolder<ToothDaggerItem> TOOTH_DAGGER = FAItems.register("tooth_dagger", properties -> new ToothDaggerItem(FAToolMaterials.DAGGER, 3, -2.4F, properties));
    public static final SimpleHolder<Item> SKULL_STICK = FAItems.register("skull_stick", properties -> new Item(properties.stacksTo(1)));
    public static final SimpleHolder<TherizinosaurusClawsItem> THERIZINOSAURUS_CLAWS = FAItems.register("therizinosaurus_claws", properties -> new TherizinosaurusClawsItem(FAToolMaterials.DAGGER, 7, -3.5F, properties));
    public static final SimpleHolder<DinopediaItem> DINOPEDIA = FAItems.register("dinopedia", properties -> new DinopediaItem(properties.stacksTo(1)));
    public static final SimpleHolder<BucketFoodItem> RAW_CHICKEN_SOUP_BUCKET = FAItems.register("raw_chicken_soup_bucket", properties -> new BucketFoodItem(properties.stacksTo(1).craftRemainder(Items.BUCKET).food(FAFoods.RAW_CHICKEN_SOUP, FAConsumables.RAW_CHICKEN_SOUP)));
    public static final SimpleHolder<BucketFoodItem> RAW_BERRY_MEDLEY_BUCKET = FAItems.register("raw_berry_medley_bucket", properties -> new BucketFoodItem(properties.stacksTo(1).craftRemainder(Items.BUCKET).food(FAFoods.RAW_BERRY_MEDLEY_BUCKET)));
    public static final SimpleHolder<BucketFoodItem> COOKED_CHICKEN_SOUP_BUCKET = FAItems.register("cooked_chicken_soup_bucket", properties -> new BucketFoodItem(properties.stacksTo(1).craftRemainder(Items.BUCKET).food(FAFoods.COOKED_CHICKEN_SOUP)));
    public static final SimpleHolder<BucketFoodItem> COOKED_BERRY_MEDLEY_BUCKET = FAItems.register("cooked_berry_medley_bucket", properties -> new BucketFoodItem(properties.stacksTo(1).craftRemainder(Items.BUCKET).food(FAFoods.COOKED_BERRY_MEDLEY_BUCKET)));
    public static final SimpleHolder<ChickenEssanceBottleItem> CHICKEN_ESSENCE_BOTTLE = FAItems.register("chicken_essence_bottle", properties -> new ChickenEssanceBottleItem(properties.stacksTo(16).food(FAFoods.CHICKEN_ESSENCE)));
    public static final SimpleHolder<DrinkingGlassBottleItem> ROMANTIC_CONCOCTION_BOTTLE = FAItems.register("romantic_concoction_bottle", properties -> new DrinkingGlassBottleItem(properties.stacksTo(16).food(FAFoods.ROMANTIC_CONCOCTION)));
    public static final SimpleHolder<GeneticCodeItem> LEGACY_GENETIC_CODE = FAItems.register("legacy_genetic_code", properties -> GeneticCodeItem.modelGeneticCode(FAModelTypeTags.LEGACY, properties.stacksTo(1).rarity(Rarity.RARE)));
    public static final SimpleHolder<Item> NAUTILUS_SHELL = FAItems.register("nautilus_shell", properties -> new Item(properties.stacksTo(1)));
    public static final SimpleHolder<MagicConchItem> MAGIC_CONCH = FAItems.register("magic_conch", properties -> new MagicConchItem(properties.stacksTo(1)));
    public static final SimpleHolder<FrozenMeatItem> FROZEN_MEAT = FAItems.register("frozen_meat", properties -> new FrozenMeatItem(FAToolMaterials.ICED_MEAT, 3, -2.4F, properties));
    public static final SimpleHolder<SwordItem> BROKEN_FROZEN_MEAT = FAItems.register("broken_frozen_meat", properties -> new SwordItem(FAToolMaterials.ICED_MEAT, 3, -2.4F, properties));
    public static final SimpleHolder<AnimalDNAItem> ARMADILLO_DNA = FAItems.register("armadillo_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.ARMADILLO, properties));
    public static final SimpleHolder<AnimalDNAItem> AXOLOTL_DNA = FAItems.register("axolotl_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.AXOLOTL, properties));
    public static final SimpleHolder<AnimalDNAItem> CAT_DNA = FAItems.register("cat_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.CAT, properties));
    public static final SimpleHolder<AnimalDNAItem> CHICKEN_DNA = FAItems.register("chicken_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.CHICKEN, properties));
    public static final SimpleHolder<AnimalDNAItem> COW_DNA = FAItems.register("cow_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.COW, properties));
    public static final SimpleHolder<AnimalDNAItem> DOLPHIN_DNA = FAItems.register("dolphin_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.DOLPHIN, properties));
    public static final SimpleHolder<AnimalDNAItem> DONKEY_DNA = FAItems.register("donkey_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.DONKEY, properties));
    public static final SimpleHolder<AnimalDNAItem> FOX_DNA = FAItems.register("fox_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.FOX, properties));
    public static final SimpleHolder<AnimalDNAItem> FROG_DNA = FAItems.register("frog_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.FROG, properties));
    public static final SimpleHolder<AnimalDNAItem> GOAT_DNA = FAItems.register("goat_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.GOAT, properties));
    public static final SimpleHolder<AnimalDNAItem> HORSE_DNA = FAItems.register("horse_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.HORSE, properties));
    public static final SimpleHolder<AnimalDNAItem> LLAMA_DNA = FAItems.register("llama_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.LLAMA, properties));
    public static final SimpleHolder<AnimalDNAItem> MULE_DNA = FAItems.register("mule_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.MULE, properties));
    public static final SimpleHolder<AnimalDNAItem> OCELOT_DNA = FAItems.register("ocelot_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.OCELOT, properties));
    public static final SimpleHolder<AnimalDNAItem> PANDA_DNA = FAItems.register("panda_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.PANDA, properties));
    public static final SimpleHolder<AnimalDNAItem> PARROT_DNA = FAItems.register("parrot_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.PARROT, properties));
    public static final SimpleHolder<AnimalDNAItem> PIG_DNA = FAItems.register("pig_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.PIG, properties));
    public static final SimpleHolder<AnimalDNAItem> POLAR_BEAR_DNA = FAItems.register("polar_bear_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.POLAR_BEAR, properties));
    public static final SimpleHolder<AnimalDNAItem> RABBIT_DNA = FAItems.register("rabbit_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.RABBIT, properties));
    public static final SimpleHolder<AnimalDNAItem> SHEEP_DNA = FAItems.register("sheep_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.SHEEP, properties));
    public static final SimpleHolder<AnimalDNAItem> WOLF_DNA = FAItems.register("wolf_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.WOLF, properties));
    public static final SimpleHolder<AnimalDNAItem> SMILODON_DNA = FAItems.register("smilodon_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.NEOGENE, FAEntityTypes.SMILODON::get, FAModelTypeTags.SMILODON, properties));
    public static final SimpleHolder<AnimalDNAItem> MAMMOTH_DNA = FAItems.register("mammoth_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, FAEntityTypes.MAMMOTH::get, FAModelTypeTags.MAMMOTH, properties));
    public static final SimpleHolder<AnimalDNAItem> DODO_DNA = FAItems.register("dodo_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, FAEntityTypes.DODO::get, FAModelTypeTags.DODO, properties));
    public static final SimpleHolder<AnimalDNAItem> MOA_DNA = FAItems.register("moa_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.QUATERNARY, FAEntityTypes.MOA::get, FAModelTypeTags.MOA, properties));
    public static final SimpleHolder<AnimalDNAItem> ELASMOTHERIUM_DNA = FAItems.register("elasmotherium_dna", properties -> new AnimalDNAItem(GeologicalTimeScale.Period.PALEOGENE, FAEntityTypes.ELASMOTHERIUM::get, FAModelTypeTags.ELASMOTHERIUM, properties));
    public static final SimpleHolder<SyringeItem> ARMADILLO_EMBRYO_SYRINGE = FAItems.register("armadillo_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.ARMADILLO, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> CAT_EMBRYO_SYRINGE = FAItems.register("cat_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.CAT, properties.stacksTo(1)));
    public static final SimpleHolder<AnimalEggItem> INCUBATED_CHICKEN_EGG = FAItems.register("incubated_chicken_egg", properties -> new AnimalEggItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.CHICKEN, true, properties.stacksTo(16)));
    public static final SimpleHolder<SyringeItem> COW_EMBRYO_SYRINGE = FAItems.register("cow_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.COW, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> DOLPHIN_EMBRYO_SYRINGE = FAItems.register("dolphin_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.DOLPHIN, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> DONKEY_EMBRYO_SYRINGE = FAItems.register("donkey_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.DONKEY, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> FOX_EMBRYO_SYRINGE = FAItems.register("fox_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.FOX, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> GOAT_EMBRYO_SYRINGE = FAItems.register("goat_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.GOAT, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> HORSE_EMBRYO_SYRINGE = FAItems.register("horse_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.HORSE, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> LLAMA_EMBRYO_SYRINGE = FAItems.register("llama_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.LLAMA, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> MULE_EMBRYO_SYRINGE = FAItems.register("mule_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.MULE, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> OCELOT_EMBRYO_SYRINGE = FAItems.register("ocelot_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.OCELOT, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> PANDA_EMBRYO_SYRINGE = FAItems.register("panda_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.PANDA, properties.stacksTo(1)));
    public static final SimpleHolder<AnimalEggItem> INCUBATED_PARROT_EGG = FAItems.register("incubated_parrot_egg", properties -> new AnimalEggItem(GeologicalTimeScale.Period.QUATERNARY, () -> EntityType.PARROT, true, properties.stacksTo(16)));
    public static final SimpleHolder<SyringeItem> PIG_EMBRYO_SYRINGE = FAItems.register("pig_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.PIG, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> POLAR_BEAR_EMBRYO_SYRINGE = FAItems.register("polar_bear_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.POLAR_BEAR, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> RABBIT_EMBRYO_SYRINGE = FAItems.register("rabbit_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.RABBIT, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> SHEEP_EMBRYO_SYRINGE = FAItems.register("sheep_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.SHEEP, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> WOLF_EMBRYO_SYRINGE = FAItems.register("wolf_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.WOLF, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> SMILODON_EMBRYO_SYRINGE = FAItems.register("smilodon_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.NEOGENE, FAPregnancyTypes.SMILODON, FAModelTypeTags.NON_LEGACY_SMILODON, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> MAMMOTH_EMBRYO_SYRINGE = FAItems.register("mammoth_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.QUATERNARY, FAPregnancyTypes.MAMMOTH, FAModelTypeTags.NON_LEGACY_MAMMOTH, properties.stacksTo(1)));
    public static final SimpleHolder<SyringeItem> ELASMOTHERIUM_EMBRYO_SYRINGE = FAItems.register("elasmotherium_embryo_syringe", properties -> new SyringeItem(GeologicalTimeScale.Period.PALEOGENE, FAPregnancyTypes.ELASMOTHERIUM, FAModelTypeTags.ELASMOTHERIUM, properties.stacksTo(1)));
    public static final SimpleHolder<AnimalEggItem> INCUBATED_DODO_EGG = FAItems.register("incubated_dodo_egg", properties -> new AnimalEggItem(GeologicalTimeScale.Period.QUATERNARY, FAEntityTypes.DODO::get, true, FAModelTypeTags.DODO, properties.stacksTo(16)));
    public static final SimpleHolder<AnimalEggItem> DODO_EGG = FAItems.register("dodo_egg", properties -> new AnimalEggItem(GeologicalTimeScale.Period.QUATERNARY, FAEntityTypes.DODO::get, false, FAModelTypeTags.DODO, properties.stacksTo(16)));
    public static final SimpleHolder<AnimalEggItem> INCUBATED_MOA_EGG = FAItems.register("incubated_moa_egg", properties -> new AnimalEggItem(GeologicalTimeScale.Period.QUATERNARY, FAEntityTypes.MOA::get, true, FAModelTypeTags.MOA, properties.stacksTo(16)));
    public static final SimpleHolder<AnimalEggItem> MOA_EGG = FAItems.register("moa_egg", properties -> new AnimalEggItem(GeologicalTimeScale.Period.QUATERNARY, FAEntityTypes.MOA::get, false, FAModelTypeTags.MOA, properties.stacksTo(16)));
    public static final SimpleHolder<SeedItem> HORSETAIL_SPORE = FAItems.register("horsetail_spore", properties -> new SeedItem(FABlocks.SHORT_HORSETAIL.get(), properties.useItemDescriptionPrefix()));
    public static final SimpleHolder<SeedItem> JURASSIC_FERN_SPORES = FAItems.register("jurassic_fern_spores", properties -> new SeedItem(FABlocks.JURASSIC_FERN.get(), properties.useItemDescriptionPrefix()));
    public static final SimpleHolder<ArticulatedFossilItem> ARTICULATED_FOSSIL = FAItems.register("articulated_fossil", properties -> FAModloaderHelper.INSTANCE.getArticulatedFossilItem(properties.stacksTo(1)));
    public static final SimpleHolder<Item> RELIC_SCRAP = FAItems.register("relic_scrap", Item::new);
    public static final SimpleHolder<DecorationPlaqueItem> WHITE_DECORATION_PLAQUE = FAItems.register("white_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.WHITE_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> ORANGE_DECORATION_PLAQUE = FAItems.register("orange_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.ORANGE_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> MAGENTA_DECORATION_PLAQUE = FAItems.register("magenta_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.MAGENTA_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> LIGHT_BLUE_DECORATION_PLAQUE = FAItems.register("light_blue_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.LIGHT_BLUE_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> YELLOW_DECORATION_PLAQUE = FAItems.register("yellow_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.YELLOW_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> LIME_DECORATION_PLAQUE = FAItems.register("lime_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.LIME_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> PINK_DECORATION_PLAQUE = FAItems.register("pink_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.PINK_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> GRAY_DECORATION_PLAQUE = FAItems.register("gray_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.GRAY_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> LIGHT_GRAY_DECORATION_PLAQUE = FAItems.register("light_gray_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.LIGHT_GRAY_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> CYAN_DECORATION_PLAQUE = FAItems.register("cyan_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.CYAN_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> PURPLE_DECORATION_PLAQUE = FAItems.register("purple_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.PURPLE_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> BLUE_DECORATION_PLAQUE = FAItems.register("blue_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.BLUE_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> BROWN_DECORATION_PLAQUE = FAItems.register("brown_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.BROWN_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> GREEN_DECORATION_PLAQUE = FAItems.register("green_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.GREEN_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> RED_DECORATION_PLAQUE = FAItems.register("red_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.RED_DECORATION_POST.get(), properties));
    public static final SimpleHolder<DecorationPlaqueItem> BLACK_DECORATION_PLAQUE = FAItems.register("black_decoration_plaque", properties -> new DecorationPlaqueItem(FABlocks.BLACK_DECORATION_POST.get(), properties));
    public static final SimpleHolder<StoneTabletItem> STONE_TABLET = FAItems.register("stone_tablet", StoneTabletItem::new);
    public static final SimpleHolder<Item> ANCIENT_SWORD_ARTIFACT = FAItems.register("ancient_sword_artifact", Item::new);
    public static final SimpleHolder<Item> ANCIENT_SHOVEL_ARTIFACT = FAItems.register("ancient_shovel_artifact", Item::new);
    public static final SimpleHolder<Item> ANCIENT_PICKAXE_ARTIFACT = FAItems.register("ancient_pickaxe_artifact", Item::new);
    public static final SimpleHolder<Item> ANCIENT_AXE_ARTIFACT = FAItems.register("ancient_axe_artifact", Item::new);
    public static final SimpleHolder<Item> ANCIENT_HOE_ARTIFACT = FAItems.register("ancient_hoe_artifact", Item::new);
    public static final SimpleHolder<Item> ANCIENT_HELMET_ARTIFACT = FAItems.register("ancient_helmet_artifact", Item::new);
    public static final SimpleHolder<Item> ANCIENT_CHESTPLATE_ARTIFACT = FAItems.register("ancient_chestplate_artifact", Item::new);
    public static final SimpleHolder<Item> ANCIENT_LEGGINGS_ARTIFACT = FAItems.register("ancient_leggings_artifact", Item::new);
    public static final SimpleHolder<Item> ANCIENT_BOOTS_ARTIFACT = FAItems.register("ancient_boots_artifact", Item::new);
    public static final SimpleHolder<Item> SCARAB_GEM = FAItems.register("scarab_gem", Item::new);
    public static final SimpleHolder<Item> JADE = FAItems.register("jade", Item::new);
    public static final SimpleHolder<Item> JADE_OCELOT = FAItems.register("jade_ocelot", Item::new);
    public static final SimpleHolder<Item> JADE_VILLAGER = FAItems.register("jade_villager", Item::new);
    public static final SimpleHolder<Item> CODEX = FAItems.register("codex", Item::new);
    public static final SimpleHolder<Item> QUIPU = FAItems.register("quipu", Item::new);
    public static final SimpleHolder<CoinItem> OVERWORLD_COIN = FAItems.register("overworld_coin", properties -> new CoinItem(Level.OVERWORLD, properties));
    public static final SimpleHolder<CoinItem> ICE_AGE_COIN = FAItems.register("ice_age_coin", properties -> new CoinItem(Level.NETHER, properties));
    public static final SimpleHolder<CoinItem> PREHISTORIC_COIN = FAItems.register("prehistoric_coin", properties -> new CoinItem(FALevels.PREHISTORY, properties));
    public static final SimpleHolder<AncientSwordItem> ANCIENT_SWORD = FAItems.register("ancient_sword", properties -> new AncientSwordItem(FAToolMaterials.ANCIENT, 3, -2.4F, properties));
    public static final SimpleHolder<AncientShovelItem> ANCIENT_SHOVEL = FAItems.register("ancient_shovel", properties -> new AncientShovelItem(FAToolMaterials.ANCIENT, 1.5F, -3.0F, properties));
    public static final SimpleHolder<AncientPickaxeItem> ANCIENT_PICKAXE = FAItems.register("ancient_pickaxe", properties -> new AncientPickaxeItem(FAToolMaterials.ANCIENT, 1, -2.8F, properties));
    public static final SimpleHolder<AncientAxeItem> ANCIENT_AXE = FAItems.register("ancient_axe", properties -> new AncientAxeItem(FAToolMaterials.ANCIENT, 5.0F, -3.0F, properties));
    public static final SimpleHolder<AncientHoeItem> ANCIENT_HOE = FAItems.register("ancient_hoe", properties -> new AncientHoeItem(FAToolMaterials.ANCIENT, -2.0F, 0.0F, properties));
    public static final SimpleHolder<ArmorItem> ANCIENT_HELMET = FAItems.register("ancient_helmet", properties -> new ArmorItem(FAArmorMaterials.ANCIENT, ArmorType.HELMET, properties));
    public static final SimpleHolder<ArmorItem> ANCIENT_CHESTPLATE = FAItems.register("ancient_chestplate", properties -> new ArmorItem(FAArmorMaterials.ANCIENT, ArmorType.CHESTPLATE, properties));
    public static final SimpleHolder<ArmorItem> ANCIENT_LEGGINGS = FAItems.register("ancient_leggings", properties -> new ArmorItem(FAArmorMaterials.ANCIENT, ArmorType.LEGGINGS, properties));
    public static final SimpleHolder<ArmorItem> ANCIENT_BOOTS = FAItems.register("ancient_boots", properties -> new ArmorItem(FAArmorMaterials.ANCIENT, ArmorType.BOOTS, properties));
    public static final SimpleHolder<SwordItem> SCARAB_GEM_SWORD = FAItems.register("scarab_gem_sword", properties -> new SwordItem(FAToolMaterials.SCARAB_GEM, 3, -2.4F, properties.fireResistant()));
    public static final SimpleHolder<ShovelItem> SCARAB_GEM_SHOVEL = FAItems.register("scarab_gem_shovel", properties -> new ShovelItem(FAToolMaterials.SCARAB_GEM, 1.5F, -3.0F, properties.fireResistant()));
    public static final SimpleHolder<PickaxeItem> SCARAB_GEM_PICKAXE = FAItems.register("scarab_gem_pickaxe", properties -> new PickaxeItem(FAToolMaterials.SCARAB_GEM, 1, -2.8F, properties.fireResistant()));
    public static final SimpleHolder<AxeItem> SCARAB_GEM_AXE = FAItems.register("scarab_gem_axe", properties -> new AxeItem(FAToolMaterials.SCARAB_GEM, 5.0F, -3.0F, properties.fireResistant()));
    public static final SimpleHolder<HoeItem> SCARAB_GEM_HOE = FAItems.register("scarab_gem_hoe", properties -> new HoeItem(FAToolMaterials.SCARAB_GEM, -4.0F, 0.0F, properties.fireResistant()));
    public static final SimpleHolder<ArmorItem> SCARAB_GEM_HELMET = FAItems.register("scarab_gem_helmet", properties -> new ArmorItem(FAArmorMaterials.SCARAB_GEM, ArmorType.HELMET, properties.fireResistant().durability(ArmorType.HELMET.getDurability(40))));
    public static final SimpleHolder<ArmorItem> SCARAB_GEM_CHESTPLATE = FAItems.register("scarab_gem_chestplate", properties -> new ArmorItem(FAArmorMaterials.SCARAB_GEM, ArmorType.CHESTPLATE, properties.fireResistant().durability(ArmorType.CHESTPLATE.getDurability(40))));
    public static final SimpleHolder<ArmorItem> SCARAB_GEM_LEGGINGS = FAItems.register("scarab_gem_leggings", properties -> new ArmorItem(FAArmorMaterials.SCARAB_GEM, ArmorType.LEGGINGS, properties.fireResistant().durability(ArmorType.LEGGINGS.getDurability(40))));
    public static final SimpleHolder<ArmorItem> SCARAB_GEM_BOOTS = FAItems.register("scarab_gem_boots", properties -> new ArmorItem(FAArmorMaterials.SCARAB_GEM, ArmorType.BOOTS, properties.fireResistant().durability(ArmorType.BOOTS.getDurability(40))));
    public static final SimpleHolder<ModSmithingTemplateItem> SCARAB_GEM_UPGRADE_SMITHING_TEMPLATE = FAItems.register("scarab_gem_upgrade_smithing_template", ModSmithingTemplateItem::createGemUpgradeTemplate);
    public static final SimpleHolder<JavelinItem> WOODEN_JAVELIN = FAItems.register("wooden_javelin", properties -> new JavelinItem(ToolMaterial.WOOD, properties));
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_WOODEN_JAVELIN = FAItems.register("broken_wooden_javelin", properties -> new BrokenJavelinItem(ToolMaterial.WOOD, properties));
    public static final SimpleHolder<JavelinItem> STONE_JAVELIN = FAItems.register("stone_javelin", properties -> new JavelinItem(ToolMaterial.STONE, properties));
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_STONE_JAVELIN = FAItems.register("broken_stone_javelin", properties -> new BrokenJavelinItem(ToolMaterial.STONE, properties));
    public static final SimpleHolder<JavelinItem> IRON_JAVELIN = FAItems.register("iron_javelin", properties -> new JavelinItem(ToolMaterial.IRON, properties));
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_IRON_JAVELIN = FAItems.register("broken_iron_javelin", properties -> new BrokenJavelinItem(ToolMaterial.IRON, properties));
    public static final SimpleHolder<JavelinItem> GOLDEN_JAVELIN = FAItems.register("golden_javelin", properties -> new JavelinItem(ToolMaterial.GOLD, properties));
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_GOLDEN_JAVELIN = FAItems.register("broken_golden_javelin", properties -> new BrokenJavelinItem(ToolMaterial.GOLD, properties));
    public static final SimpleHolder<JavelinItem> DIAMOND_JAVELIN = FAItems.register("diamond_javelin", properties -> new JavelinItem(ToolMaterial.DIAMOND, properties));
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_DIAMOND_JAVELIN = FAItems.register("broken_diamond_javelin", properties -> new BrokenJavelinItem(ToolMaterial.DIAMOND, properties));
    public static final SimpleHolder<JavelinItem> NETHERITE_JAVELIN = FAItems.register("netherite_javelin", properties -> new JavelinItem(ToolMaterial.NETHERITE, properties));
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_NETHERITE_JAVELIN = FAItems.register("broken_netherite_javelin", properties -> new BrokenJavelinItem(ToolMaterial.NETHERITE, properties));
    public static final SimpleHolder<JavelinItem> SCARAB_GEM_JAVELIN = FAItems.register("scarab_gem_javelin", properties -> new JavelinItem(FAToolMaterials.SCARAB_GEM, properties));
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_SCARAB_GEM_JAVELIN = FAItems.register("broken_scarab_gem_javelin", properties -> new BrokenJavelinItem(FAToolMaterials.SCARAB_GEM, properties));
    public static final SimpleHolder<HammerItem> WOODEN_HAMMER = FAItems.register("wooden_hammer", properties -> new HammerItem(ToolMaterial.WOOD, 7.0F, -3.2F, properties));
    public static final SimpleHolder<HammerItem> STONE_HAMMER = FAItems.register("stone_hammer", properties -> new HammerItem(ToolMaterial.STONE, 7.0F, -3.2F, properties));
    public static final SimpleHolder<HammerItem> IRON_HAMMER = FAItems.register("iron_hammer", properties -> new HammerItem(ToolMaterial.IRON, 7.0F, -3.2F, properties));
    public static final SimpleHolder<HammerItem> GOLDEN_HAMMER = FAItems.register("golden_hammer", properties -> new HammerItem(ToolMaterial.GOLD, 7.0F, -3.2F, properties));
    public static final SimpleHolder<HammerItem> DIAMOND_HAMMER = FAItems.register("diamond_hammer", properties -> new HammerItem(ToolMaterial.DIAMOND, 7.0F, -3.2F, properties));
    public static final SimpleHolder<HammerItem> NETHERITE_HAMMER = FAItems.register("netherite_hammer", properties -> new HammerItem(ToolMaterial.NETHERITE, 7.0F, -3.2F, properties));
    public static final SimpleHolder<RifleItem> RIFLE = FAItems.register("rifle", properties -> new RifleItem(properties.stacksTo(1).durability(250)));
    public static final SimpleHolder<DartItem> GREEN_TRANQUILIZER_DART = FAItems.register("green_tranquilizer_dart", properties -> new DartItem(Dart.Color.GREEN, 5000, properties));
    public static final SimpleHolder<DartItem> RED_TRANQUILIZER_DART = FAItems.register("red_tranquilizer_dart", properties -> new DartItem(Dart.Color.RED, 20000, properties));
    public static final SimpleHolder<DartItem> BLUE_TRANQUILIZER_DART = FAItems.register("blue_tranquilizer_dart", properties -> new DartItem(Dart.Color.BLUE, 50000, properties));
    public static final SimpleHolder<BucketItem> TAR_BUCKET = FAItems.register("tar_bucket", properties -> new BucketItem(FAFluids.TAR.get(), properties));
    public static final SimpleHolder<PlaceEntityItem<Jeep>> JEEP_1993 = FAItems.register("1993_jeep", properties -> new PlaceEntityItem<>(FAEntityTypes.JEEP::get, properties));
    public static final SimpleHolder<SpawnEggItem> ANU_SPAWN_EGG = FAItems.register("anu_spawn_egg", properties -> new SpawnEggItem(FAEntityTypes.ANU.get(), properties));
    public static final SimpleHolder<SpawnEggItem> FAILURESAURUS_SPAWN_EGG = FAItems.register("failuresaurus_spawn_egg", properties -> new SpawnEggItem(FAEntityTypes.FAILURESAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> BRACHIOSAURUS_SPAWN_EGG = FAItems.register("brachiosaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.BRACHIOSAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> DILOPHOSAURUS_SPAWN_EGG = FAItems.register("dilophosaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.DILOPHOSAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> FUTABASAURUS_SPAWN_EGG = FAItems.register("futabasaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.FUTABASAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> MAMMOTH_SPAWN_EGG = FAItems.register("mammoth_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.MAMMOTH.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> MOSASAURUS_SPAWN_EGG = FAItems.register("mosasaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.MOSASAURUS.get(), properties));
    public static final SimpleHolder<SpawnEggItem> NAUTILUS_SPAWN_EGG = FAItems.register("nautilus_spawn_egg", properties -> new SpawnEggItem(FAEntityTypes.NAUTILUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> PTERANODON_SPAWN_EGG = FAItems.register("pteranodon_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.PTERANODON.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> SMILODON_SPAWN_EGG = FAItems.register("smilodon_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.SMILODON.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> STEGOSAURUS_SPAWN_EGG = FAItems.register("stegosaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.STEGOSAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> TRICERATOPS_SPAWN_EGG = FAItems.register("triceratops_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.TRICERATOPS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> TYRANNOSAURUS_SPAWN_EGG = FAItems.register("tyrannosaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.TYRANNOSAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> VELOCIRAPTOR_SPAWN_EGG = FAItems.register("velociraptor_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.VELOCIRAPTOR.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> CARNOTAURUS_SPAWN_EGG = FAItems.register("carnotaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.CARNOTAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> CRYOLOPHOSAURUS_SPAWN_EGG = FAItems.register("cryolophosaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.CRYOLOPHOSAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> THERIZINOSAURUS_SPAWN_EGG = FAItems.register("therizinosaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.THERIZINOSAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> PACHYCEPHALOSAURUS_SPAWN_EGG = FAItems.register("pachycephalosaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.PACHYCEPHALOSAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> COMPSOGNATHUS_SPAWN_EGG = FAItems.register("compsognathus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.COMPSOGNATHUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> DODO_SPAWN_EGG = FAItems.register("dodo_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.DODO.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> MOA_SPAWN_EGG = FAItems.register("moa_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.MOA.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> GALLIMIMUS_SPAWN_EGG = FAItems.register("gallimimus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.GALLIMIMUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> SPINOSAURUS_SPAWN_EGG = FAItems.register("spinosaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.SPINOSAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> ANKYLOSAURUS_SPAWN_EGG = FAItems.register("ankylosaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.ANKYLOSAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> DIMETRODON_SPAWN_EGG = FAItems.register("dimetrodon_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.DIMETRODON.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> ICHTHYOSAURUS_SPAWN_EGG = FAItems.register("ichthyosaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.ICHTHYOSAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> ELASMOTHERIUM_SPAWN_EGG = FAItems.register("elasmotherium_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.ELASMOTHERIUM.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> DRYOSAURUS_SPAWN_EGG = FAItems.register("dryosaurus_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.DRYOSAURUS.get(), properties));
    public static final SimpleHolder<DinosaurSpawnEggItem> BARYONYX_SPAWN_EGG = FAItems.register("baryonyx_spawn_egg", properties -> new DinosaurSpawnEggItem(FAEntityTypes.BARYONYX.get(), properties));

    public static final SimpleHolder<BlockItem> SKULL_BLOCK = FAItems.register("skull_block", properties -> new BlockItem(FABlocks.SKULL_BLOCK.get(), properties.useBlockDescriptionPrefix().component(DataComponents.EQUIPPABLE, Equippable.builder(EquipmentSlot.HEAD).setSwappable(false).setCameraOverlay(FAUtils.resource("misc/skullblur")).build())));
    public static final SimpleHolder<BlockItem> DNA_RECOMBINATOR = FAItems.register("dna_recombinator", properties -> new BlockItem(FABlocks.DNA_RECOMBINATOR.get(), properties.rarity(Rarity.UNCOMMON).useBlockDescriptionPrefix()));
    public static final SimpleHolder<PlaceOnWaterBlockItem> AXOLOTLSPAWN = FAItems.register("axolotlspawn", properties -> new PlaceOnWaterBlockPeriodItem(GeologicalTimeScale.Period.QUATERNARY, FABlocks.AXOLOTLSPAWN.get(), properties.useBlockDescriptionPrefix()));
    public static final SimpleHolder<CageBlockItem> SMALL_CAGE = FAItems.register("small_cage", properties -> new CageBlockItem(1, 1, FABlocks.SMALL_CAGE.get(), properties.stacksTo(1).useBlockDescriptionPrefix()));
    public static final SimpleHolder<SignItem> LEPIDODENDRON_SIGN = FAItems.register("lepidodendron_sign", properties -> new SignItem(FABlocks.LEPIDODENDRON_SIGN.get(), FABlocks.LEPIDODENDRON_WALL_SIGN.get(), properties.stacksTo(16).useBlockDescriptionPrefix()));
    public static final SimpleHolder<HangingSignItem> LEPIDODENDRON_HANGING_SIGN = FAItems.register("lepidodendron_hanging_sign", properties -> new HangingSignItem(FABlocks.LEPIDODENDRON_HANGING_SIGN.get(), FABlocks.LEPIDODENDRON_WALL_HANGING_SIGN.get(), properties.stacksTo(16).useBlockDescriptionPrefix()));
    public static final SimpleHolder<DoubleHighBlockItem> LEPIDODENDRON_DOOR = FAItems.register("lepidodendron_door", properties -> new DoubleHighBlockItem(FABlocks.LEPIDODENDRON_DOOR.get(), properties.useBlockDescriptionPrefix()));
    public static final SimpleHolder<SignItem> SIGILLARIA_SIGN = FAItems.register("sigillaria_sign", properties -> new SignItem(FABlocks.SIGILLARIA_SIGN.get(), FABlocks.SIGILLARIA_WALL_SIGN.get(), properties.stacksTo(16).useBlockDescriptionPrefix()));
    public static final SimpleHolder<HangingSignItem> SIGILLARIA_HANGING_SIGN = FAItems.register("sigillaria_hanging_sign", properties -> new HangingSignItem(FABlocks.SIGILLARIA_HANGING_SIGN.get(), FABlocks.SIGILLARIA_WALL_HANGING_SIGN.get(), properties.stacksTo(16).useBlockDescriptionPrefix()));
    public static final SimpleHolder<DoubleHighBlockItem> SIGILLARIA_DOOR = FAItems.register("sigillaria_door", properties -> new DoubleHighBlockItem(FABlocks.SIGILLARIA_DOOR.get(), properties.useBlockDescriptionPrefix()));
    public static final SimpleHolder<SignItem> CALAMITES_SIGN = FAItems.register("calamites_sign", properties -> new SignItem(FABlocks.CALAMITES_SIGN.get(), FABlocks.CALAMITES_WALL_SIGN.get(), properties.stacksTo(16).useBlockDescriptionPrefix()));
    public static final SimpleHolder<HangingSignItem> CALAMITES_HANGING_SIGN = FAItems.register("calamites_hanging_sign", properties -> new HangingSignItem(FABlocks.CALAMITES_HANGING_SIGN.get(), FABlocks.CALAMITES_WALL_HANGING_SIGN.get(), properties.stacksTo(16).useBlockDescriptionPrefix()));
    public static final SimpleHolder<DoubleHighBlockItem> CALAMITES_DOOR = FAItems.register("calamites_door", properties -> new DoubleHighBlockItem(FABlocks.CALAMITES_DOOR.get(), properties.useBlockDescriptionPrefix()));
    public static final SimpleHolder<SignItem> ARCHAEOPTERIS_SIGN = FAItems.register("archaeopteris_sign", properties -> new SignItem(FABlocks.ARCHAEOPTERIS_SIGN.get(), FABlocks.ARCHAEOPTERIS_WALL_SIGN.get(), properties.stacksTo(16).useBlockDescriptionPrefix()));
    public static final SimpleHolder<HangingSignItem> ARCHAEOPTERIS_HANGING_SIGN = FAItems.register("archaeopteris_hanging_sign", properties -> new HangingSignItem(FABlocks.ARCHAEOPTERIS_HANGING_SIGN.get(), FABlocks.ARCHAEOPTERIS_WALL_HANGING_SIGN.get(), properties.stacksTo(16).useBlockDescriptionPrefix()));
    public static final SimpleHolder<DoubleHighBlockItem> ARCHAEOPTERIS_DOOR = FAItems.register("archaeopteris_door", properties -> new DoubleHighBlockItem(FABlocks.ARCHAEOPTERIS_DOOR.get(), properties.useBlockDescriptionPrefix()));
    public static final SimpleHolder<SignItem> GINKGO_SIGN = FAItems.register("ginkgo_sign", properties -> new SignItem(FABlocks.GINKGO_SIGN.get(), FABlocks.GINKGO_WALL_SIGN.get(), properties.stacksTo(16).useBlockDescriptionPrefix()));
    public static final SimpleHolder<HangingSignItem> GINKGO_HANGING_SIGN = FAItems.register("ginkgo_hanging_sign", properties -> new HangingSignItem(FABlocks.GINKGO_HANGING_SIGN.get(), FABlocks.GINKGO_WALL_HANGING_SIGN.get(), properties.stacksTo(16).useBlockDescriptionPrefix()));
    public static final SimpleHolder<DoubleHighBlockItem> GINKGO_DOOR = FAItems.register("ginkgo_door", properties -> new DoubleHighBlockItem(FABlocks.GINKGO_DOOR.get(), properties.useBlockDescriptionPrefix()));

    public static final SimpleHolder<BoatItem> LEPIDODENDRON_BOAT = FAItems.register("lepidodendron_boat", properties -> new BoatItem(FAEntityTypes.LEPIDODENDRON_BOAT.get(), properties.stacksTo(1)));
    public static final SimpleHolder<BoatItem> LEPIDODENDRON_CHEST_BOAT = FAItems.register("lepidodendron_chest_boat", properties -> new BoatItem(FAEntityTypes.LEPIDODENDRON_CHEST_BOAT.get(), properties.stacksTo(1)));
    public static final SimpleHolder<BoatItem> SIGILLARIA_BOAT = FAItems.register("sigillaria_boat", properties -> new BoatItem(FAEntityTypes.SIGILLARIA_BOAT.get(), properties.stacksTo(1)));
    public static final SimpleHolder<BoatItem> SIGILLARIA_CHEST_BOAT = FAItems.register("sigillaria_chest_boat", properties -> new BoatItem(FAEntityTypes.SIGILLARIA_CHEST_BOAT.get(), properties.stacksTo(1)));
    public static final SimpleHolder<BoatItem> CALAMITES_BOAT = FAItems.register("calamites_boat", properties -> new BoatItem(FAEntityTypes.CALAMITES_BOAT.get(), properties.stacksTo(1)));
    public static final SimpleHolder<BoatItem> CALAMITES_CHEST_BOAT = FAItems.register("calamites_chest_boat", properties -> new BoatItem(FAEntityTypes.CALAMITES_CHEST_BOAT.get(), properties.stacksTo(1)));
    public static final SimpleHolder<BoatItem> ARCHAEOPTERIS_BOAT = FAItems.register("archaeopteris_boat", properties -> new BoatItem(FAEntityTypes.ARCHAEOPTERIS_BOAT.get(), properties.stacksTo(1)));
    public static final SimpleHolder<BoatItem> ARCHAEOPTERIS_CHEST_BOAT = FAItems.register("archaeopteris_chest_boat", properties -> new BoatItem(FAEntityTypes.ARCHAEOPTERIS_CHEST_BOAT.get(), properties.stacksTo(1)));
    public static final SimpleHolder<BoatItem> GINKGO_BOAT = FAItems.register("ginkgo_boat", properties -> new BoatItem(FAEntityTypes.GINKGO_BOAT.get(), properties.stacksTo(1)));
    public static final SimpleHolder<BoatItem> GINKGO_CHEST_BOAT = FAItems.register("ginkgo_chest_boat", properties -> new BoatItem(FAEntityTypes.GINKGO_CHEST_BOAT.get(), properties.stacksTo(1)));

    public static final SimpleHolder<DebugItem> DEBUG_MAX_HUNGER = FAItems.register("debug_max_hunger", properties -> new DebugItem(DebugItem.debugMaxHunger(), properties));
    public static final SimpleHolder<DebugItem> DEBUG_MAX_HEALTH = FAItems.register("debug_max_health", properties -> new DebugItem(DebugItem.debugMaxHealth(), properties));
    public static final SimpleHolder<DebugItem> DEBUG_FULL_GROWN = FAItems.register("debug_full_grown", properties -> new DebugItem(DebugItem.debugFullGrown(), properties));
    public static final SimpleHolder<DebugItem> DEBUG_BABY = FAItems.register("debug_baby", properties -> new DebugItem(DebugItem.debugBaby(), properties));
    public static final SimpleHolder<DebugItem> DEBUG_TAME = FAItems.register("debug_tame", properties -> new DebugItem(DebugItem.debugTame(), properties));
    public static final SimpleHolder<DebugItem> DEBUG_CHANGE_GENETICS = FAItems.register("debug_change_genetics", properties -> new DebugItem(DebugItem.debugChangeGenetics(), properties));

    public static final ResourceKey<Item> LEPIDODENDRON_PLANKS = FAItems.blockReference("lepidodendron_planks");
    public static final ResourceKey<Item> LEPIDODENDRON_SAPLING = FAItems.blockReference("lepidodendron_sapling");
    public static final ResourceKey<Item> LEPIDODENDRON_LOG = FAItems.blockReference("lepidodendron_log");
    public static final ResourceKey<Item> STRIPPED_LEPIDODENDRON_LOG = FAItems.blockReference("stripped_lepidodendron_log");
    public static final ResourceKey<Item> LEPIDODENDRON_WOOD = FAItems.blockReference("lepidodendron_wood");
    public static final ResourceKey<Item> STRIPPED_LEPIDODENDRON_WOOD = FAItems.blockReference("stripped_lepidodendron_wood");
    public static final ResourceKey<Item> LEPIDODENDRON_LEAVES = FAItems.blockReference("lepidodendron_leaves");
    public static final ResourceKey<Item> LEPIDODENDRON_STAIRS = FAItems.blockReference("lepidodendron_stairs");
    public static final ResourceKey<Item> LEPIDODENDRON_PRESSURE_PLATE = FAItems.blockReference("lepidodendron_pressure_plate");
    public static final ResourceKey<Item> LEPIDODENDRON_FENCE = FAItems.blockReference("lepidodendron_fence");
    public static final ResourceKey<Item> LEPIDODENDRON_TRAPDOOR = FAItems.blockReference("lepidodendron_trapdoor");
    public static final ResourceKey<Item> LEPIDODENDRON_FENCE_GATE = FAItems.blockReference("lepidodendron_fence_gate");
    public static final ResourceKey<Item> POTTED_LEPIDODENDRON_SAPLING = FAItems.blockReference("potted_lepidodendron_sapling");
    public static final ResourceKey<Item> LEPIDODENDRON_BUTTON = FAItems.blockReference("lepidodendron_button");
    public static final ResourceKey<Item> LEPIDODENDRON_SLAB = FAItems.blockReference("lepidodendron_slab");
    public static final ResourceKey<Item> SIGILLARIA_PLANKS = FAItems.blockReference("sigillaria_planks");
    public static final ResourceKey<Item> SIGILLARIA_SAPLING = FAItems.blockReference("sigillaria_sapling");
    public static final ResourceKey<Item> SIGILLARIA_LOG = FAItems.blockReference("sigillaria_log");
    public static final ResourceKey<Item> STRIPPED_SIGILLARIA_LOG = FAItems.blockReference("stripped_sigillaria_log");
    public static final ResourceKey<Item> SIGILLARIA_WOOD = FAItems.blockReference("sigillaria_wood");
    public static final ResourceKey<Item> STRIPPED_SIGILLARIA_WOOD = FAItems.blockReference("stripped_sigillaria_wood");
    public static final ResourceKey<Item> SIGILLARIA_LEAVES = FAItems.blockReference("sigillaria_leaves");
    public static final ResourceKey<Item> SIGILLARIA_STAIRS = FAItems.blockReference("sigillaria_stairs");
    public static final ResourceKey<Item> SIGILLARIA_PRESSURE_PLATE = FAItems.blockReference("sigillaria_pressure_plate");
    public static final ResourceKey<Item> SIGILLARIA_FENCE = FAItems.blockReference("sigillaria_fence");
    public static final ResourceKey<Item> SIGILLARIA_TRAPDOOR = FAItems.blockReference("sigillaria_trapdoor");
    public static final ResourceKey<Item> SIGILLARIA_FENCE_GATE = FAItems.blockReference("sigillaria_fence_gate");
    public static final ResourceKey<Item> POTTED_SIGILLARIA_SAPLING = FAItems.blockReference("potted_sigillaria_sapling");
    public static final ResourceKey<Item> SIGILLARIA_BUTTON = FAItems.blockReference("sigillaria_button");
    public static final ResourceKey<Item> SIGILLARIA_SLAB = FAItems.blockReference("sigillaria_slab");
    public static final ResourceKey<Item> CALAMITES_PLANKS = FAItems.blockReference("calamites_planks");
    public static final ResourceKey<Item> CALAMITES_SAPLING = FAItems.blockReference("calamites_sapling");
    public static final ResourceKey<Item> CALAMITES_LOG = FAItems.blockReference("calamites_log");
    public static final ResourceKey<Item> STRIPPED_CALAMITES_LOG = FAItems.blockReference("stripped_calamites_log");
    public static final ResourceKey<Item> CALAMITES_WOOD = FAItems.blockReference("calamites_wood");
    public static final ResourceKey<Item> STRIPPED_CALAMITES_WOOD = FAItems.blockReference("stripped_calamites_wood");
    public static final ResourceKey<Item> CALAMITES_LEAVES = FAItems.blockReference("calamites_leaves");
    public static final ResourceKey<Item> CALAMITES_STAIRS = FAItems.blockReference("calamites_stairs");
    public static final ResourceKey<Item> CALAMITES_PRESSURE_PLATE = FAItems.blockReference("calamites_pressure_plate");
    public static final ResourceKey<Item> CALAMITES_FENCE = FAItems.blockReference("calamites_fence");
    public static final ResourceKey<Item> CALAMITES_TRAPDOOR = FAItems.blockReference("calamites_trapdoor");
    public static final ResourceKey<Item> CALAMITES_FENCE_GATE = FAItems.blockReference("calamites_fence_gate");
    public static final ResourceKey<Item> POTTED_CALAMITES_SAPLING = FAItems.blockReference("potted_calamites_sapling");
    public static final ResourceKey<Item> CALAMITES_BUTTON = FAItems.blockReference("calamites_button");
    public static final ResourceKey<Item> CALAMITES_SLAB = FAItems.blockReference("calamites_slab");
    public static final ResourceKey<Item> ARCHAEOPTERIS_PLANKS = FAItems.blockReference("archaeopteris_planks");
    public static final ResourceKey<Item> ARCHAEOPTERIS_SAPLING = FAItems.blockReference("archaeopteris_sapling");
    public static final ResourceKey<Item> ARCHAEOPTERIS_LOG = FAItems.blockReference("archaeopteris_log");
    public static final ResourceKey<Item> STRIPPED_ARCHAEOPTERIS_LOG = FAItems.blockReference("stripped_archaeopteris_log");
    public static final ResourceKey<Item> ARCHAEOPTERIS_WOOD = FAItems.blockReference("archaeopteris_wood");
    public static final ResourceKey<Item> STRIPPED_ARCHAEOPTERIS_WOOD = FAItems.blockReference("stripped_archaeopteris_wood");
    public static final ResourceKey<Item> ARCHAEOPTERIS_LEAVES = FAItems.blockReference("archaeopteris_leaves");
    public static final ResourceKey<Item> ARCHAEOPTERIS_STAIRS = FAItems.blockReference("archaeopteris_stairs");
    public static final ResourceKey<Item> ARCHAEOPTERIS_PRESSURE_PLATE = FAItems.blockReference("archaeopteris_pressure_plate");
    public static final ResourceKey<Item> ARCHAEOPTERIS_FENCE = FAItems.blockReference("archaeopteris_fence");
    public static final ResourceKey<Item> ARCHAEOPTERIS_TRAPDOOR = FAItems.blockReference("archaeopteris_trapdoor");
    public static final ResourceKey<Item> ARCHAEOPTERIS_FENCE_GATE = FAItems.blockReference("archaeopteris_fence_gate");
    public static final ResourceKey<Item> POTTED_ARCHAEOPTERIS_SAPLING = FAItems.blockReference("potted_archaeopteris_sapling");
    public static final ResourceKey<Item> ARCHAEOPTERIS_BUTTON = FAItems.blockReference("archaeopteris_button");
    public static final ResourceKey<Item> ARCHAEOPTERIS_SLAB = FAItems.blockReference("archaeopteris_slab");
    public static final ResourceKey<Item> GINKGO_PLANKS = FAItems.blockReference("ginkgo_planks");
    public static final ResourceKey<Item> GINKGO_SAPLING = FAItems.blockReference("ginkgo_sapling");
    public static final ResourceKey<Item> GINKGO_LOG = FAItems.blockReference("ginkgo_log");
    public static final ResourceKey<Item> STRIPPED_GINKGO_LOG = FAItems.blockReference("stripped_ginkgo_log");
    public static final ResourceKey<Item> GINKGO_WOOD = FAItems.blockReference("ginkgo_wood");
    public static final ResourceKey<Item> STRIPPED_GINKGO_WOOD = FAItems.blockReference("stripped_ginkgo_wood");
    public static final ResourceKey<Item> GINKGO_LEAVES = FAItems.blockReference("ginkgo_leaves");
    public static final ResourceKey<Item> GINKGO_STAIRS = FAItems.blockReference("ginkgo_stairs");
    public static final ResourceKey<Item> GINKGO_PRESSURE_PLATE = FAItems.blockReference("ginkgo_pressure_plate");
    public static final ResourceKey<Item> GINKGO_FENCE = FAItems.blockReference("ginkgo_fence");
    public static final ResourceKey<Item> GINKGO_TRAPDOOR = FAItems.blockReference("ginkgo_trapdoor");
    public static final ResourceKey<Item> GINKGO_FENCE_GATE = FAItems.blockReference("ginkgo_fence_gate");
    public static final ResourceKey<Item> POTTED_GINKGO_SAPLING = FAItems.blockReference("potted_ginkgo_sapling");
    public static final ResourceKey<Item> GINKGO_BUTTON = FAItems.blockReference("ginkgo_button");
    public static final ResourceKey<Item> GINKGO_SLAB = FAItems.blockReference("ginkgo_slab");
    public static final SimpleHolder<DoubleHighBlockItem> TALL_HORSETAIL = FAItems.register("tall_horsetail", properties -> new DoubleHighBlockItem(FABlocks.TALL_HORSETAIL.get(), properties.useBlockDescriptionPrefix()));

    private static ResourceKey<Item> blockReference(String id) {
        return ResourceKey.create(Registries.ITEM, FAUtils.resource(id));
    }

    private static <T extends Item> SimpleHolder<T> register(String name, Function<Item.Properties, T> item) {
        ResourceKey<Item> id = ResourceKey.create(Registries.ITEM, FAUtils.resource(name));
        return ITEMS.register(name, () -> item.apply(new Item.Properties().setId(id)));
    }

    static {
        List<SimpleHolder<? extends Block>> exceptions = List.of(FABlocks.SKULL_BLOCK, FABlocks.DNA_RECOMBINATOR, FABlocks.AXOLOTLSPAWN, FABlocks.RAW_CHICKEN_SOUP_CAULDRON, FABlocks.COOKED_CHICKEN_SOUP_CAULDRON, FABlocks.RAW_BERRY_MEDLEY_CAULDRON, FABlocks.COOKED_BERRY_MEDLEY_CAULDRON, FABlocks.RED_DECORATION_POST, FABlocks.BLACK_DECORATION_POST, FABlocks.BLUE_DECORATION_POST, FABlocks.BROWN_DECORATION_POST, FABlocks.CYAN_DECORATION_POST, FABlocks.GRAY_DECORATION_POST, FABlocks.GREEN_DECORATION_POST, FABlocks.LIGHT_BLUE_DECORATION_POST, FABlocks.LIGHT_GRAY_DECORATION_POST, FABlocks.LIME_DECORATION_POST, FABlocks.MAGENTA_DECORATION_POST, FABlocks.ORANGE_DECORATION_POST, FABlocks.PINK_DECORATION_POST, FABlocks.PURPLE_DECORATION_POST, FABlocks.WHITE_DECORATION_POST, FABlocks.YELLOW_DECORATION_POST, FABlocks.LEPIDODENDRON_SIGN, FABlocks.LEPIDODENDRON_WALL_SIGN, FABlocks.LEPIDODENDRON_HANGING_SIGN, FABlocks.LEPIDODENDRON_WALL_HANGING_SIGN, FABlocks.LEPIDODENDRON_DOOR, FABlocks.POTTED_LEPIDODENDRON_SAPLING, FABlocks.SIGILLARIA_SIGN, FABlocks.SIGILLARIA_WALL_SIGN, FABlocks.SIGILLARIA_HANGING_SIGN, FABlocks.SIGILLARIA_WALL_HANGING_SIGN, FABlocks.SIGILLARIA_DOOR, FABlocks.POTTED_SIGILLARIA_SAPLING, FABlocks.CALAMITES_SIGN, FABlocks.CALAMITES_WALL_SIGN, FABlocks.CALAMITES_HANGING_SIGN, FABlocks.CALAMITES_WALL_HANGING_SIGN, FABlocks.CALAMITES_DOOR, FABlocks.POTTED_CALAMITES_SAPLING, FABlocks.ARCHAEOPTERIS_SIGN, FABlocks.ARCHAEOPTERIS_WALL_SIGN, FABlocks.ARCHAEOPTERIS_HANGING_SIGN, FABlocks.ARCHAEOPTERIS_WALL_HANGING_SIGN, FABlocks.ARCHAEOPTERIS_DOOR, FABlocks.POTTED_ARCHAEOPTERIS_SAPLING, FABlocks.GINKGO_SIGN, FABlocks.GINKGO_WALL_SIGN, FABlocks.GINKGO_HANGING_SIGN, FABlocks.GINKGO_WALL_HANGING_SIGN, FABlocks.GINKGO_DOOR, FABlocks.POTTED_GINKGO_SAPLING, FABlocks.TALL_HORSETAIL, FABlocks.TAR, FABlocks.SMALL_CAGE);
        FABlocks.BLOCKS.getEntriesView().stream().filter(simpleHolder -> !exceptions.contains(simpleHolder)).forEach(simpleHolder -> FAItems.register(simpleHolder.getId().getPath(), properties -> new BlockItem(simpleHolder.get(), properties.useBlockDescriptionPrefix())));
    }
}
