package willatendo.fossilslegacy.server.model_type;

import net.minecraft.core.Holder;
import net.minecraft.core.HolderGetter;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import willatendo.fossilslegacy.server.pattern_type.FAPatternTypes;
import willatendo.fossilslegacy.server.pattern_type.PatternType;
import willatendo.fossilslegacy.server.registry.FARegistries;
import willatendo.fossilslegacy.server.utils.FAUtils;

public final class FAModelTypes {
    public static final ResourceKey<ModelType> ANKYLOSAURUS = FAModelTypes.create("ankylosaurus");
    public static final ResourceKey<ModelType> BRACHIOSAURUS = FAModelTypes.create("brachiosaurus");
    public static final ResourceKey<ModelType> CARNOTAURUS = FAModelTypes.create("carnotaurus");
    public static final ResourceKey<ModelType> RED_CARNOTAURUS = FAModelTypes.create("red_carnotaurus");
    public static final ResourceKey<ModelType> COMPSOGNATHUS = FAModelTypes.create("compsognathus");
    public static final ResourceKey<ModelType> CRYOLOPHOSAURUS = FAModelTypes.create("cryolophosaurus");
    public static final ResourceKey<ModelType> DILOPHOSAURUS = FAModelTypes.create("dilophosaurus");
    public static final ResourceKey<ModelType> DIMETRODON = FAModelTypes.create("dimetrodon");
    public static final ResourceKey<ModelType> DODO = FAModelTypes.create("dodo");
    public static final ResourceKey<ModelType> FUTABASAURUS = FAModelTypes.create("futabasaurus");
    public static final ResourceKey<ModelType> GALLIMIMUS = FAModelTypes.create("gallimimus");
    public static final ResourceKey<ModelType> ICHTHYOSAURUS = FAModelTypes.create("ichthyosaurus");
    public static final ResourceKey<ModelType> MAMMOTH = FAModelTypes.create("mammoth");
    public static final ResourceKey<ModelType> MOA = FAModelTypes.create("moa");
    public static final ResourceKey<ModelType> MOSASAURUS = FAModelTypes.create("mosasaurus");
    public static final ResourceKey<ModelType> PACHYCEPHALOSAURUS = FAModelTypes.create("pachycephalosaurus");
    public static final ResourceKey<ModelType> PTERANODON = FAModelTypes.create("pteranodon");
    public static final ResourceKey<ModelType> SMILODON = FAModelTypes.create("smilodon");
    public static final ResourceKey<ModelType> SPINOSAURUS = FAModelTypes.create("spinosaurus");
    public static final ResourceKey<ModelType> STEGOSAURUS = FAModelTypes.create("stegosaurus");
    public static final ResourceKey<ModelType> THERIZINOSAURUS = FAModelTypes.create("therizinosaurus");
    public static final ResourceKey<ModelType> TRICERATOPS = FAModelTypes.create("triceratops");
    public static final ResourceKey<ModelType> BROWN_TRICERATOPS = FAModelTypes.create("brown_triceratops");
    public static final ResourceKey<ModelType> TYRANNOSAURUS = FAModelTypes.create("tyrannosaurus");
    public static final ResourceKey<ModelType> VELOCIRAPTOR = FAModelTypes.create("velociraptor");
    public static final ResourceKey<ModelType> SANDY_VELOCIRAPTOR = FAModelTypes.create("sandy_velociraptor");
    public static final ResourceKey<ModelType> WHITE_VELOCIRAPTOR = FAModelTypes.create("white_velociraptor");

    public static final ResourceKey<ModelType> LEGACY_BRACHIOSAURUS = FAModelTypes.create("legacy_brachiosaurus");
    public static final ResourceKey<ModelType> LEGACY_CARNOTAURUS = FAModelTypes.create("legacy_carnotaurus");
    public static final ResourceKey<ModelType> LEGACY_RED_CARNOTAURUS = FAModelTypes.create("legacy_red_carnotaurus");
    public static final ResourceKey<ModelType> LEGACY_CRYOLOPHOSAURUS = FAModelTypes.create("legacy_cryolophosaurus");
    public static final ResourceKey<ModelType> LEGACY_DILOPHOSAURUS = FAModelTypes.create("legacy_dilophosaurus");
    public static final ResourceKey<ModelType> LEGACY_FUTABASAURUS = FAModelTypes.create("legacy_futabasaurus");
    public static final ResourceKey<ModelType> LEGACY_MAMMOTH = FAModelTypes.create("legacy_mammoth");
    public static final ResourceKey<ModelType> LEGACY_MOSASAURUS = FAModelTypes.create("legacy_mosasaurus");
    public static final ResourceKey<ModelType> LEGACY_PTERANODON = FAModelTypes.create("legacy_pteranodon");
    public static final ResourceKey<ModelType> LEGACY_SMILODON = FAModelTypes.create("legacy_smilodon");
    public static final ResourceKey<ModelType> LEGACY_STEGOSAURUS = FAModelTypes.create("legacy_stegosaurus");
    public static final ResourceKey<ModelType> LEGACY_THERIZINOSAURUS = FAModelTypes.create("legacy_therizinosaurus");
    public static final ResourceKey<ModelType> LEGACY_FEATHERLESS_THERIZINOSAURUS = FAModelTypes.create("legacy_featherless_therizinosaurus");
    public static final ResourceKey<ModelType> LEGACY_TRICERATOPS = FAModelTypes.create("legacy_triceratops");
    public static final ResourceKey<ModelType> LEGACY_BROWN_TRICERATOPS = FAModelTypes.create("legacy_brown_triceratops");
    public static final ResourceKey<ModelType> LEGACY_TYRANNOSAURUS = FAModelTypes.create("legacy_tyrannosaurus");
    public static final ResourceKey<ModelType> LEGACY_VELOCIRAPTOR = FAModelTypes.create("legacy_green_velociraptor");
    public static final ResourceKey<ModelType> LEGACY_SANDY_VELOCIRAPTOR = FAModelTypes.create("legacy_sandy_velociraptor");
    public static final ResourceKey<ModelType> LEGACY_WHITE_VELOCIRAPTOR = FAModelTypes.create("legacy_white_velociraptor");

    private static ResourceKey<ModelType> create(String name) {
        return ResourceKey.create(FARegistries.MODEL_TYPES, FAUtils.resource(name));
    }

    private static void register(BootstrapContext<ModelType> bootstrapContext, ResourceKey<ModelType> resourceKey, ModelType modelType) {
        bootstrapContext.register(resourceKey, modelType);
    }

    public static void bootstrap(BootstrapContext<ModelType> bootstrapContext) {
        HolderGetter<PatternType> holderGetter = bootstrapContext.lookup(FARegistries.PATTERN_TYPES);
        Holder<PatternType> basic = holderGetter.getOrThrow(FAPatternTypes.BASIC);
        FAModelTypes.register(bootstrapContext, ANKYLOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.ankylosaurus"), 0x533A1B, 0.3F, 0.0F, FAUtils.resource("ankylosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/ankylosaurus/ankylosaurus_adult.png"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake")).withBabyTexture(FAUtils.resource("textures/entity/ankylosaurus/ankylosaurus_baby.png")), 1.75F, 1.5F, 0.2F, 1.5F, 1.5F, 0.3F, 1.0F, 0.25F).build());
        FAModelTypes.register(bootstrapContext, BRACHIOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.brachiosaurus"), 0x3C3F56, 0.07F, 8.0F, FAUtils.resource("brachiosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/brachiosaurus/brachiosaurus_adult.png"), Component.translatable("pattern.fossilslegacy.blue_iguana")).withBabyTexture(FAUtils.resource("textures/entity/brachiosaurus/brachiosaurus_baby.png")), 1.75F, 2.5F, 0.3F, 1.5F, 1.5F, 0.4F, 1.0F, 0.15F).build());
        FAModelTypes.register(bootstrapContext, CARNOTAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.green_carnotaurus"), 0x485039, 0.35F, 1.0F, FAUtils.resource("carnotaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/carnotaurus/green_carnotaurus_adult.png"), Component.translatable("pattern.fossilslegacy.green_tree_python")).withBabyTexture(FAUtils.resource("textures/entity/carnotaurus/red_carnotaurus_baby.png")), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.4F, 0.75F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, RED_CARNOTAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.red_carnotaurus"), 0xBF5242, 0.35F, 1.0F, FAUtils.resource("carnotaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/carnotaurus/red_carnotaurus_adult.png"), Component.translatable("pattern.fossilslegacy.northern_cardinal")).withBabyTexture(FAUtils.resource("textures/entity/carnotaurus/green_carnotaurus_baby.png")), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.4F, 0.75F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, COMPSOGNATHUS, ModelType.build(Component.translatable("model_type.fossilslegacy.compsognathus"), 0x213D20, 2.0F, -1.0F, FAUtils.resource("compsognathus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/compsognathus/compsognathus.png"), Component.translatable("pattern.fossilslegacy.green_tree_python")), 0.25F, 0.25F, 0.1F, 0.25F, 0.25F, 0.125F, 0.25F, 0.025F).build());
        FAModelTypes.register(bootstrapContext, CRYOLOPHOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.cryolophosaurus"), 0x49658B, 0.75F, -0.2F, FAUtils.resource("cryolophosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/cryolophosaurus/cryolophosaurus_adult.png"), Component.translatable("pattern.fossilslegacy.blue_iguana")).withBabyTexture(FAUtils.resource("textures/entity/cryolophosaurus/cryolophosaurus_baby.png")), 0.35F, 0.35F, 0.2F, 0.25F, 0.25F, 0.2F, 0.15F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, DILOPHOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.dilophosaurus"), 0x736F4A, 1.0F, 0.25F, FAUtils.resource("dilophosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/dilophosaurus/dilophosaurus_adult.png"), Component.translatable("pattern.fossilslegacy.inland_taipan")).withAggressiveTexture(FAUtils.resource("textures/entity/dilophosaurus/aggressive_dilophosaurus_adult.png")), 0.5F, 0.5F, 0.2F, 0.2F, 0.2F, 0.15F, 0.15F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, DIMETRODON, ModelType.build(Component.translatable("model_type.fossilslegacy.dimetrodon"), 0x251A22, 1.0F, 0.0F, FAUtils.resource("dimetrodon"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/dimetrodon/dimetrodon_adult.png"), Component.translatable("pattern.fossilslegacy.eastern_indigo_snake")).withBabyTexture(FAUtils.resource("textures/entity/dimetrodon/dimetrodon_baby.png")).withAggressiveTexture(FAUtils.resource("textures/entity/dimetrodon/dimetrodon_agressive.png")), 0.5F, 0.5F, 0.05F, 0.5F, 0.5F, 0.075F, 0.15F, 0.05F).build());
        FAModelTypes.register(bootstrapContext, DODO, ModelType.build(Component.translatable("model_type.fossilslegacy.dodo"), 0x5A5A5A, 2.0F, -1.0F, FAUtils.resource("dodo"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/dodo/dodo.png"), Component.translatable("pattern.fossilslegacy.domestic_pigeon")), 0.5F, 0.5F, 0.05F, 0.5F, 0.5F, 0.07142857142F, 0.15F, 0.05F).build());
        FAModelTypes.register(bootstrapContext, FUTABASAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.futabasaurus"), 0xB92200, 0.35F, 0.25F, FAUtils.resource("futabasaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/futabasaurus/futabasaurus.png"), Component.translatable("pattern.fossilslegacy.broadhead_skink")), 2.0F, 0.75F, 0.25F, 1.5F, 1.5F, 0.3F, 1.0F, 0.15F).build());
        FAModelTypes.register(bootstrapContext, GALLIMIMUS, ModelType.build(Component.translatable("model_type.fossilslegacy.gallimimus"), 0x774913, 0.4F, 1.5F, FAUtils.resource("gallimimus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/gallimimus/gallimimus_adult.png"), Component.translatable("pattern.fossilslegacy.broadhead_skink")).withBabyTexture(FAUtils.resource("textures/entity/gallimimus/gallimimus_baby.png")), 0.7F, 0.7F, 0.25F, 0.75F, 0.75F, 0.2F, 1.0F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, ICHTHYOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.ichthyosaurus"), 0x383C4F, 0.4F, 1.0F, FAUtils.resource("ichthyosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/ichthyosaurus/ichthyosaurus.png"), Component.translatable("pattern.fossilslegacy.blue_iguana")), 0.7F, 0.5F, 0.25F, 0.75F, 0.75F, 0.1F, 0.5F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, MAMMOTH, ModelType.build(Component.translatable("model_type.fossilslegacy.mammoth"), 0x3D2700, 0.4F, 1.0F, FAUtils.resource("mammoth"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/mammoth/mammoth_adult.png"), Component.translatable("pattern.fossilslegacy.american_bison")).withBabyTexture(FAUtils.resource("textures/entity/mammoth/mammoth_baby.png")).withFurTexture(FAUtils.resource("textures/entity/mammoth/mammoth_adult_fur.png")).withBabyFurTexture(FAUtils.resource("textures/entity/mammoth/mammoth_baby_fur.png")).withShearedTexture(FAUtils.resource("textures/entity/mammoth/mammoth_adult_sheared.png")), 0.7F, 0.7F, 0.5F, 1.0F, 1.0F, 0.4F, 0.75F, 0.15F).build());
        FAModelTypes.register(bootstrapContext, MOSASAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.mosasaurus"), 0x0D7346, 0.3F, 0.25F, FAUtils.resource("mosasaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/mosasaurus/mosasaurus.png"), Component.translatable("pattern.fossilslegacy.marine_iguana")).withEyeLayerTexture(FAUtils.resource("textures/entity/mosasaurus/mosasaurus_eyes.png")), 0.5F, 0.5F, 0.1F, 0.5F, 0.5F, 0.5125F, 0.5F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, MOA, ModelType.build(Component.translatable("model_type.fossilslegacy.moa"), 0x352A17, 0.45F, 1.0F, FAUtils.resource("moa"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/moa/moa.png"), Component.translatable("pattern.fossilslegacy.american_bison")), 0.5F, 1.5F, 0.1F, 0.5F, 0.5F, 0.25F, 0.15F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, PACHYCEPHALOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.pachycephalosaurus"), 0xC06929, 0.7F, 0.0F, FAUtils.resource("pachycephalosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/pachycephalosaurus/pachycephalosaurus_adult.png"), Component.translatable("pattern.fossilslegacy.broadhead_skink")).withBabyTexture(FAUtils.resource("textures/entity/pachycephalosaurus/pachycephalosaurus_baby.png")), 0.7F, 0.7F, 0.1F, 1.0F, 1.0F, 0.1F, 0.5F, 0.075F).build());
        FAModelTypes.register(bootstrapContext, PTERANODON, ModelType.build(Component.translatable("model_type.fossilslegacy.pteranodon"), 0x7C5D89, 0.75F, 0.0F, FAUtils.resource("pteranodon"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/pteranodon/pteranodon_adult.png"), Component.translatable("pattern.fossilslegacy.eastern_indigo_snake")).withBabyTexture(FAUtils.resource("textures/entity/pteranodon/pteranodon_baby.png")), 0.5F, 0.5F, 0.2F, 0.8F, 0.8F, 0.2F, 0.5F, 0.075F).build());
        FAModelTypes.register(bootstrapContext, SMILODON, ModelType.build(Component.translatable("model_type.fossilslegacy.smilodon"), 0xEFA745, 1.0F, -0.5F, FAUtils.resource("smilodon"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/smilodon/smilodon_adult.png"), Component.translatable("pattern.fossilslegacy.tiger")).withBabyTexture(FAUtils.resource("textures/entity/smilodon/smilodon_baby.png")), 0.75F, 0.75F, 0.1F, 0.7F, 0.7F, 0.1F, 0.5F, 0.05F).build());
        FAModelTypes.register(bootstrapContext, SPINOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.spinosaurus"), 0x26261D, 0.25F, 3.0F, FAUtils.resource("spinosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/spinosaurus/spinosaurus_adult.png"), Component.translatable("pattern.fossilslegacy.marine_iguana")).withBabyTexture(FAUtils.resource("textures/entity/spinosaurus/spinosaurus_baby.png")), 0.5F, 0.5F, 0.4F, 0.5F, 0.5F, 0.5125F, 0.5F, 0.15F).build());
        FAModelTypes.register(bootstrapContext, STEGOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.stegosaurus"), 0x8BE400, 0.3F, 1.0F, FAUtils.resource("stegosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/stegosaurus/stegosaurus_adult.png"), Component.translatable("pattern.fossilslegacy.green_tree_python")).withBabyTexture(FAUtils.resource("textures/entity/stegosaurus/stegosaurus_baby.png")), 0.75F, 0.75F, 0.2F, 0.8F, 0.8F, 0.2F, 1.0F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, THERIZINOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.therizinosaurus"), 0xCE551D, 0.25F, 0.25F, FAUtils.resource("therizinosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/therizinosaurus/therizinosaurus_adult.png"), Component.translatable("pattern.fossilslegacy.green_parakeet")).withBabyTexture(FAUtils.resource("textures/entity/therizinosaurus/therizinosaurus_baby.png")), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.25F, 0.75F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, TRICERATOPS, ModelType.build(Component.translatable("model_type.fossilslegacy.green_triceratops"), 0xADE642, 0.4F, 0.0F, FAUtils.resource("triceratops"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/triceratops/green_triceratops_adult.png"), Component.translatable("pattern.fossilslegacy.green_tree_python")).withBabyTexture(FAUtils.resource("textures/entity/triceratops/green_triceratops_baby.png")), 1.0F, 1.0F, 0.2F, 1.0F, 1.0F, 0.15F, 1.0F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, BROWN_TRICERATOPS, ModelType.build(Component.translatable("model_type.fossilslegacy.brown_triceratops"), 0xA58856, 0.4F, 0.0F, FAUtils.resource("triceratops"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/triceratops/brown_triceratops_adult.png"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake")).withBabyTexture(FAUtils.resource("textures/entity/triceratops/brown_triceratops_baby.png")), 1.0F, 1.0F, 0.2F, 1.0F, 1.0F, 0.15F, 1.0F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, TYRANNOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.tyrannosaurus"), 0x918066, 0.25F, 0.25F, FAUtils.resource("tyrannosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/tyrannosaurus/tyrannosaurus_adult.png"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake")).withAggressiveTexture(FAUtils.resource("textures/entity/tyrannosaurus/tyrannosaurus_aggressive.png")).withKnockedOutTexture(FAUtils.resource("textures/entity/tyrannosaurus/tyrannosaurus_weak.png")).withBabyTexture(FAUtils.resource("textures/entity/tyrannosaurus/tyrannosaurus_baby.png")), 0.5F, 0.5F, 0.6F, 0.5F, 0.5F, 0.5125F, 0.75F, 0.15F).withKnockoutModel(FAUtils.resource("knocked_out_tyrannosaurus")).build());
        FAModelTypes.register(bootstrapContext, VELOCIRAPTOR, ModelType.build(Component.translatable("model_type.fossilslegacy.green_velociraptor"), 0x0C3F4C, 1.5F, -0.75F, FAUtils.resource("velociraptor"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/green_velociraptor_adult.png"), Component.translatable("pattern.fossilslegacy.green_tree_python")).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/green_velociraptor_baby.png")), 0.2F, 0.4F, 0.05F, 0.5F, 0.5F, 0.1F, 0.5F, 0.025F).build());
        FAModelTypes.register(bootstrapContext, SANDY_VELOCIRAPTOR, ModelType.build(Component.translatable("model_type.fossilslegacy.sandy_velociraptor"), 0x632D09, 1.5F, -0.75F, FAUtils.resource("velociraptor"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/sandy_velociraptor_adult.png"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake")).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/sandy_velociraptor_baby.png")), 0.2F, 0.4F, 0.05F, 0.5F, 0.5F, 0.1F, 0.5F, 0.025F).build());
        FAModelTypes.register(bootstrapContext, WHITE_VELOCIRAPTOR, ModelType.build(Component.translatable("model_type.fossilslegacy.white_velociraptor"), 0x252525, 1.5F, -0.75F, FAUtils.resource("velociraptor"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/white_velociraptor_adult.png"), Component.translatable("pattern.fossilslegacy.gray_ratsnake")).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/white_velociraptor_baby.png")), 0.2F, 0.4F, 0.05F, 0.5F, 0.5F, 0.1F, 0.5F, 0.025F).build());

        FAModelTypes.register(bootstrapContext, LEGACY_BRACHIOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_brachiosaurus"), 0x363950, 0.07F, 8.0F, FAUtils.resource("legacy_brachiosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/brachiosaurus/legacy/brachiosaurus.png"), Component.translatable("pattern.fossilslegacy.blue_iguana")), 1.75F, 2.5F, 0.3F, 1.5F, 1.5F, 0.3F, 0.15F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_CARNOTAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_green_carnotaurus"), 0x485039, 0.35F, 1.0F, FAUtils.resource("legacy_carnotaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/carnotaurus/legacy/green_carnotaurus.png"), Component.translatable("pattern.fossilslegacy.green_tree_python")), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.3F, 0.75F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_RED_CARNOTAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_red_carnotaurus"), 0xBF5242, 0.35F, 1.0F, FAUtils.resource("legacy_carnotaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/carnotaurus/legacy/red_carnotaurus.png"), Component.translatable("pattern.fossilslegacy.northern_cardinal")), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.3F, 0.75F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_CRYOLOPHOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_cryolophosaurus"), 0x49658B, 0.75F, -0.2F, FAUtils.resource("legacy_cryolophosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/cryolophosaurus/legacy/cryolophosaurus.png"), Component.translatable("pattern.fossilslegacy.blue_iguana")), 0.35F, 0.35F, 0.2F, 0.25F, 0.25F, 0.2F, 0.15F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_DILOPHOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_dilophosaurus"), 0x736F4A, 1.0F, 0.25F, FAUtils.resource("legacy_dilophosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/dilophosaurus/legacy/dilophosaurus.png"), Component.translatable("pattern.fossilslegacy.inland_taipan")).withAggressiveTexture(FAUtils.resource("textures/entity/dilophosaurus/legacy/dilophosaurus_aggressive.png")), 0.5F, 0.5F, 0.2F, 0.2F, 0.2F, 0.15F, 0.15F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_FUTABASAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_futabasaurus"), 0xC75B00, 0.3F, 0.25F, FAUtils.resource("legacy_futabasaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/futabasaurus/legacy/futabasaurus.png"), Component.translatable("pattern.fossilslegacy.broadhead_skink")), 0.75F, 0.75F, 0.2F, 1.5F, 1.5F, 0.3F, 0.15F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_MAMMOTH, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_mammoth"), 0x3D2700, 0.4F, 0.0F, FAUtils.resource("legacy_mammoth"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/mammoth/legacy/mammoth_adult.png"), Component.translatable("pattern.fossilslegacy.american_bison")).withBabyTexture(FAUtils.resource("textures/entity/mammoth/legacy/mammoth_baby.png")).withFurTexture(FAUtils.resource("textures/entity/mammoth/legacy/mammoth_adult_fur.png")).withBabyFurTexture(FAUtils.resource("textures/entity/mammoth/legacy/mammoth_baby_fur.png")).withShearedTexture(FAUtils.resource("textures/entity/mammoth/legacy/mammoth_adult_sheared.png")), 0.7F, 0.7F, 0.5F, 1.0F, 1.0F, 0.625F, 0.75F, 0.15F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_MOSASAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_mosasaurus"), 0x0D7346, 0.4F, 0.25F, FAUtils.resource("legacy_mosasaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/mosasaurus/legacy/mosasaurus.png"), Component.translatable("pattern.fossilslegacy.marine_iguana")).withEyeLayerTexture(FAUtils.resource("textures/entity/mosasaurus/legacy/mosasaurus_eyes.png")), 0.5F, 0.5F, 0.2F, 0.5F, 0.5F, 0.5125F, 0.5F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_PTERANODON, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_pteranodon"), 0x7C5D89, 0.75F, 0.0F, FAUtils.resource("legacy_pteranodon"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/pteranodon/legacy/pteranodon.png"), Component.translatable("pattern.fossilslegacy.eastern_indigo_snake")), 0.5F, 0.5F, 0.2F, 0.8F, 0.8F, 0.2F, 0.5F, 0.075F).withFlyingModels(FAUtils.resource("legacy_flying_pteranodon"), FAUtils.resource("legacy_landing_pteranodon")).build());
        FAModelTypes.register(bootstrapContext, LEGACY_SMILODON, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_smilodon"), 0xEFA745, 1.0F, -0.5F, FAUtils.resource("legacy_smilodon"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/smilodon/legacy/smilodon_adult.png"), Component.translatable("pattern.fossilslegacy.tiger")).withBabyTexture(FAUtils.resource("textures/entity/smilodon/legacy/smilodon_baby.png")), 0.75F, 0.75F, 0.1F, 1.0F, 1.0F, 0.14285714285F, 0.5F, 0.05F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_STEGOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_stegosaurus"), 0x8BE400, 0.3F, 0.0F, FAUtils.resource("legacy_stegosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/stegosaurus/legacy/stegosaurus_adult.png"), Component.translatable("pattern.fossilslegacy.green_tree_python")).withBabyTexture(FAUtils.resource("textures/entity/stegosaurus/legacy/stegosaurus_baby.png")), 0.75F, 0.75F, 0.2F, 1.5F, 1.5F, 0.3F, 1.0F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_THERIZINOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_feathered_therizinosaurus"), 0xCE551D, 0.25F, 0.25F, FAUtils.resource("legacy_therizinosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/therizinosaurus/legacy/therizinosaurus_feathered.png"), Component.translatable("pattern.fossilslegacy.green_parakeet")), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.35F, 0.75F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_FEATHERLESS_THERIZINOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_featherless_therizinosaurus"), 0x606F3F, 0.25F, 0.25F, FAUtils.resource("legacy_therizinosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/therizinosaurus/legacy/therizinosaurus_featherless.png"), Component.translatable("pattern.fossilslegacy.green_tree_python")), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.35F, 0.75F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_TRICERATOPS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_green_triceratops"), 0xB6EF4B, 0.4F, 0.0F, FAUtils.resource("legacy_triceratops"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/triceratops/legacy/green_triceratops_adult.png"), Component.translatable("pattern.fossilslegacy.green_tree_python")).withBabyTexture(FAUtils.resource("textures/entity/triceratops/legacy/green_triceratops_baby.png")), 0.75F, 0.75F, 0.15F, 1.5F, 1.5F, 0.3F, 1.0F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_BROWN_TRICERATOPS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_brown_triceratops"), 0xE3BB7B, 0.4F, 0.0F, FAUtils.resource("legacy_triceratops"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/triceratops/legacy/brown_triceratops_adult.png"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake")).withBabyTexture(FAUtils.resource("textures/entity/triceratops/legacy/brown_triceratops_baby.png")), 0.75F, 0.75F, 0.15F, 1.5F, 1.5F, 0.3F, 1.0F, 0.1F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_TYRANNOSAURUS, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_tyrannosaurus"), 0x918066, 0.25F, 0.25F, FAUtils.resource("legacy_tyrannosaurus"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/tyrannosaurus/legacy/tyrannosaurus.png"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake")).withAggressiveTexture(FAUtils.resource("textures/entity/tyrannosaurus/legacy/tyrannosaurus_aggressive.png")).withKnockedOutTexture(FAUtils.resource("textures/entity/tyrannosaurus/legacy/tyrannosaurus_weak.png")), 0.5F, 0.5F, 0.6F, 0.5F, 0.5F, 0.5125F, 0.75F, 0.15F).withKnockoutModel(FAUtils.resource("legacy_knocked_out_tyrannosaurus")).build());
        FAModelTypes.register(bootstrapContext, LEGACY_VELOCIRAPTOR, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_green_velociraptor"), 0x71A367, 1.0F, -0.75F, FAUtils.resource("legacy_velociraptor"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/legacy/green_velociraptor_adult.png"), Component.translatable("pattern.fossilslegacy.green_tree_python")).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/legacy/green_velociraptor_baby.png")), 0.3F, 0.3F, 0.1F, 0.2F, 0.32F, 0.1F, 0.35F, 0.05F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_SANDY_VELOCIRAPTOR, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_sandy_velociraptor"), 0xD6C68E, 1.0F, -0.75F, FAUtils.resource("legacy_velociraptor"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/legacy/sandy_velociraptor_adult.png"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake")).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/legacy/sandy_velociraptor_baby.png")), 0.3F, 0.3F, 0.1F, 0.2F, 0.32F, 0.1F, 0.35F, 0.05F).build());
        FAModelTypes.register(bootstrapContext, LEGACY_WHITE_VELOCIRAPTOR, ModelType.build(Component.translatable("model_type.fossilslegacy.legacy_white_velociraptor"), 0xC0C5D5, 1.0F, -0.75F, FAUtils.resource("legacy_velociraptor"), basic, ModelType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/legacy/white_velociraptor_adult.png"), Component.translatable("pattern.fossilslegacy.gray_ratsnake")).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/legacy/white_velociraptor_baby.png")), 0.3F, 0.3F, 0.1F, 0.2F, 0.32F, 0.1F, 0.35F, 0.05F).build());
    }
}
