package willatendo.fossilslegacy.server.item.feederfood;

import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import willatendo.fossilslegacy.server.core.registry.FossilsLegacyRegistries;
import willatendo.fossilslegacy.server.item.FossilsLegacyItems;
import willatendo.fossilslegacy.server.utils.FossilsLegacyUtils;

public class FossilsLegacyFeederFoods {
    public static final ResourceKey<FeederFood> BEEF = FossilsLegacyFeederFoods.create("beef");
    public static final ResourceKey<FeederFood> COOKED_BEEF = FossilsLegacyFeederFoods.create("cooked_beef");
    public static final ResourceKey<FeederFood> CHICKEN = FossilsLegacyFeederFoods.create("chicken");
    public static final ResourceKey<FeederFood> COOKED_CHICKEN = FossilsLegacyFeederFoods.create("cooked_chicken");
    public static final ResourceKey<FeederFood> MUTTON = FossilsLegacyFeederFoods.create("mutton");
    public static final ResourceKey<FeederFood> COOKED_MUTTON = FossilsLegacyFeederFoods.create("cooked_mutton");
    public static final ResourceKey<FeederFood> RABBIT = FossilsLegacyFeederFoods.create("rabbit");
    public static final ResourceKey<FeederFood> COOKED_RABBIT = FossilsLegacyFeederFoods.create("cooked_rabbit");
    public static final ResourceKey<FeederFood> PORKCHOP = FossilsLegacyFeederFoods.create("porkchop");
    public static final ResourceKey<FeederFood> COOKED_PORKCHOP = FossilsLegacyFeederFoods.create("cooked_porkchop");
    public static final ResourceKey<FeederFood> COD = FossilsLegacyFeederFoods.create("cod");
    public static final ResourceKey<FeederFood> COOKED_COD = FossilsLegacyFeederFoods.create("cooked_cod");
    public static final ResourceKey<FeederFood> SALMON = FossilsLegacyFeederFoods.create("salmon");
    public static final ResourceKey<FeederFood> COOKED_SALMON = FossilsLegacyFeederFoods.create("cooked_salmon");
    public static final ResourceKey<FeederFood> TROPICAL_FISH = FossilsLegacyFeederFoods.create("tropical_fish");
    public static final ResourceKey<FeederFood> RAW_TRICERATOPS = FossilsLegacyFeederFoods.create("raw_triceratops");
    public static final ResourceKey<FeederFood> RAW_VELOCIRAPTOR = FossilsLegacyFeederFoods.create("raw_velociraptor");
    public static final ResourceKey<FeederFood> RAW_TYRANNOSAURUS = FossilsLegacyFeederFoods.create("raw_tyrannosaurus");
    public static final ResourceKey<FeederFood> RAW_PTERANODON = FossilsLegacyFeederFoods.create("raw_pteranodon");
    public static final ResourceKey<FeederFood> RAW_FUTABASAURUS = FossilsLegacyFeederFoods.create("raw_futabasaurus");
    public static final ResourceKey<FeederFood> RAW_MOSASAURUS = FossilsLegacyFeederFoods.create("raw_mosasaurus");
    public static final ResourceKey<FeederFood> RAW_STEGOSAURUS = FossilsLegacyFeederFoods.create("raw_stegosaurus");
    public static final ResourceKey<FeederFood> RAW_DILOPHOSAURUS = FossilsLegacyFeederFoods.create("raw_dilophosaurus");
    public static final ResourceKey<FeederFood> RAW_BRACHIOSAURUS = FossilsLegacyFeederFoods.create("raw_brachiosaurus");
    public static final ResourceKey<FeederFood> RAW_SMILODON = FossilsLegacyFeederFoods.create("raw_smilodon");
    public static final ResourceKey<FeederFood> RAW_MAMMOTH = FossilsLegacyFeederFoods.create("raw_mammoth");
    public static final ResourceKey<FeederFood> RAW_CARNOTAURUS = FossilsLegacyFeederFoods.create("raw_carnotaurus");
    public static final ResourceKey<FeederFood> RAW_CRYOLOPHOSAURUS = FossilsLegacyFeederFoods.create("raw_cryolophosaurus");
    public static final ResourceKey<FeederFood> RAW_THERIZINOSAURUS = FossilsLegacyFeederFoods.create("raw_therizinosaurus");
    public static final ResourceKey<FeederFood> RAW_PACHYCEPHALOSAURUS = FossilsLegacyFeederFoods.create("raw_pachycephalosaurus");
    public static final ResourceKey<FeederFood> RAW_COMPSOGNATHUS = FossilsLegacyFeederFoods.create("raw_compsognathus");
    public static final ResourceKey<FeederFood> RAW_DODO = FossilsLegacyFeederFoods.create("raw_dodo");
    public static final ResourceKey<FeederFood> RAW_MOA = FossilsLegacyFeederFoods.create("raw_moa");
    public static final ResourceKey<FeederFood> RAW_GALLIMIMUS = FossilsLegacyFeederFoods.create("raw_gallimimus");
    public static final ResourceKey<FeederFood> RAW_SPINOSAURUS = FossilsLegacyFeederFoods.create("raw_spinosaurus");
    public static final ResourceKey<FeederFood> RAW_ANKYLOSAURUS = FossilsLegacyFeederFoods.create("raw_ankylosaurus");
    public static final ResourceKey<FeederFood> COOKED_TRICERATOPS = FossilsLegacyFeederFoods.create("cooked_triceratops");
    public static final ResourceKey<FeederFood> COOKED_VELOCIRAPTOR = FossilsLegacyFeederFoods.create("cooked_velociraptor");
    public static final ResourceKey<FeederFood> COOKED_TYRANNOSAURUS = FossilsLegacyFeederFoods.create("cooked_tyrannosaurus");
    public static final ResourceKey<FeederFood> COOKED_PTERANODON = FossilsLegacyFeederFoods.create("cooked_pteranodon");
    public static final ResourceKey<FeederFood> SIO_CHIU_LE = FossilsLegacyFeederFoods.create("sio_chiu_le");
    public static final ResourceKey<FeederFood> COOKED_FUTABASAURUS = FossilsLegacyFeederFoods.create("cooked_futabasaurus");
    public static final ResourceKey<FeederFood> COOKED_MOSASAURUS = FossilsLegacyFeederFoods.create("cooked_mosasaurus");
    public static final ResourceKey<FeederFood> COOKED_STEGOSAURUS = FossilsLegacyFeederFoods.create("cooked_stegosaurus");
    public static final ResourceKey<FeederFood> COOKED_DILOPHOSAURUS = FossilsLegacyFeederFoods.create("cooked_dilophosaurus");
    public static final ResourceKey<FeederFood> COOKED_BRACHIOSAURUS = FossilsLegacyFeederFoods.create("cooked_brachiosaurus");
    public static final ResourceKey<FeederFood> COOKED_SMILODON = FossilsLegacyFeederFoods.create("cooked_smilodon");
    public static final ResourceKey<FeederFood> COOKED_MAMMOTH = FossilsLegacyFeederFoods.create("cooked_mammoth");
    public static final ResourceKey<FeederFood> COOKED_CARNOTAURUS = FossilsLegacyFeederFoods.create("cooked_carnotaurus");
    public static final ResourceKey<FeederFood> COOKED_CRYOLOPHOSAURUS = FossilsLegacyFeederFoods.create("cooked_cryolophosaurus");
    public static final ResourceKey<FeederFood> COOKED_THERIZINOSAURUS = FossilsLegacyFeederFoods.create("cooked_therizinosaurus");
    public static final ResourceKey<FeederFood> COOKED_PACHYCEPHALOSAURUS = FossilsLegacyFeederFoods.create("cooked_pachycephalosaurus");
    public static final ResourceKey<FeederFood> COOKED_COMPSOGNATHUS = FossilsLegacyFeederFoods.create("cooked_compsognathus");
    public static final ResourceKey<FeederFood> COOKED_DODO = FossilsLegacyFeederFoods.create("cooked_dodo");
    public static final ResourceKey<FeederFood> COOKED_MOA = FossilsLegacyFeederFoods.create("cooked_moa");
    public static final ResourceKey<FeederFood> COOKED_GALLIMIMUS = FossilsLegacyFeederFoods.create("cooked_gallimimus");
    public static final ResourceKey<FeederFood> COOKED_SPINOSAURUS = FossilsLegacyFeederFoods.create("cooked_spinosaurus");
    public static final ResourceKey<FeederFood> COOKED_ANKYLOSAURUS = FossilsLegacyFeederFoods.create("cooked_ankylosaurus");
    public static final ResourceKey<FeederFood> APPLE = FossilsLegacyFeederFoods.create("apple");
    public static final ResourceKey<FeederFood> WHEAT = FossilsLegacyFeederFoods.create("wheat");
    public static final ResourceKey<FeederFood> BREAD = FossilsLegacyFeederFoods.create("bread");
    public static final ResourceKey<FeederFood> SUGAR_CANE = FossilsLegacyFeederFoods.create("sugar_cane");
    public static final ResourceKey<FeederFood> WHEAT_SEEDS = FossilsLegacyFeederFoods.create("wheat_seeds");
    public static final ResourceKey<FeederFood> BEETROOT_SEEDS = FossilsLegacyFeederFoods.create("beetroot_seeds");
    public static final ResourceKey<FeederFood> MELON_SEEDS = FossilsLegacyFeederFoods.create("melon_seeds");
    public static final ResourceKey<FeederFood> PUMPKIN_SEEDS = FossilsLegacyFeederFoods.create("pumpkin_seeds");
    public static final ResourceKey<FeederFood> MELON_SLICE = FossilsLegacyFeederFoods.create("melon_slice");
    public static final ResourceKey<FeederFood> SWEET_BERRIES = FossilsLegacyFeederFoods.create("sweet_berries");
    public static final ResourceKey<FeederFood> GLOW_BERRIES = FossilsLegacyFeederFoods.create("glow_berries");
    public static final ResourceKey<FeederFood> CARROT = FossilsLegacyFeederFoods.create("carrot");
    public static final ResourceKey<FeederFood> POTATO = FossilsLegacyFeederFoods.create("potato");
    public static final ResourceKey<FeederFood> BAKED_POTATO = FossilsLegacyFeederFoods.create("baked_potato");
    public static final ResourceKey<FeederFood> BEETROOT = FossilsLegacyFeederFoods.create("beetroot");
    public static final ResourceKey<FeederFood> KELP = FossilsLegacyFeederFoods.create("kelp");
    public static final ResourceKey<FeederFood> JURASSIC_FERN_SPORES = FossilsLegacyFeederFoods.create("jurassic_fern_spores");

    public static ResourceKey<FeederFood> create(String name) {
        return ResourceKey.create(FossilsLegacyRegistries.FEEDER_FOOD, FossilsLegacyUtils.resource(name));
    }

    private static void register(BootstrapContext<FeederFood> bootstrapContext, ResourceKey<FeederFood> resourceKey, ItemStack itemStack, int amount, FillType fillType) {
        bootstrapContext.register(resourceKey, new FeederFood(resourceKey.location(), itemStack, amount, fillType));
    }

    public static void bootstrap(BootstrapContext<FeederFood> bootstrapContext) {
        register(bootstrapContext, BEEF, new ItemStack(Items.BEEF), 40, FillType.MEAT);
        register(bootstrapContext, COOKED_BEEF, new ItemStack(Items.COOKED_BEEF), 20, FillType.MEAT);
        register(bootstrapContext, CHICKEN, new ItemStack(Items.CHICKEN), 30, FillType.MEAT);
        register(bootstrapContext, COOKED_CHICKEN, new ItemStack(Items.COOKED_CHICKEN), 10, FillType.MEAT);
        register(bootstrapContext, MUTTON, new ItemStack(Items.MUTTON), 30, FillType.MEAT);
        register(bootstrapContext, COOKED_MUTTON, new ItemStack(Items.COOKED_MUTTON), 10, FillType.MEAT);
        register(bootstrapContext, RABBIT, new ItemStack(Items.RABBIT), 30, FillType.MEAT);
        register(bootstrapContext, COOKED_RABBIT, new ItemStack(Items.COOKED_RABBIT), 10, FillType.MEAT);
        register(bootstrapContext, PORKCHOP, new ItemStack(Items.PORKCHOP), 20, FillType.MEAT);
        register(bootstrapContext, COOKED_PORKCHOP, new ItemStack(Items.COOKED_PORKCHOP), 30, FillType.MEAT);
        register(bootstrapContext, COD, new ItemStack(Items.COD), 40, FillType.MEAT);
        register(bootstrapContext, COOKED_COD, new ItemStack(Items.COOKED_COD), 60, FillType.MEAT);
        register(bootstrapContext, SALMON, new ItemStack(Items.SALMON), 40, FillType.MEAT);
        register(bootstrapContext, COOKED_SALMON, new ItemStack(Items.COOKED_SALMON), 60, FillType.MEAT);
        register(bootstrapContext, TROPICAL_FISH, new ItemStack(Items.TROPICAL_FISH), 40, FillType.MEAT);
        register(bootstrapContext, RAW_TRICERATOPS, new ItemStack(FossilsLegacyItems.RAW_TRICERATOPS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_VELOCIRAPTOR, new ItemStack(FossilsLegacyItems.RAW_VELOCIRAPTOR.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_TYRANNOSAURUS, new ItemStack(FossilsLegacyItems.RAW_TYRANNOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_PTERANODON, new ItemStack(FossilsLegacyItems.RAW_PTERANODON.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_FUTABASAURUS, new ItemStack(FossilsLegacyItems.RAW_FUTABASAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_MOSASAURUS, new ItemStack(FossilsLegacyItems.RAW_MOSASAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_STEGOSAURUS, new ItemStack(FossilsLegacyItems.RAW_STEGOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_DILOPHOSAURUS, new ItemStack(FossilsLegacyItems.RAW_DILOPHOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_BRACHIOSAURUS, new ItemStack(FossilsLegacyItems.RAW_BRACHIOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_SMILODON, new ItemStack(FossilsLegacyItems.RAW_SMILODON.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_MAMMOTH, new ItemStack(FossilsLegacyItems.RAW_MAMMOTH.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_CARNOTAURUS, new ItemStack(FossilsLegacyItems.RAW_CARNOTAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_CRYOLOPHOSAURUS, new ItemStack(FossilsLegacyItems.RAW_CRYOLOPHOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_THERIZINOSAURUS, new ItemStack(FossilsLegacyItems.RAW_THERIZINOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_PACHYCEPHALOSAURUS, new ItemStack(FossilsLegacyItems.RAW_PACHYCEPHALOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_COMPSOGNATHUS, new ItemStack(FossilsLegacyItems.RAW_COMPSOGNATHUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_DODO, new ItemStack(FossilsLegacyItems.RAW_DODO.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_MOA, new ItemStack(FossilsLegacyItems.RAW_MOA.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_GALLIMIMUS, new ItemStack(FossilsLegacyItems.RAW_GALLIMIMUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_SPINOSAURUS, new ItemStack(FossilsLegacyItems.RAW_SPINOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, RAW_ANKYLOSAURUS, new ItemStack(FossilsLegacyItems.RAW_ANKYLOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_TRICERATOPS, new ItemStack(FossilsLegacyItems.COOKED_TRICERATOPS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_VELOCIRAPTOR, new ItemStack(FossilsLegacyItems.COOKED_VELOCIRAPTOR.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_TYRANNOSAURUS, new ItemStack(FossilsLegacyItems.COOKED_TYRANNOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_PTERANODON, new ItemStack(FossilsLegacyItems.COOKED_PTERANODON.get()), 100, FillType.MEAT);
        register(bootstrapContext, SIO_CHIU_LE, new ItemStack(FossilsLegacyItems.SIO_CHIU_LE.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_FUTABASAURUS, new ItemStack(FossilsLegacyItems.COOKED_FUTABASAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_MOSASAURUS, new ItemStack(FossilsLegacyItems.COOKED_MOSASAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_STEGOSAURUS, new ItemStack(FossilsLegacyItems.COOKED_STEGOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_DILOPHOSAURUS, new ItemStack(FossilsLegacyItems.COOKED_DILOPHOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_BRACHIOSAURUS, new ItemStack(FossilsLegacyItems.COOKED_BRACHIOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_SMILODON, new ItemStack(FossilsLegacyItems.COOKED_SMILODON.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_MAMMOTH, new ItemStack(FossilsLegacyItems.COOKED_MAMMOTH.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_CARNOTAURUS, new ItemStack(FossilsLegacyItems.COOKED_CARNOTAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_CRYOLOPHOSAURUS, new ItemStack(FossilsLegacyItems.COOKED_CRYOLOPHOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_THERIZINOSAURUS, new ItemStack(FossilsLegacyItems.COOKED_THERIZINOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_PACHYCEPHALOSAURUS, new ItemStack(FossilsLegacyItems.COOKED_PACHYCEPHALOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_COMPSOGNATHUS, new ItemStack(FossilsLegacyItems.COOKED_COMPSOGNATHUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_DODO, new ItemStack(FossilsLegacyItems.COOKED_DODO.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_MOA, new ItemStack(FossilsLegacyItems.COOKED_MOA.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_GALLIMIMUS, new ItemStack(FossilsLegacyItems.COOKED_GALLIMIMUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_SPINOSAURUS, new ItemStack(FossilsLegacyItems.COOKED_SPINOSAURUS.get()), 100, FillType.MEAT);
        register(bootstrapContext, COOKED_ANKYLOSAURUS, new ItemStack(FossilsLegacyItems.COOKED_ANKYLOSAURUS.get()), 100, FillType.MEAT);

        register(bootstrapContext, APPLE, new ItemStack(Items.APPLE), 100, FillType.PLANT);
        register(bootstrapContext, WHEAT, new ItemStack(Items.WHEAT), 40, FillType.PLANT);
        register(bootstrapContext, BREAD, new ItemStack(Items.BREAD), 120, FillType.PLANT);
        register(bootstrapContext, SUGAR_CANE, new ItemStack(Items.SUGAR_CANE), 20, FillType.PLANT);
        register(bootstrapContext, WHEAT_SEEDS, new ItemStack(Items.WHEAT_SEEDS), 20, FillType.PLANT);
        register(bootstrapContext, BEETROOT_SEEDS, new ItemStack(Items.BEETROOT_SEEDS), 20, FillType.PLANT);
        register(bootstrapContext, MELON_SEEDS, new ItemStack(Items.MELON_SEEDS), 20, FillType.PLANT);
        register(bootstrapContext, PUMPKIN_SEEDS, new ItemStack(Items.PUMPKIN_SEEDS), 20, FillType.PLANT);
        register(bootstrapContext, MELON_SLICE, new ItemStack(Items.MELON_SLICE), 25, FillType.PLANT);
        register(bootstrapContext, SWEET_BERRIES, new ItemStack(Items.SWEET_BERRIES), 15, FillType.PLANT);
        register(bootstrapContext, GLOW_BERRIES, new ItemStack(Items.GLOW_BERRIES), 15, FillType.PLANT);
        register(bootstrapContext, CARROT, new ItemStack(Items.CARROT), 100, FillType.PLANT);
        register(bootstrapContext, POTATO, new ItemStack(Items.POTATO), 100, FillType.PLANT);
        register(bootstrapContext, BAKED_POTATO, new ItemStack(Items.BAKED_POTATO), 75, FillType.PLANT);
        register(bootstrapContext, BEETROOT, new ItemStack(Items.BEETROOT), 25, FillType.PLANT);
        register(bootstrapContext, KELP, new ItemStack(Items.KELP), 15, FillType.PLANT);
        register(bootstrapContext, JURASSIC_FERN_SPORES, new ItemStack(FossilsLegacyItems.JURASSIC_FERN_SPORES.get()), 50, FillType.PLANT);
    }
}
