package fossilslegacy.server;

import fossilslegacy.server.block.FossilsLegacyBlocks;
import fossilslegacy.server.entity.StoneHieroglyphTypes;
import fossilslegacy.server.item.FossilsLegacyItems;
import fossilslegacy.server.utils.FossilsLegacyUtils;
import net.minecraft.core.registries.Registries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class FossilsLegacyCreativeModeTabs {
	public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, FossilsLegacyUtils.ID);

	public static final RegistryObject<CreativeModeTab> FOSSILS_LEGACY = CREATIVE_MODE_TABS.register("fossils_legacy", () -> CreativeModeTab.builder().title(FossilsLegacyUtils.translation("itemGroup", FossilsLegacyUtils.ID)).icon(() -> FossilsLegacyItems.FOSSIL.get().getDefaultInstance()).displayItems((itemDisplayParameters, output) -> {
		output.accept(FossilsLegacyItems.FOSSIL.get());
		output.accept(FossilsLegacyItems.TRICERATOPS_DNA.get());
		output.accept(FossilsLegacyItems.UTAHRAPTOR_DNA.get());
		output.accept(FossilsLegacyItems.TYRANNOSAURUS_DNA.get());
		output.accept(FossilsLegacyItems.PTEROSAURUS_DNA.get());
		output.accept(FossilsLegacyItems.NAUTILUS_DNA.get());
		output.accept(FossilsLegacyItems.PLESIOSAURUS_DNA.get());
		output.accept(FossilsLegacyItems.MOSASAURUS_DNA.get());
		output.accept(FossilsLegacyItems.STEGOSAURUS_DNA.get());
		output.accept(FossilsLegacyItems.DILOPHOSAURUS_DNA.get());
		output.accept(FossilsLegacyItems.BRACHIOSAURUS_DNA.get());
		output.accept(FossilsLegacyItems.TRICERATOPS_EGG.get());
		output.accept(FossilsLegacyItems.UTAHRAPTOR_EGG.get());
		output.accept(FossilsLegacyItems.TYRANNOSAURUS_EGG.get());
		output.accept(FossilsLegacyItems.PTEROSAURUS_EGG.get());
		output.accept(FossilsLegacyItems.NAUTILUS_EGGS.get());
		output.accept(FossilsLegacyItems.PLESIOSAURUS_EGG.get());
		output.accept(FossilsLegacyItems.MOSASAURUS_EGG.get());
		output.accept(FossilsLegacyItems.STEGOSAURUS_EGG.get());
		output.accept(FossilsLegacyItems.DILOPHOSAURUS_EGG.get());
		output.accept(FossilsLegacyItems.BRACHIOSAURUS_EGG.get());
		output.accept(FossilsLegacyItems.RAW_TRICERATOPS_MEAT.get());
		output.accept(FossilsLegacyItems.RAW_UTAHRAPTOR_MEAT.get());
		output.accept(FossilsLegacyItems.RAW_TYRANNOSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.RAW_PTEROSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.NAUTILUS.get());
		output.accept(FossilsLegacyItems.RAW_PLESIOSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.RAW_MOSASAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.RAW_STEGOSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.RAW_DILOPHOSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.RAW_BRACHIOSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.RAW_SMILODON_MEAT.get());
		output.accept(FossilsLegacyItems.RAW_MAMMOTH_MEAT.get());
		output.accept(FossilsLegacyItems.COOKED_TRICERATOPS_MEAT.get());
		output.accept(FossilsLegacyItems.COOKED_UTAHRAPTOR_MEAT.get());
		output.accept(FossilsLegacyItems.COOKED_TYRANNOSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.COOKED_PTEROSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.SIO_CHIU_LE.get());
		output.accept(FossilsLegacyItems.COOKED_PLESIOSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.COOKED_MOSASAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.COOKED_STEGOSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.COOKED_DILOPHOSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.COOKED_BRACHIOSAURUS_MEAT.get());
		output.accept(FossilsLegacyItems.COOKED_SMILODON_MEAT.get());
		output.accept(FossilsLegacyItems.COOKED_MAMMOTH_MEAT.get());
		output.accept(FossilsLegacyItems.TYRANNOSAURUS_TOOTH.get());
		output.accept(FossilsLegacyItems.TOOTH_DAGGER.get());
		output.accept(FossilsLegacyItems.SKULL_STICK.get());
		output.accept(FossilsLegacyItems.DINOSAUR_ENCYCLOPEDIA.get());
		output.accept(FossilsLegacyItems.RAW_CHICKEN_SOUP_BUCKET.get());
		output.accept(FossilsLegacyItems.COOKED_CHICKEN_SOUP_BUCKET.get());
		output.accept(FossilsLegacyItems.CHICKEN_ESSENCE_BOTTLE.get());
		output.accept(FossilsLegacyItems.NAUTILUS_SHELL.get());
		output.accept(FossilsLegacyItems.SIO_CHIU_LE.get());
		for (int i = 0; i < 3; i++) {
			ItemStack magicConch = new ItemStack(FossilsLegacyItems.MAGIC_CONCH.get());
			CompoundTag compoundTag = magicConch.getOrCreateTag();
			compoundTag.putInt("Order", i);
			output.accept(magicConch);
		}
		output.accept(FossilsLegacyItems.FROZEN_MEAT.get());
		output.accept(FossilsLegacyItems.AXOLOTL_DNA.get());
		output.accept(FossilsLegacyItems.CAT_DNA.get());
		output.accept(FossilsLegacyItems.CHICKEN_DNA.get());
		output.accept(FossilsLegacyItems.COW_DNA.get());
		output.accept(FossilsLegacyItems.DOLPHIN_DNA.get());
		output.accept(FossilsLegacyItems.DONKEY_DNA.get());
		output.accept(FossilsLegacyItems.FOX_DNA.get());
		output.accept(FossilsLegacyItems.FROG_DNA.get());
		output.accept(FossilsLegacyItems.GOAT_DNA.get());
		output.accept(FossilsLegacyItems.HORSE_DNA.get());
		output.accept(FossilsLegacyItems.LLAMA_DNA.get());
		output.accept(FossilsLegacyItems.MULE_DNA.get());
		output.accept(FossilsLegacyItems.OCELOT_DNA.get());
		output.accept(FossilsLegacyItems.PANDA_DNA.get());
		output.accept(FossilsLegacyItems.PARROT_DNA.get());
		output.accept(FossilsLegacyItems.PIG_DNA.get());
		output.accept(FossilsLegacyItems.POLAR_BEAR_DNA.get());
		output.accept(FossilsLegacyItems.RABBIT_DNA.get());
		output.accept(FossilsLegacyItems.SHEEP_DNA.get());
		output.accept(FossilsLegacyItems.TURTLE_DNA.get());
		output.accept(FossilsLegacyItems.WOLF_DNA.get());
		output.accept(FossilsLegacyItems.SMILODON_DNA.get());
		output.accept(FossilsLegacyItems.MAMMOTH_DNA.get());
		output.accept(FossilsLegacyItems.AXOLOTL_EGGS.get());
		output.accept(FossilsLegacyItems.CAT_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.INCUBATED_CHICKEN_EGG.get());
		output.accept(FossilsLegacyItems.COW_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.DOLPHIN_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.DONKEY_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.FOX_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.FROG_EGGS.get());
		output.accept(FossilsLegacyItems.GOAT_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.HORSE_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.LLAMA_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.MULE_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.OCELOT_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.PANDA_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.INCUBATED_PARROT_EGG.get());
		output.accept(FossilsLegacyItems.PIG_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.POLAR_BEAR_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.RABBIT_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.SHEEP_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.WOLF_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.SMILODON_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.MAMMOTH_EMBRYO_SYRINGE.get());
		output.accept(FossilsLegacyItems.JURASSIC_FERN_SPORES.get());
		output.accept(FossilsLegacyItems.RELIC_SCRAP.get());
		output.accept(FossilsLegacyItems.STONE_HIEROGLYPH.get());
		for (int i = 0; i < StoneHieroglyphTypes.values().length; i++) {
			ItemStack itemStack = new ItemStack(FossilsLegacyItems.STONE_HIEROGLYPH.get());
			CompoundTag compoundTag = itemStack.getOrCreateTagElement("EntityTag");
			compoundTag.putInt("Type", i);
			output.accept(itemStack);
		}
		output.accept(FossilsLegacyItems.SWORD_ARTIFACT.get());
		output.accept(FossilsLegacyItems.HELMET_ARTIFACT.get());
		output.accept(FossilsLegacyItems.GEM_ARTIFACT.get());
		output.accept(FossilsLegacyItems.ANCIENT_SWORD.get());
		output.accept(FossilsLegacyItems.ANCIENT_HELMET.get());
		output.accept(FossilsLegacyItems.GEM_SWORD.get());
		output.accept(FossilsLegacyItems.GEM_SHOVEL.get());
		output.accept(FossilsLegacyItems.GEM_PICKAXE.get());
		output.accept(FossilsLegacyItems.GEM_AXE.get());
		output.accept(FossilsLegacyItems.GEM_HOE.get());
		output.accept(FossilsLegacyItems.WOODEN_JAVELIN.get());
		output.accept(FossilsLegacyItems.STONE_JAVELIN.get());
		output.accept(FossilsLegacyItems.IRON_JAVELIN.get());
		output.accept(FossilsLegacyItems.GOLDEN_JAVELIN.get());
		output.accept(FossilsLegacyItems.DIAMOND_JAVELIN.get());
		output.accept(FossilsLegacyItems.NETHERITE_JAVELIN.get());
		output.accept(FossilsLegacyItems.GEM_JAVELIN.get());
		output.accept(FossilsLegacyBlocks.FOSSIL_ORE.get());
		output.accept(FossilsLegacyBlocks.SKULL_BLOCK.get());
		output.accept(FossilsLegacyBlocks.SKULL_LANTURN_BLOCK.get());
		output.accept(FossilsLegacyBlocks.ANALYZER.get());
		output.accept(FossilsLegacyBlocks.CULTIVATOR.get());
		output.accept(FossilsLegacyBlocks.ARCHAEOLOGY_WORKBENCH.get());
		output.accept(ForgeRegistries.ITEMS.getValue(FossilsLegacyUtils.resource("jurassic_fern")));
		output.accept(FossilsLegacyBlocks.DRUM.get());
		output.accept(FossilsLegacyBlocks.FEEDER.get());
		output.accept(FossilsLegacyBlocks.PERMAFROST.get());
		output.accept(FossilsLegacyBlocks.ICED_STONE.get());
		output.accept(FossilsLegacyItems.MAMMOTH_SPAWN_EGG.get());
		output.accept(FossilsLegacyItems.SMILODON_SPAWN_EGG.get());
		output.accept(FossilsLegacyItems.TRICERATOPS_SPAWN_EGG.get());
	}).build());
}
