package willatendo.fossilslegacy.server.utils;

public enum DinosaurTypes {
	TRICERATOPS,
	UTAHRAPTOR,
	TYRANNOSAURUS,
	PTEROSAURUS,
	NAUTILUS,
	PLESIOSAURUS,
	MOSASAURUS,
	STEGOSAURUS,
	DILOPHOSAURUS,
	BRACHIOSAURUS,
	MAMMOTH,
	SMILODON;
}
