package willatendo.fossilslegacy.server.coat_type;

import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import willatendo.fossilslegacy.server.entity.genetics.PatternType;
import willatendo.fossilslegacy.server.registry.FARegistries;
import willatendo.fossilslegacy.server.utils.FAUtils;

public final class FACoatTypes {
    public static final ResourceKey<CoatType> ANKYLOSAURUS = FACoatTypes.create("ankylosaurus");
    public static final ResourceKey<CoatType> BRACHIOSAURUS = FACoatTypes.create("brachiosaurus");
    public static final ResourceKey<CoatType> GREEN_CARNOTAURUS = FACoatTypes.create("green_carnotaurus");
    public static final ResourceKey<CoatType> RED_CARNOTAURUS = FACoatTypes.create("red_carnotaurus");
    public static final ResourceKey<CoatType> COMPSOGNATHUS = FACoatTypes.create("compsognathus");
    public static final ResourceKey<CoatType> CRYOLOPHOSAURUS = FACoatTypes.create("cryolophosaurus");
    public static final ResourceKey<CoatType> DILOPHOSAURUS = FACoatTypes.create("dilophosaurus");
    public static final ResourceKey<CoatType> DIMETRODON = FACoatTypes.create("dimetrodon");
    public static final ResourceKey<CoatType> DODO = FACoatTypes.create("dodo");
    public static final ResourceKey<CoatType> FUTABASAURUS = FACoatTypes.create("futabasaurus");
    public static final ResourceKey<CoatType> GALLIMIMUS = FACoatTypes.create("gallimimus");
    public static final ResourceKey<CoatType> MAMMOTH = FACoatTypes.create("mammoth");
    public static final ResourceKey<CoatType> MOA = FACoatTypes.create("moa");
    public static final ResourceKey<CoatType> MOSASAURUS = FACoatTypes.create("mosasaurus");
    public static final ResourceKey<CoatType> PACHYCEPHALOSAURUS = FACoatTypes.create("pachycephalosaurus");
    public static final ResourceKey<CoatType> PTERANODON = FACoatTypes.create("pteranodon");
    public static final ResourceKey<CoatType> SMILODON = FACoatTypes.create("smilodon");
    public static final ResourceKey<CoatType> SPINOSAURUS = FACoatTypes.create("spinosaurus");
    public static final ResourceKey<CoatType> STEGOSAURUS = FACoatTypes.create("stegosaurus");
    public static final ResourceKey<CoatType> THERIZINOSAURUS = FACoatTypes.create("therizinosaurus");
    public static final ResourceKey<CoatType> GREEN_TRICERATOPS = FACoatTypes.create("green_triceratops");
    public static final ResourceKey<CoatType> BROWN_TRICERATOPS = FACoatTypes.create("brown_triceratops");
    public static final ResourceKey<CoatType> TYRANNOSAURUS = FACoatTypes.create("tyrannosaurus");
    public static final ResourceKey<CoatType> GREEN_VELOCIRAPTOR = FACoatTypes.create("green_velociraptor");
    public static final ResourceKey<CoatType> SANDY_VELOCIRAPTOR = FACoatTypes.create("sandy_velociraptor");
    public static final ResourceKey<CoatType> WHITE_VELOCIRAPTOR = FACoatTypes.create("white_velociraptor");

    public static final ResourceKey<CoatType> LEGACY_BRACHIOSAURUS = FACoatTypes.create("legacy_brachiosaurus");
    public static final ResourceKey<CoatType> LEGACY_GREEN_CARNOTAURUS = FACoatTypes.create("legacy_green_carnotaurus");
    public static final ResourceKey<CoatType> LEGACY_RED_CARNOTAURUS = FACoatTypes.create("legacy_red_carnotaurus");
    public static final ResourceKey<CoatType> LEGACY_CRYOLOPHOSAURUS = FACoatTypes.create("legacy_cryolophosaurus");
    public static final ResourceKey<CoatType> LEGACY_DILOPHOSAURUS = FACoatTypes.create("legacy_dilophosaurus");
    public static final ResourceKey<CoatType> LEGACY_FUTABASAURUS = FACoatTypes.create("legacy_futabasaurus");
    public static final ResourceKey<CoatType> LEGACY_MAMMOTH = FACoatTypes.create("legacy_mammoth");
    public static final ResourceKey<CoatType> LEGACY_MOSASAURUS = FACoatTypes.create("legacy_mosasaurus");
    public static final ResourceKey<CoatType> LEGACY_PTERANODON = FACoatTypes.create("legacy_pteranodon");
    public static final ResourceKey<CoatType> LEGACY_SMILODON = FACoatTypes.create("legacy_smilodon");
    public static final ResourceKey<CoatType> LEGACY_STEGOSAURUS = FACoatTypes.create("legacy_stegosaurus");
    public static final ResourceKey<CoatType> LEGACY_FEATHERED_THERIZINOSAURUS = FACoatTypes.create("legacy_feathered_therizinosaurus");
    public static final ResourceKey<CoatType> LEGACY_FEATHERLESS_THERIZINOSAURUS = FACoatTypes.create("legacy_featherless_therizinosaurus");
    public static final ResourceKey<CoatType> LEGACY_GREEN_TRICERATOPS = FACoatTypes.create("legacy_green_triceratops");
    public static final ResourceKey<CoatType> LEGACY_BROWN_TRICERATOPS = FACoatTypes.create("legacy_brown_triceratops");
    public static final ResourceKey<CoatType> LEGACY_TYRANNOSAURUS = FACoatTypes.create("legacy_tyrannosaurus");
    public static final ResourceKey<CoatType> LEGACY_GREEN_VELOCIRAPTOR = FACoatTypes.create("legacy_green_velociraptor");
    public static final ResourceKey<CoatType> LEGACY_SANDY_VELOCIRAPTOR = FACoatTypes.create("legacy_sandy_velociraptor");
    public static final ResourceKey<CoatType> LEGACY_WHITE_VELOCIRAPTOR = FACoatTypes.create("legacy_white_velociraptor");

    private static ResourceKey<CoatType> create(String name) {
        return ResourceKey.create(FARegistries.COAT_TYPES, FAUtils.resource(name));
    }

    private static void register(BootstrapContext<CoatType> bootstrapContext, ResourceKey<CoatType> resourceKey, CoatType coatType) {
        bootstrapContext.register(resourceKey, coatType);
    }

    public static void bootstrap(BootstrapContext<CoatType> bootstrapContext) {
        FACoatTypes.register(bootstrapContext, ANKYLOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.ankylosaurus"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake"), 0x533A1B, 0.3F, 0.0F, FAUtils.resource("ankylosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/ankylosaurus/ankylosaurus_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/ankylosaurus/ankylosaurus_baby.png")), 1.75F, 1.5F, 0.2F, 1.5F, 1.5F, 0.3F, 1.0F, 0.25F).build());
        FACoatTypes.register(bootstrapContext, BRACHIOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.brachiosaurus"), Component.translatable("pattern.fossilslegacy.blue_iguana"), 0x3C3F56, 0.07F, 8.0F, FAUtils.resource("brachiosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/brachiosaurus/brachiosaurus_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/brachiosaurus/brachiosaurus_baby.png")), 1.75F, 2.5F, 0.3F, 1.5F, 1.5F, 0.4F, 1.0F, 0.15F).build());
        FACoatTypes.register(bootstrapContext, GREEN_CARNOTAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.green_carnotaurus"), Component.translatable("pattern.fossilslegacy.green_tree_python"), 0x485039, 0.35F, 1.0F, FAUtils.resource("carnotaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/carnotaurus/green_carnotaurus_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/carnotaurus/red_carnotaurus_baby.png")), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.4F, 0.75F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, RED_CARNOTAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.red_carnotaurus"), Component.translatable("pattern.fossilslegacy.northern_cardinal"), 0xBF5242, 0.35F, 1.0F, FAUtils.resource("carnotaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/carnotaurus/red_carnotaurus_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/carnotaurus/green_carnotaurus_baby.png")), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.4F, 0.75F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, COMPSOGNATHUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.compsognathus"), Component.translatable("pattern.fossilslegacy.green_tree_python"), 0x213D20, 2.0F, -1.0F, FAUtils.resource("compsognathus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/compsognathus/compsognathus.png"), PatternType.DOMINANT), 0.25F, 0.25F, 0.1F, 0.25F, 0.25F, 0.125F, 0.25F, 0.025F).build());
        FACoatTypes.register(bootstrapContext, CRYOLOPHOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.cryolophosaurus"), Component.translatable("pattern.fossilslegacy.blue_iguana"), 0x49658B, 0.75F, -0.2F, FAUtils.resource("cryolophosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/cryolophosaurus/cryolophosaurus_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/cryolophosaurus/cryolophosaurus_baby.png")), 0.35F, 0.35F, 0.2F, 0.25F, 0.25F, 0.2F, 0.15F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, DILOPHOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.dilophosaurus"), Component.translatable("pattern.fossilslegacy.inland_taipan"), 0x736F4A, 1.0F, 0.25F, FAUtils.resource("dilophosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/dilophosaurus/dilophosaurus_adult.png"), PatternType.DOMINANT).withAggressiveTexture(FAUtils.resource("textures/entity/dilophosaurus/aggressive_dilophosaurus_adult.png")), 0.5F, 0.5F, 0.2F, 0.2F, 0.2F, 0.15F, 0.15F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, DIMETRODON, CoatType.build(Component.translatable("coat_type.fossilslegacy.dimetrodon"), Component.translatable("pattern.fossilslegacy.eastern_indigo_snake"), 0x251A22, 1.0F, 0.0F, FAUtils.resource("dimetrodon"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/dimetrodon/dimetrodon_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/dimetrodon/dimetrodon_baby.png")).withAggressiveTexture(FAUtils.resource("textures/entity/dimetrodon/dimetrodon_agressive.png")), 0.5F, 0.5F, 0.05F, 0.5F, 0.5F, 0.075F, 0.15F, 0.05F).build());
        FACoatTypes.register(bootstrapContext, DODO, CoatType.build(Component.translatable("coat_type.fossilslegacy.dodo"), Component.translatable("pattern.fossilslegacy.domestic_pigeon"), 0x5A5A5A, 2.0F, -1.0F, FAUtils.resource("dodo"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/dodo/dodo.png"), PatternType.DOMINANT), 0.5F, 0.5F, 0.05F, 0.5F, 0.5F, 0.07142857142F, 0.15F, 0.05F).build());
        FACoatTypes.register(bootstrapContext, FUTABASAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.futabasaurus"), Component.translatable("pattern.fossilslegacy.broadhead_skink"), 0xB92200, 0.35F, 0.25F, FAUtils.resource("futabasaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/futabasaurus/futabasaurus.png"), PatternType.DOMINANT), 2.0F, 0.75F, 0.25F, 1.5F, 1.5F, 0.3F, 1.0F, 0.15F).build());
        FACoatTypes.register(bootstrapContext, GALLIMIMUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.gallimimus"), Component.translatable("pattern.fossilslegacy.broadhead_skink"), 0x774913, 0.4F, 1.5F, FAUtils.resource("gallimimus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/gallimimus/gallimimus_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/gallimimus/gallimimus_baby.png")), 0.7F, 0.7F, 0.25F, 0.75F, 0.75F, 0.2F, 1.0F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, MAMMOTH, CoatType.build(Component.translatable("coat_type.fossilslegacy.mammoth"), Component.translatable("pattern.fossilslegacy.american_bison"), 0x3D2700, 0.4F, 1.0F, FAUtils.resource("mammoth"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/mammoth/mammoth_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/mammoth/mammoth_baby.png")).withFurTexture(FAUtils.resource("textures/entity/mammoth/mammoth_adult_fur.png")).withBabyFurTexture(FAUtils.resource("textures/entity/mammoth/mammoth_baby_fur.png")).withShearedTexture(FAUtils.resource("textures/entity/mammoth/mammoth_adult_sheared.png")), 0.7F, 0.7F, 0.5F, 1.0F, 1.0F, 0.4F, 0.75F, 0.15F).build());
        FACoatTypes.register(bootstrapContext, MOSASAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.mosasaurus"), Component.translatable("pattern.fossilslegacy.marine_iguana"), 0x0D7346, 0.3F, 0.25F, FAUtils.resource("mosasaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/mosasaurus/mosasaurus.png"), PatternType.DOMINANT).withEyeLayerTexture(FAUtils.resource("textures/entity/mosasaurus/mosasaurus_eyes.png")), 0.5F, 0.5F, 0.2F, 0.5F, 0.5F, 0.5125F, 0.5F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, MOA, CoatType.build(Component.translatable("coat_type.fossilslegacy.moa"), Component.translatable("pattern.fossilslegacy.american_bison"), 0x352A17, 0.45F, 1.0F, FAUtils.resource("moa"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/moa/moa.png"), PatternType.DOMINANT), 0.5F, 1.5F, 0.1F, 0.5F, 0.5F, 0.25F, 0.15F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, PACHYCEPHALOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.pachycephalosaurus"), Component.translatable("pattern.fossilslegacy.broadhead_skink"), 0xC06929, 0.7F, 0.0F, FAUtils.resource("pachycephalosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/pachycephalosaurus/pachycephalosaurus_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/pachycephalosaurus/pachycephalosaurus_baby.png")), 0.7F, 0.7F, 0.1F, 1.0F, 1.0F, 0.1F, 0.5F, 0.075F).build());
        FACoatTypes.register(bootstrapContext, PTERANODON, CoatType.build(Component.translatable("coat_type.fossilslegacy.pteranodon"), Component.translatable("pattern.fossilslegacy.eastern_indigo_snake"), 0x7C5D89, 0.75F, 0.0F, FAUtils.resource("pteranodon"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/pteranodon/pteranodon_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/pteranodon/pteranodon_baby.png")), 0.5F, 0.5F, 0.2F, 0.8F, 0.8F, 0.2F, 0.5F, 0.075F).build());
        FACoatTypes.register(bootstrapContext, SMILODON, CoatType.build(Component.translatable("coat_type.fossilslegacy.smilodon"), Component.translatable("pattern.fossilslegacy.tiger"), 0xEFA745, 1.0F, -0.5F, FAUtils.resource("smilodon"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/smilodon/smilodon_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/smilodon/smilodon_baby.png")), 0.75F, 0.75F, 0.1F, 0.7F, 0.7F, 0.1F, 0.5F, 0.05F).build());
        FACoatTypes.register(bootstrapContext, SPINOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.spinosaurus"), Component.translatable("pattern.fossilslegacy.marine_iguana"), 0x26261D, 0.25F, 3.0F, FAUtils.resource("spinosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/spinosaurus/spinosaurus_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/spinosaurus/spinosaurus_baby.png")), 0.5F, 0.5F, 0.4F, 0.5F, 0.5F, 0.5125F, 0.5F, 0.15F).build());
        FACoatTypes.register(bootstrapContext, STEGOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.stegosaurus"), Component.translatable("pattern.fossilslegacy.green_tree_python"), 0x8BE400, 0.3F, 1.0F, FAUtils.resource("stegosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/stegosaurus/stegosaurus_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/stegosaurus/stegosaurus_baby.png")), 0.75F, 0.75F, 0.2F, 0.8F, 0.8F, 0.2F, 1.0F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, THERIZINOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.therizinosaurus"), Component.translatable("pattern.fossilslegacy.green_parakeet"), 0xCE551D, 0.25F, 0.25F, FAUtils.resource("therizinosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/therizinosaurus/therizinosaurus_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/therizinosaurus/therizinosaurus_baby.png")), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.25F, 0.75F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, GREEN_TRICERATOPS, CoatType.build(Component.translatable("coat_type.fossilslegacy.green_triceratops"), Component.translatable("pattern.fossilslegacy.green_tree_python"), 0xADE642, 0.4F, 0.0F, FAUtils.resource("triceratops"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/triceratops/green_triceratops_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/triceratops/green_triceratops_baby.png")), 1.0F, 1.0F, 0.2F, 1.0F, 1.0F, 0.15F, 1.0F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, BROWN_TRICERATOPS, CoatType.build(Component.translatable("coat_type.fossilslegacy.brown_triceratops"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake"), 0xA58856, 0.4F, 0.0F, FAUtils.resource("triceratops"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/triceratops/brown_triceratops_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/triceratops/brown_triceratops_baby.png")), 1.0F, 1.0F, 0.2F, 1.0F, 1.0F, 0.15F, 1.0F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, TYRANNOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.tyrannosaurus"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake"), 0x918066, 0.25F, 0.25F, FAUtils.resource("tyrannosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/tyrannosaurus/tyrannosaurus_adult.png"), PatternType.DOMINANT).withAggressiveTexture(FAUtils.resource("textures/entity/tyrannosaurus/tyrannosaurus_aggressive.png")).withKnockedOutTexture(FAUtils.resource("textures/entity/tyrannosaurus/tyrannosaurus_weak.png")).withBabyTexture(FAUtils.resource("textures/entity/tyrannosaurus/tyrannosaurus_baby.png")), 0.5F, 0.5F, 0.6F, 0.5F, 0.5F, 0.5125F, 0.75F, 0.15F).withKnockoutModel(FAUtils.resource("knocked_out_tyrannosaurus")).build());
        FACoatTypes.register(bootstrapContext, GREEN_VELOCIRAPTOR, CoatType.build(Component.translatable("coat_type.fossilslegacy.green_velociraptor"), Component.translatable("pattern.fossilslegacy.green_tree_python"), 0x0C3F4C, 1.5F, -0.75F, FAUtils.resource("velociraptor"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/green_velociraptor_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/green_velociraptor_baby.png")), 0.2F, 0.4F, 0.05F, 0.5F, 0.5F, 0.1F, 0.5F, 0.025F).build());
        FACoatTypes.register(bootstrapContext, SANDY_VELOCIRAPTOR, CoatType.build(Component.translatable("coat_type.fossilslegacy.sandy_velociraptor"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake"), 0x632D09, 1.5F, -0.75F, FAUtils.resource("velociraptor"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/sandy_velociraptor_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/sandy_velociraptor_baby.png")), 0.2F, 0.4F, 0.05F, 0.5F, 0.5F, 0.1F, 0.5F, 0.025F).build());
        FACoatTypes.register(bootstrapContext, WHITE_VELOCIRAPTOR, CoatType.build(Component.translatable("coat_type.fossilslegacy.white_velociraptor"), Component.translatable("pattern.fossilslegacy.gray_ratsnake"), 0x252525, 1.5F, -0.75F, FAUtils.resource("velociraptor"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/white_velociraptor_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/white_velociraptor_baby.png")), 0.2F, 0.4F, 0.05F, 0.5F, 0.5F, 0.1F, 0.5F, 0.025F).build());

        FACoatTypes.register(bootstrapContext, LEGACY_BRACHIOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_brachiosaurus"), Component.translatable("pattern.fossilslegacy.blue_iguana"), 0x363950, 0.07F, 8.0F, FAUtils.resource("legacy_brachiosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/brachiosaurus/legacy/brachiosaurus.png"), PatternType.DOMINANT), 1.75F, 2.5F, 0.3F, 1.5F, 1.5F, 0.3F, 0.15F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_GREEN_CARNOTAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_green_carnotaurus"), Component.translatable("pattern.fossilslegacy.green_tree_python"), 0x485039, 0.35F, 1.0F, FAUtils.resource("legacy_carnotaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/carnotaurus/legacy/green_carnotaurus.png"), PatternType.DOMINANT), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.3F, 0.75F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_RED_CARNOTAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_red_carnotaurus"), Component.translatable("pattern.fossilslegacy.northern_cardinal"), 0xBF5242, 0.35F, 1.0F, FAUtils.resource("legacy_carnotaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/carnotaurus/legacy/red_carnotaurus.png"), PatternType.DOMINANT), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.3F, 0.75F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_CRYOLOPHOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_cryolophosaurus"), Component.translatable("pattern.fossilslegacy.blue_iguana"), 0x49658B, 0.75F, -0.2F, FAUtils.resource("legacy_cryolophosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/cryolophosaurus/legacy/cryolophosaurus.png"), PatternType.DOMINANT), 0.35F, 0.35F, 0.2F, 0.25F, 0.25F, 0.2F, 0.15F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_DILOPHOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_dilophosaurus"), Component.translatable("pattern.fossilslegacy.inland_taipan"), 0x736F4A, 1.0F, 0.25F, FAUtils.resource("legacy_dilophosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/dilophosaurus/legacy/dilophosaurus.png"), PatternType.DOMINANT).withAggressiveTexture(FAUtils.resource("textures/entity/dilophosaurus/legacy/dilophosaurus_aggressive.png")), 0.5F, 0.5F, 0.2F, 0.2F, 0.2F, 0.15F, 0.15F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_FUTABASAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_futabasaurus"), Component.translatable("pattern.fossilslegacy.broadhead_skink"), 0xC75B00, 0.3F, 0.25F, FAUtils.resource("legacy_futabasaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/futabasaurus/legacy/futabasaurus.png"), PatternType.DOMINANT), 0.75F, 0.75F, 0.2F, 1.5F, 1.5F, 0.3F, 0.15F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_MAMMOTH, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_mammoth"), Component.translatable("pattern.fossilslegacy.american_bison"), 0x3D2700, 0.4F, 0.0F, FAUtils.resource("legacy_mammoth"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/mammoth/legacy/mammoth_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/mammoth/legacy/mammoth_baby.png")).withFurTexture(FAUtils.resource("textures/entity/mammoth/legacy/mammoth_adult_fur.png")).withBabyFurTexture(FAUtils.resource("textures/entity/mammoth/legacy/mammoth_baby_fur.png")).withShearedTexture(FAUtils.resource("textures/entity/mammoth/legacy/mammoth_adult_sheared.png")), 0.7F, 0.7F, 0.5F, 1.0F, 1.0F, 0.625F, 0.75F, 0.15F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_MOSASAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_mosasaurus"), Component.translatable("pattern.fossilslegacy.marine_iguana"), 0x0D7346, 0.4F, 0.25F, FAUtils.resource("legacy_mosasaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/mosasaurus/legacy/mosasaurus.png"), PatternType.DOMINANT).withEyeLayerTexture(FAUtils.resource("textures/entity/mosasaurus/legacy/mosasaurus_eyes.png")), 0.5F, 0.5F, 0.2F, 0.5F, 0.5F, 0.5125F, 0.5F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_PTERANODON, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_pteranodon"), Component.translatable("pattern.fossilslegacy.eastern_indigo_snake"), 0x7C5D89, 0.75F, 0.0F, FAUtils.resource("legacy_pteranodon"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/pteranodon/legacy/pteranodon.png"), PatternType.DOMINANT), 0.5F, 0.5F, 0.2F, 0.8F, 0.8F, 0.2F, 0.5F, 0.075F).withFlyingModels(FAUtils.resource("legacy_flying_pteranodon"), FAUtils.resource("legacy_landing_pteranodon")).build());
        FACoatTypes.register(bootstrapContext, LEGACY_SMILODON, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_smilodon"), Component.translatable("pattern.fossilslegacy.tiger"), 0xEFA745, 1.0F, -0.5F, FAUtils.resource("legacy_smilodon"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/smilodon/legacy/smilodon_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/smilodon/legacy/smilodon_baby.png")), 0.75F, 0.75F, 0.1F, 1.0F, 1.0F, 0.14285714285F, 0.5F, 0.05F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_STEGOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_stegosaurus"), Component.translatable("pattern.fossilslegacy.green_tree_python"), 0x8BE400, 0.3F, 0.0F, FAUtils.resource("legacy_stegosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/stegosaurus/legacy/stegosaurus_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/stegosaurus/legacy/stegosaurus_baby.png")), 0.75F, 0.75F, 0.2F, 1.5F, 1.5F, 0.3F, 1.0F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_FEATHERED_THERIZINOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_feathered_therizinosaurus"), Component.translatable("pattern.fossilslegacy.green_parakeet"), 0xCE551D, 0.25F, 0.25F, FAUtils.resource("legacy_therizinosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/therizinosaurus/legacy/therizinosaurus_feathered.png"), PatternType.DOMINANT), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.35F, 0.75F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_FEATHERLESS_THERIZINOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_featherless_therizinosaurus"), Component.translatable("pattern.fossilslegacy.green_tree_python"), 0x606F3F, 0.25F, 0.25F, FAUtils.resource("legacy_therizinosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/therizinosaurus/legacy/therizinosaurus_featherless.png"), PatternType.DOMINANT), 0.5F, 0.5F, 0.35F, 0.5F, 0.5F, 0.35F, 0.75F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_GREEN_TRICERATOPS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_green_triceratops"), Component.translatable("pattern.fossilslegacy.green_tree_python"), 0xB6EF4B, 0.4F, 0.0F, FAUtils.resource("legacy_triceratops"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/triceratops/legacy/green_triceratops_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/triceratops/legacy/green_triceratops_baby.png")), 0.75F, 0.75F, 0.15F, 1.5F, 1.5F, 0.3F, 1.0F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_BROWN_TRICERATOPS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_brown_triceratops"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake"), 0xE3BB7B, 0.4F, 0.0F, FAUtils.resource("legacy_triceratops"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/triceratops/legacy/brown_triceratops_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/triceratops/legacy/brown_triceratops_baby.png")), 0.75F, 0.75F, 0.15F, 1.5F, 1.5F, 0.3F, 1.0F, 0.1F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_TYRANNOSAURUS, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_tyrannosaurus"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake"), 0x918066, 0.25F, 0.25F, FAUtils.resource("legacy_tyrannosaurus"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/tyrannosaurus/legacy/tyrannosaurus.png"), PatternType.DOMINANT).withAggressiveTexture(FAUtils.resource("textures/entity/tyrannosaurus/legacy/tyrannosaurus_aggressive.png")).withKnockedOutTexture(FAUtils.resource("textures/entity/tyrannosaurus/legacy/tyrannosaurus_weak.png")), 0.5F, 0.5F, 0.6F, 0.5F, 0.5F, 0.5125F, 0.75F, 0.15F).withKnockoutModel(FAUtils.resource("legacy_knocked_out_tyrannosaurus")).build());
        FACoatTypes.register(bootstrapContext, LEGACY_GREEN_VELOCIRAPTOR, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_green_velociraptor"), Component.translatable("pattern.fossilslegacy.green_tree_python"), 0x71A367, 1.0F, -0.75F, FAUtils.resource("legacy_velociraptor"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/legacy/green_velociraptor_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/legacy/green_velociraptor_baby.png")), 0.3F, 0.3F, 0.1F, 0.2F, 0.32F, 0.1F, 0.35F, 0.05F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_SANDY_VELOCIRAPTOR, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_sandy_velociraptor"), Component.translatable("pattern.fossilslegacy.eastern_brown_snake"), 0xD6C68E, 1.0F, -0.75F, FAUtils.resource("legacy_velociraptor"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/legacy/sandy_velociraptor_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/legacy/sandy_velociraptor_baby.png")), 0.3F, 0.3F, 0.1F, 0.2F, 0.32F, 0.1F, 0.35F, 0.05F).build());
        FACoatTypes.register(bootstrapContext, LEGACY_WHITE_VELOCIRAPTOR, CoatType.build(Component.translatable("coat_type.fossilslegacy.legacy_white_velociraptor"), Component.translatable("pattern.fossilslegacy.gray_ratsnake"), 0xC0C5D5, 1.0F, -0.75F, FAUtils.resource("legacy_velociraptor"), CoatType.Pattern.builder(FAUtils.resource("textures/entity/velociraptor/legacy/white_velociraptor_adult.png"), PatternType.DOMINANT).withBabyTexture(FAUtils.resource("textures/entity/velociraptor/legacy/white_velociraptor_baby.png")), 0.3F, 0.3F, 0.1F, 0.2F, 0.32F, 0.1F, 0.35F, 0.05F).build());
    }
}
