package willatendo.fossilslegacy.server.item;

import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.ArmorItem.Type;
import net.minecraft.world.item.AxeItem;
import net.minecraft.world.item.HoeItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemNameBlockItem;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.PickaxeItem;
import net.minecraft.world.item.ShovelItem;
import net.minecraft.world.item.SwordItem;
import net.minecraft.world.item.Tiers;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import willatendo.fossilslegacy.server.block.FossilsLegacyBlocks;
import willatendo.fossilslegacy.server.entity.Egg;
import willatendo.fossilslegacy.server.entity.FossilsLegacyEntities;
import willatendo.fossilslegacy.server.utils.FossilsLegacyUtils;
import willatendo.fossilslegacy.server.utils.SyringeAnimals;
import willatendo.simplelibrary.server.util.SimpleUtils;

public class FossilsLegacyItems {
	public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, FossilsLegacyUtils.ID);

	public static final RegistryObject<Item> FOSSIL = ITEMS.register("fossil", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> TRICERATOPS_DNA = ITEMS.register("triceratops_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> UTAHRAPTOR_DNA = ITEMS.register("utahraptor_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> TYRANNOSAURUS_DNA = ITEMS.register("tyrannosaurus_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> PTEROSAURUS_DNA = ITEMS.register("pterosaurus_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> NAUTILUS_DNA = ITEMS.register("nautilus_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> PLESIOSAURUS_DNA = ITEMS.register("plesiosaurus_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> MOSASAURUS_DNA = ITEMS.register("mosasaurus_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> STEGOSAURUS_DNA = ITEMS.register("stegosaurus_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> DILOPHOSAURUS_DNA = ITEMS.register("dilophosaurus_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> BRACHIOSAURUS_DNA = ITEMS.register("brachiosaurus_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> TRICERATOPS_EGG = ITEMS.register("triceratops_egg", () -> new EggItem(Egg.Eggs.TRICERATOPS, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> UTAHRAPTOR_EGG = ITEMS.register("utahraptor_egg", () -> new EggItem(Egg.Eggs.UTAHRAPTOR, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> TYRANNOSAURUS_EGG = ITEMS.register("tyrannosaurus_egg", () -> new EggItem(Egg.Eggs.TYRANNOSAURUS, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> PTEROSAURUS_EGG = ITEMS.register("pterosaurus_egg", () -> new EggItem(Egg.Eggs.PTEROSAURUS, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> NAUTILUS_EGGS = ITEMS.register("nautilus_eggs", () -> new Item(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> PLESIOSAURUS_EGG = ITEMS.register("plesiosaurus_egg", () -> new EggItem(Egg.Eggs.PLESIOSAURUS, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> MOSASAURUS_EGG = ITEMS.register("mosasaurus_egg", () -> new EggItem(Egg.Eggs.MOSASAURUS, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> STEGOSAURUS_EGG = ITEMS.register("stegosaurus_egg", () -> new EggItem(Egg.Eggs.STEGOSAURUS, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> DILOPHOSAURUS_EGG = ITEMS.register("dilophosaurus_egg", () -> new EggItem(Egg.Eggs.DILOPHOSAURUS, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> BRACHIOSAURUS_EGG = ITEMS.register("brachiosaurus_egg", () -> new EggItem(Egg.Eggs.BRACHIOSAURUS, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> RAW_TRICERATOPS_MEAT = ITEMS.register("raw_triceratops_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.RAW_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> RAW_UTAHRAPTOR_MEAT = ITEMS.register("raw_utahraptor_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.RAW_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> RAW_TYRANNOSAURUS_MEAT = ITEMS.register("raw_tyrannosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.RAW_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> RAW_PTEROSAURUS_MEAT = ITEMS.register("raw_pterosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.RAW_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> NAUTILUS = ITEMS.register("nautilus", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> RAW_PLESIOSAURUS_MEAT = ITEMS.register("raw_plesiosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.RAW_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> RAW_MOSASAURUS_MEAT = ITEMS.register("raw_mosasaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.RAW_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> RAW_STEGOSAURUS_MEAT = ITEMS.register("raw_stegosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.RAW_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> RAW_DILOPHOSAURUS_MEAT = ITEMS.register("raw_dilophosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.RAW_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> RAW_BRACHIOSAURUS_MEAT = ITEMS.register("raw_brachiosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.RAW_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> RAW_SMILODON_MEAT = ITEMS.register("raw_smilodon_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.RAW_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> RAW_MAMMOTH_MEAT = ITEMS.register("raw_mammoth_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.RAW_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> COOKED_TRICERATOPS_MEAT = ITEMS.register("cooked_triceratops_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.COOKED_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> COOKED_UTAHRAPTOR_MEAT = ITEMS.register("cooked_utahraptor_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.COOKED_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> COOKED_TYRANNOSAURUS_MEAT = ITEMS.register("cooked_tyrannosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.COOKED_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> COOKED_PTEROSAURUS_MEAT = ITEMS.register("cooked_pterosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.COOKED_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> SIO_CHIU_LE = ITEMS.register("sio_chiu_le", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.SIO_CHIU_LE)));
	public static final RegistryObject<Item> COOKED_PLESIOSAURUS_MEAT = ITEMS.register("cooked_plesiosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.COOKED_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> COOKED_MOSASAURUS_MEAT = ITEMS.register("cooked_mosasaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.COOKED_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> COOKED_STEGOSAURUS_MEAT = ITEMS.register("cooked_stegosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.COOKED_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> COOKED_DILOPHOSAURUS_MEAT = ITEMS.register("cooked_dilophosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.COOKED_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> COOKED_BRACHIOSAURUS_MEAT = ITEMS.register("cooked_brachiosaurus_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.COOKED_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> COOKED_SMILODON_MEAT = ITEMS.register("cooked_smilodon_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.COOKED_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> COOKED_MAMMOTH_MEAT = ITEMS.register("cooked_mammoth_meat", () -> new Item(new Item.Properties().food(FossilsLegacyFoods.COOKED_DINOSAUR_MEAT)));
	public static final RegistryObject<Item> TYRANNOSAURUS_TOOTH = ITEMS.register("tyrannosaurus_tooth", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> TOOTH_DAGGER = ITEMS.register("tooth_dagger", () -> new ToothDaggerItem(FossilsLegacyTiers.DAGGER, 3, -2.4F, new Item.Properties()));
	public static final RegistryObject<Item> SKULL_STICK = ITEMS.register("skull_stick", () -> new Item(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> DINOSAUR_ENCYCLOPEDIA = ITEMS.register("dinosaur_encyclopedia", () -> new DinosaurEncyclopediaItem(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> RAW_CHICKEN_SOUP_BUCKET = ITEMS.register("raw_chicken_soup_bucket", () -> new BucketFoodItem(new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET).food(FossilsLegacyFoods.RAW_CHICKEN_SOUP)));
	public static final RegistryObject<Item> COOKED_CHICKEN_SOUP_BUCKET = ITEMS.register("cooked_chicken_soup_bucket", () -> new BucketFoodItem(new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET).food(FossilsLegacyFoods.COOKED_CHICKEN_SOUP)));
	public static final RegistryObject<Item> CHICKEN_ESSENCE_BOTTLE = ITEMS.register("chicken_essence_bottle", () -> new ChickenEssanceBottleItem(new Item.Properties().stacksTo(16).food(FossilsLegacyFoods.CHICKEN_ESSENCE)));
	public static final RegistryObject<Item> NAUTILUS_SHELL = ITEMS.register("nautilus_shell", () -> new Item(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> MAGIC_CONCH = ITEMS.register("magic_conch", () -> new MagicConchItem(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> FROZEN_MEAT = ITEMS.register("frozen_meat", () -> new FrozenMeatItem(new Item.Properties()));
	public static final RegistryObject<Item> BROKEN_FROZEN_MEAT = ITEMS.register("broken_frozen_meat", () -> new BrokenFrozenMeatItem(FossilsLegacyTiers.ICED_MEAT, 3, -2.4F, new Item.Properties()));
	public static final RegistryObject<Item> AXOLOTL_DNA = ITEMS.register("axolotl_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> CAT_DNA = ITEMS.register("cat_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> CHICKEN_DNA = ITEMS.register("chicken_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> COW_DNA = ITEMS.register("cow_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> DOLPHIN_DNA = ITEMS.register("dolphin_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> DONKEY_DNA = ITEMS.register("donkey_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> FOX_DNA = ITEMS.register("fox_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> FROG_DNA = ITEMS.register("frog_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> GOAT_DNA = ITEMS.register("goat_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> HORSE_DNA = ITEMS.register("horse_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> LLAMA_DNA = ITEMS.register("llama_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> MULE_DNA = ITEMS.register("mule_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> OCELOT_DNA = ITEMS.register("ocelot_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> PANDA_DNA = ITEMS.register("panda_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> PARROT_DNA = ITEMS.register("parrot_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> PIG_DNA = ITEMS.register("pig_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> POLAR_BEAR_DNA = ITEMS.register("polar_bear_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> RABBIT_DNA = ITEMS.register("rabbit_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> SHEEP_DNA = ITEMS.register("sheep_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> TURTLE_DNA = ITEMS.register("turtle_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> WOLF_DNA = ITEMS.register("wolf_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> SMILODON_DNA = ITEMS.register("smilodon_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> MAMMOTH_DNA = ITEMS.register("mammoth_dna", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> AXOLOTL_EGGS = ITEMS.register("axolotl_eggs", () -> new PlaceEntityItem(() -> EntityType.AXOLOTL, new Item.Properties()));
	public static final RegistryObject<Item> CAT_EMBRYO_SYRINGE = ITEMS.register("cat_embryo_syringe", () -> new SyringeItem(SyringeAnimals.CAT, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> INCUBATED_CHICKEN_EGG = ITEMS.register("incubated_chicken_egg", () -> new IncubatedEggItem(0, new Item.Properties().stacksTo(16)));
	public static final RegistryObject<Item> COW_EMBRYO_SYRINGE = ITEMS.register("cow_embryo_syringe", () -> new SyringeItem(SyringeAnimals.COW, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> DOLPHIN_EMBRYO_SYRINGE = ITEMS.register("dolphin_embryo_syringe", () -> new SyringeItem(SyringeAnimals.DOLPHIN, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> DONKEY_EMBRYO_SYRINGE = ITEMS.register("donkey_embryo_syringe", () -> new SyringeItem(SyringeAnimals.DONKEY, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> FOX_EMBRYO_SYRINGE = ITEMS.register("fox_embryo_syringe", () -> new SyringeItem(SyringeAnimals.FOX, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> FROG_EGGS = ITEMS.register("frog_eggs", () -> new PlaceEntityItem(() -> EntityType.TADPOLE, new Item.Properties()));
	public static final RegistryObject<Item> GOAT_EMBRYO_SYRINGE = ITEMS.register("goat_embryo_syringe", () -> new SyringeItem(SyringeAnimals.GOAT, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> HORSE_EMBRYO_SYRINGE = ITEMS.register("horse_embryo_syringe", () -> new SyringeItem(SyringeAnimals.HORSE, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> LLAMA_EMBRYO_SYRINGE = ITEMS.register("llama_embryo_syringe", () -> new SyringeItem(SyringeAnimals.LLAMA, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> MULE_EMBRYO_SYRINGE = ITEMS.register("mule_embryo_syringe", () -> new SyringeItem(SyringeAnimals.MULE, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> OCELOT_EMBRYO_SYRINGE = ITEMS.register("ocelot_embryo_syringe", () -> new SyringeItem(SyringeAnimals.OCELOT, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> PANDA_EMBRYO_SYRINGE = ITEMS.register("panda_embryo_syringe", () -> new SyringeItem(SyringeAnimals.PANDA, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> INCUBATED_PARROT_EGG = ITEMS.register("incubated_parrot_egg", () -> new IncubatedEggItem(1, new Item.Properties().stacksTo(16)));
	public static final RegistryObject<Item> PIG_EMBRYO_SYRINGE = ITEMS.register("pig_embryo_syringe", () -> new SyringeItem(SyringeAnimals.PIG, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> POLAR_BEAR_EMBRYO_SYRINGE = ITEMS.register("polar_bear_embryo_syringe", () -> new SyringeItem(SyringeAnimals.POLAR_BEAR, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> RABBIT_EMBRYO_SYRINGE = ITEMS.register("rabbit_embryo_syringe", () -> new SyringeItem(SyringeAnimals.RABBIT, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> SHEEP_EMBRYO_SYRINGE = ITEMS.register("sheep_embryo_syringe", () -> new SyringeItem(SyringeAnimals.SHEEP, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> WOLF_EMBRYO_SYRINGE = ITEMS.register("wolf_embryo_syringe", () -> new SyringeItem(SyringeAnimals.WOLF, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> SMILODON_EMBRYO_SYRINGE = ITEMS.register("smilodon_embryo_syringe", () -> new SyringeItem(SyringeAnimals.SMILODON, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> MAMMOTH_EMBRYO_SYRINGE = ITEMS.register("mammoth_embryo_syringe", () -> new SyringeItem(SyringeAnimals.MAMMOTH, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> JURASSIC_FERN_SPORES = ITEMS.register("jurassic_fern_spores", () -> new ItemNameBlockItem(FossilsLegacyBlocks.JURASSIC_FERN.get(), new Item.Properties()));
	public static final RegistryObject<Item> RELIC_SCRAP = ITEMS.register("relic_scrap", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> STONE_HIEROGLYPH = ITEMS.register("stone_hieroglyph", () -> new StoneHieroglyphItem(new Item.Properties()));
	public static final RegistryObject<Item> SWORD_ARTIFACT = ITEMS.register("sword_artifact", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> HELMET_ARTIFACT = ITEMS.register("helmet_artifact", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> GEM_ARTIFACT = ITEMS.register("gem_artifact", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> ANCIENT_SWORD = ITEMS.register("ancient_sword", () -> new AncientSwordItem(FossilsLegacyTiers.ANCIENT, 3, -2.4F, new Item.Properties()));
	public static final RegistryObject<Item> ANCIENT_HELMET = ITEMS.register("ancient_helmet", () -> new ModArmourItem("ancient", FossilsLegacyArmorMaterials.ANCIENT, Type.HELMET, new Item.Properties()));
	public static final RegistryObject<Item> GEM_SWORD = ITEMS.register("gem_sword", () -> new SwordItem(FossilsLegacyTiers.GEM, 3, -2.4F, new Item.Properties()));
	public static final RegistryObject<Item> GEM_SHOVEL = ITEMS.register("gem_shovel", () -> new ShovelItem(FossilsLegacyTiers.GEM, 1.5F, -3.0F, new Item.Properties()));
	public static final RegistryObject<Item> GEM_PICKAXE = ITEMS.register("gem_pickaxe", () -> new PickaxeItem(FossilsLegacyTiers.GEM, 1, -2.8F, new Item.Properties()));
	public static final RegistryObject<Item> GEM_AXE = ITEMS.register("gem_axe", () -> new AxeItem(FossilsLegacyTiers.GEM, 5.0F, -3.0F, new Item.Properties()));
	public static final RegistryObject<Item> GEM_HOE = ITEMS.register("gem_hoe", () -> new HoeItem(FossilsLegacyTiers.GEM, -4, 0.0F, new Item.Properties()));
	public static final RegistryObject<Item> GEM_UPGRADE_SMITHING_TEMPLATE = ITEMS.register("gem_upgrade_smithing_template", () -> ModSmithingTemplateItem.createGemUpgradeTemplate());
	public static final RegistryObject<Item> WOODEN_JAVELIN = ITEMS.register("wooden_javelin", () -> new JavelinItem(Tiers.WOOD, new Item.Properties().stacksTo(16)));
	public static final RegistryObject<Item> BROKEN_WOODEN_JAVELIN = ITEMS.register("broken_wooden_javelin", () -> new BrokenJavelinItem(Tiers.WOOD, new Item.Properties()));
	public static final RegistryObject<Item> STONE_JAVELIN = ITEMS.register("stone_javelin", () -> new JavelinItem(Tiers.STONE, new Item.Properties().stacksTo(16)));
	public static final RegistryObject<Item> BROKEN_STONE_JAVELIN = ITEMS.register("broken_stone_javelin", () -> new BrokenJavelinItem(Tiers.STONE, new Item.Properties()));
	public static final RegistryObject<Item> IRON_JAVELIN = ITEMS.register("iron_javelin", () -> new JavelinItem(Tiers.IRON, new Item.Properties().stacksTo(16)));
	public static final RegistryObject<Item> BROKEN_IRON_JAVELIN = ITEMS.register("broken_iron_javelin", () -> new BrokenJavelinItem(Tiers.IRON, new Item.Properties()));
	public static final RegistryObject<Item> GOLDEN_JAVELIN = ITEMS.register("golden_javelin", () -> new JavelinItem(Tiers.GOLD, new Item.Properties().stacksTo(16)));
	public static final RegistryObject<Item> BROKEN_GOLDEN_JAVELIN = ITEMS.register("broken_golden_javelin", () -> new BrokenJavelinItem(Tiers.GOLD, new Item.Properties()));
	public static final RegistryObject<Item> DIAMOND_JAVELIN = ITEMS.register("diamond_javelin", () -> new JavelinItem(Tiers.DIAMOND, new Item.Properties().stacksTo(16)));
	public static final RegistryObject<Item> BROKEN_DIAMOND_JAVELIN = ITEMS.register("broken_diamond_javelin", () -> new BrokenJavelinItem(Tiers.DIAMOND, new Item.Properties()));
	public static final RegistryObject<Item> NETHERITE_JAVELIN = ITEMS.register("netherite_javelin", () -> new JavelinItem(Tiers.NETHERITE, new Item.Properties().stacksTo(16)));
	public static final RegistryObject<Item> BROKEN_NETHERITE_JAVELIN = ITEMS.register("broken_netherite_javelin", () -> new BrokenJavelinItem(Tiers.NETHERITE, new Item.Properties()));
	public static final RegistryObject<Item> GEM_JAVELIN = ITEMS.register("gem_javelin", () -> new JavelinItem(FossilsLegacyTiers.GEM, new Item.Properties().stacksTo(16)));
	public static final RegistryObject<Item> BROKEN_GEM_JAVELIN = ITEMS.register("broken_gem_javelin", () -> new BrokenJavelinItem(FossilsLegacyTiers.GEM, new Item.Properties()));

	public static final RegistryObject<Item> ZOMBIFIED_PIGMAN_SPAWN_EGG = ITEMS.register("zombified_pigman_spawn_egg", () -> new ForgeSpawnEggItem(() -> FossilsLegacyEntities.ZOMBIFIED_PIGMAN.get(), 0xEA9393, 0x4C7129, new Item.Properties()));
	public static final RegistryObject<Item> DROWNED_PIRATE_SPAWN_EGG = ITEMS.register("drowned_pirate_spawn_egg", () -> new ForgeSpawnEggItem(() -> FossilsLegacyEntities.DROWNED_PIRATE.get(), 0x8FF1D7, 0x799C65, new Item.Properties()));

	public static final RegistryObject<Item> MAMMOTH_SPAWN_EGG = ITEMS.register("mammoth_spawn_egg", () -> new ForgeSpawnEggItem(() -> FossilsLegacyEntities.MAMMOTH.get(), 0x3d2700, 0x211500, new Item.Properties()));
	public static final RegistryObject<Item> SMILODON_SPAWN_EGG = ITEMS.register("smilodon_spawn_egg", () -> new ForgeSpawnEggItem(() -> FossilsLegacyEntities.SMILODON.get(), 0xefa745, 0x9a6527, new Item.Properties()));
	public static final RegistryObject<Item> TRICERATOPS_SPAWN_EGG = ITEMS.register("triceratops_spawn_egg", () -> new ForgeSpawnEggItem(() -> FossilsLegacyEntities.TRICERATOPS.get(), 0xc2ff51, 0x638a25, new Item.Properties()));

	static {
		SimpleUtils.registerAllItems(ITEMS, FossilsLegacyBlocks.BLOCKS);
	}
}
