package willatendo.fossilslegacy.client.animation;

import willatendo.fossilslegacy.client.animation.json.JsonAnimation;
import willatendo.fossilslegacy.client.animation.json.JsonKeyframe;

public final class BaryonyxAnimations {
    public static final JsonAnimation BARYONYX_WALK = JsonAnimation.builder(1F).looping().addAnimation("right_leg", "rotation", JsonKeyframe.create(0F, 0F, 0F, 0F, "linear"), JsonKeyframe.create(0.25F, -27.5F, 0F, 0F, "linear"), JsonKeyframe.create(0.75F, 27.5F, 0F, 0F, "linear"), JsonKeyframe.create(1F, 0F, 0F, 0F, "linear")).addAnimation("left_leg", "rotation", JsonKeyframe.create(0F, 0F, 0F, 0F, "linear"), JsonKeyframe.create(0.25F, 27.5F, 0F, 0F, "linear"), JsonKeyframe.create(0.75F, -27.5F, 0F, 0F, "linear"), JsonKeyframe.create(1F, 0F, 0F, 0F, "linear")).build();
    public static final JsonAnimation BARYONYX_SLEEP = JsonAnimation.builder(0F).looping().addAnimation("neck", "position", JsonKeyframe.create(0F, 0F, -8F, 0F, "linear")).addAnimation("neck", "rotation", JsonKeyframe.create(0F, 80F, 0F, 0F, "linear")).addAnimation("head", "rotation", JsonKeyframe.create(0F, -72.5F, 0F, 0F, "linear")).addAnimation("tail", "position", JsonKeyframe.create(0F, 0F, -8F, 0F, "linear")).addAnimation("tail", "rotation", JsonKeyframe.create(0F, -15F, 0F, 0F, "linear")).addAnimation("right_arm", "position", JsonKeyframe.create(0F, 0F, -8F, 0F, "linear")).addAnimation("right_arm", "rotation", JsonKeyframe.create(0F, -85F, 0F, 0F, "linear")).addAnimation("left_arm", "position", JsonKeyframe.create(0F, 0F, -8F, 0F, "linear")).addAnimation("left_arm", "rotation", JsonKeyframe.create(0F, -85F, 0F, 0F, "linear")).addAnimation("left_leg", "position", JsonKeyframe.create(0F, 0F, -8F, 0F, "linear")).addAnimation("left_leg", "rotation", JsonKeyframe.create(0F, -85F, 0F, 0F, "linear")).addAnimation("right_leg", "position", JsonKeyframe.create(0F, 0F, -8F, 0F, "linear")).addAnimation("right_leg", "rotation", JsonKeyframe.create(0F, -85F, 0F, 0F, "linear")).addAnimation("body", "position", JsonKeyframe.create(0F, 0F, -8F, 0F, "linear")).build();
}
