package willatendo.pridelands.server.item;

import net.minecraft.core.registries.Registries;
import net.minecraft.world.item.CreativeModeTab;
import willatendo.pridelands.server.block.PridelandsBlocks;
import willatendo.pridelands.server.utils.PridelandsUtils;
import willatendo.simplelibrary.server.registry.SimpleHolder;
import willatendo.simplelibrary.server.registry.SimpleRegistry;
import willatendo.simplelibrary.server.util.SimpleUtils;

public final class PridelandsCreativeModeTabs {
    public static final SimpleRegistry<CreativeModeTab> CREATIVE_MODE_TABS = SimpleRegistry.create(Registries.CREATIVE_MODE_TAB, PridelandsUtils.ID);

    public static final SimpleHolder<CreativeModeTab> PRIDELANDS_BLOCKS = CREATIVE_MODE_TABS.register("pridelands_blocks", () -> SimpleUtils.create(PridelandsUtils.ID, "pridelands_blocks", () -> PridelandsBlocks.PRIDESTONE.get().asItem(), (itemDisplayParameters, output) -> {
        output.accept(PridelandsBlocks.PRIDESTONE.get());
        output.accept(PridelandsBlocks.PRIDESTONE_STAIRS.get());
        output.accept(PridelandsBlocks.PRIDESTONE_SLAB.get());
        output.accept(PridelandsBlocks.PRIDESTONE_PRESSURE_PLATE.get());
        output.accept(PridelandsBlocks.PRIDESTONE_BUTTON.get());
        output.accept(PridelandsBlocks.PRIDESTONE_BRICKS.get());
        output.accept(PridelandsBlocks.PRIDESTONE_BRICK_STAIRS.get());
        output.accept(PridelandsBlocks.PRIDESTONE_BRICK_SLAB.get());
        output.accept(PridelandsBlocks.PRIDESTONE_BRICK_WALL.get());
        output.accept(PridelandsBlocks.CRACKED_PRIDESTONE_BRICKS.get());
        output.accept(PridelandsBlocks.MOSSY_PRIDESTONE_BRICKS.get());
        output.accept(PridelandsBlocks.MOSSY_PRIDESTONE_BRICK_STAIRS.get());
        output.accept(PridelandsBlocks.MOSSY_PRIDESTONE_BRICK_SLAB.get());
        output.accept(PridelandsBlocks.MOSSY_PRIDESTONE_BRICK_WALL.get());
        output.accept(PridelandsBlocks.OUTSTONE.get());
        output.accept(PridelandsBlocks.OUTSTONE_STAIRS.get());
        output.accept(PridelandsBlocks.OUTSTONE_SLAB.get());
        output.accept(PridelandsBlocks.OUTSTONE_PRESSURE_PLATE.get());
        output.accept(PridelandsBlocks.OUTSTONE_BUTTON.get());
        output.accept(PridelandsBlocks.OUTSTONE_BRICKS.get());
        output.accept(PridelandsBlocks.OUTSTONE_BRICK_STAIRS.get());
        output.accept(PridelandsBlocks.OUTSTONE_BRICK_SLAB.get());
        output.accept(PridelandsBlocks.OUTSTONE_BRICK_WALL.get());
        output.accept(PridelandsBlocks.PRIDESTONE_COAL_ORE.get());
        output.accept(PridelandsBlocks.PRIDESTONE_SILVER_ORE.get());
        output.accept(PridelandsBlocks.PRIDESTONE_PEACOCK_ORE.get());
        output.accept(PridelandsBlocks.OUTSTONE_NUKA_ORE.get());
        output.accept(PridelandsBlocks.OUTSTONE_KIVULITE_ORE.get());
        output.accept(PridelandsBlocks.PRIDELANDS_PORTAL_FRAME.get());
        output.accept(PridelandsBlocks.OUTLANDS_PORTAL_FRAME.get());
        output.accept(PridelandsBlocks.RAFIKI_TREE_WOOD.get());
        output.accept(PridelandsBlocks.RAFIKI_TREE_BARK.get());
        output.accept(PridelandsBlocks.RAFIKI_TREE_LOG.get());
        output.accept(PridelandsBlocks.FUR_RUG.get());
        output.accept(PridelandsBlocks.WHITE_FUR_RUG.get());
        output.accept(PridelandsBlocks.ORANGE_FUR_RUG.get());
        output.accept(PridelandsBlocks.MAGENTA_FUR_RUG.get());
        output.accept(PridelandsBlocks.LIGHT_BLUE_FUR_RUG.get());
        output.accept(PridelandsBlocks.YELLOW_FUR_RUG.get());
        output.accept(PridelandsBlocks.LIME_FUR_RUG.get());
        output.accept(PridelandsBlocks.PINK_FUR_RUG.get());
        output.accept(PridelandsBlocks.GRAY_FUR_RUG.get());
        output.accept(PridelandsBlocks.LIGHT_GRAY_FUR_RUG.get());
        output.accept(PridelandsBlocks.CYAN_FUR_RUG.get());
        output.accept(PridelandsBlocks.PURPLE_FUR_RUG.get());
        output.accept(PridelandsBlocks.BLUE_FUR_RUG.get());
        output.accept(PridelandsBlocks.BROWN_FUR_RUG.get());
        output.accept(PridelandsBlocks.GREEN_FUR_RUG.get());
        output.accept(PridelandsBlocks.RED_FUR_RUG.get());
        output.accept(PridelandsBlocks.BLACK_FUR_RUG.get());
        output.accept(PridelandsBlocks.HYENA_BONE_TORCH.get());
        output.accept(PridelandsBlocks.ACACIA_BONGO.get());
        output.accept(PridelandsBlocks.BANANA_BONGO.get());
        output.accept(PridelandsBlocks.DEAD_WOOD_BONGO.get());
        output.accept(PridelandsBlocks.MANGO_BONGO.get());
        output.accept(PridelandsBlocks.PASSION_BONGO.get());
        output.accept(PridelandsBlocks.RAINFOREST_BONGO.get());
    }).build());
    public static final SimpleHolder<CreativeModeTab> PRIDELANDS_ITEMS = CREATIVE_MODE_TABS.register("pridelands_items", () -> SimpleUtils.create(PridelandsUtils.ID, "pridelands_items", () -> PridelandsItems.ZEBRA.get().asItem(), (itemDisplayParameters, output) -> {
        output.accept(PridelandsItems.LION.get());
        output.accept(PridelandsItems.COOKED_LION.get());
        output.accept(PridelandsItems.MANGO.get());
        output.accept(PridelandsItems.CHOCOLATE_MUFASA.get());
        output.accept(PridelandsItems.ZEBRA.get());
        output.accept(PridelandsItems.COOKED_ZEBRA.get());
        output.accept(PridelandsItems.RHINO.get());
        output.accept(PridelandsItems.COOKED_RHINO.get());
        output.accept(PridelandsItems.MANGO_JUICE_PRIDESTONE_JAR.get());
        output.accept(PridelandsItems.CORN.get());
        output.accept(PridelandsItems.POPCORN.get());
        output.accept(PridelandsItems.OUTLANDER.get());
        output.accept(PridelandsItems.BUG_STEW.get());
        output.accept(PridelandsItems.CROCODILE.get());
        output.accept(PridelandsItems.KIWANO_SLICE.get());
        output.accept(PridelandsItems.YAM.get());
        output.accept(PridelandsItems.ROASTED_YAM.get());
        output.accept(PridelandsItems.BANANA.get());
        output.accept(PridelandsBlocks.BANANA_CAKE.get());
        output.accept(PridelandsItems.BANANA_BREAD.get());
        output.accept(PridelandsItems.HYENA_BONE.get());
        output.accept(PridelandsItems.BLUE_FEATHER.get());
        output.accept(PridelandsItems.YELLOW_FEATHER.get());
        output.accept(PridelandsItems.RED_FEATHER.get());
        output.accept(PridelandsItems.HYENA_BONE_SHARD.get());
        output.accept(PridelandsItems.ZEBRA_HIDE.get());
        output.accept(PridelandsItems.SILVER_INGOT.get());
        output.accept(PridelandsItems.GROUND_TERMITE.get());
        output.accept(PridelandsItems.LION_FUR.get());
        output.accept(PridelandsItems.RHINO_HORN.get());
        output.accept(PridelandsItems.GROUND_RHINO_HORN.get());
        output.accept(PridelandsItems.GEMSBOK_HIDE.get());
        output.accept(PridelandsItems.GEMSBOK_HORN.get());
        output.accept(PridelandsItems.PEACOCK_GEM.get());
        output.accept(PridelandsItems.MAIZE_STALKS.get());
        output.accept(PridelandsItems.NUKA_SHARD.get());
        output.accept(PridelandsItems.OUTLANDER_FUR.get());
        output.accept(PridelandsItems.KIVULITE_INGOT.get());
        output.accept(PridelandsItems.POISON_POWDER.get());
        output.accept(PridelandsItems.ZAZU_EGG.get());
        output.accept(PridelandsItems.KIWANO_SEEDS.get());
        output.accept(PridelandsItems.FLAMINGO_FEATHER.get());
        output.accept(PridelandsItems.HYENA_MEAL.get());
        output.accept(PridelandsItems.CORN_KERNELS.get());
        output.accept(PridelandsItems.DRIED_MAIZE.get());
        output.accept(PridelandsItems.PRIDESTONE_JAR.get());
        output.accept(PridelandsItems.WATER_PRIDESTONE_JAR.get());
        output.accept(PridelandsItems.LAVA_PRIDESTONE_JAR.get());
        output.accept(PridelandsItems.ZEBRA_MILK_PRIDESTONE_JAR.get());
        output.accept(PridelandsItems.C_NOTE.get());
        output.accept(PridelandsItems.D_NOTE.get());
        output.accept(PridelandsItems.E_NOTE.get());
        output.accept(PridelandsItems.F_NOTE.get());
        output.accept(PridelandsItems.G_NOTE.get());
        output.accept(PridelandsItems.A_NOTE.get());
        output.accept(PridelandsItems.B_NOTE.get());
        output.accept(PridelandsItems.PRIDESTONE_SWORD.get());
        output.accept(PridelandsItems.PRIDESTONE_SHOVEL.get());
        output.accept(PridelandsItems.PRIDESTONE_PICKAXE.get());
        output.accept(PridelandsItems.PRIDESTONE_AXE.get());
        output.accept(PridelandsItems.PRIDESTONE_HOE.get());
        output.accept(PridelandsItems.SILVER_SWORD.get());
        output.accept(PridelandsItems.SILVER_SHOVEL.get());
        output.accept(PridelandsItems.SILVER_PICKAXE.get());
        output.accept(PridelandsItems.SILVER_AXE.get());
        output.accept(PridelandsItems.SILVER_HOE.get());
        output.accept(PridelandsItems.PEACOCK_SWORD.get());
        output.accept(PridelandsItems.PEACOCK_SHOVEL.get());
        output.accept(PridelandsItems.PEACOCK_PICKAXE.get());
        output.accept(PridelandsItems.PEACOCK_AXE.get());
        output.accept(PridelandsItems.PEACOCK_HOE.get());
        output.accept(PridelandsItems.LION_KING_TICKET.get());
    }).build());
}