package willatendo.fossilslegacy.server.feeder_food;

import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import willatendo.fossilslegacy.server.registry.FARegistries;
import willatendo.fossilslegacy.server.item.FAItems;
import willatendo.fossilslegacy.server.utils.FossilsLegacyUtils;

public final class FAFeederFoods {
    public static final ResourceKey<FeederFood> BEEF = FAFeederFoods.create("beef");
    public static final ResourceKey<FeederFood> COOKED_BEEF = FAFeederFoods.create("cooked_beef");
    public static final ResourceKey<FeederFood> CHICKEN = FAFeederFoods.create("chicken");
    public static final ResourceKey<FeederFood> COOKED_CHICKEN = FAFeederFoods.create("cooked_chicken");
    public static final ResourceKey<FeederFood> MUTTON = FAFeederFoods.create("mutton");
    public static final ResourceKey<FeederFood> COOKED_MUTTON = FAFeederFoods.create("cooked_mutton");
    public static final ResourceKey<FeederFood> RABBIT = FAFeederFoods.create("rabbit");
    public static final ResourceKey<FeederFood> COOKED_RABBIT = FAFeederFoods.create("cooked_rabbit");
    public static final ResourceKey<FeederFood> PORKCHOP = FAFeederFoods.create("porkchop");
    public static final ResourceKey<FeederFood> COOKED_PORKCHOP = FAFeederFoods.create("cooked_porkchop");
    public static final ResourceKey<FeederFood> COD = FAFeederFoods.create("cod");
    public static final ResourceKey<FeederFood> COOKED_COD = FAFeederFoods.create("cooked_cod");
    public static final ResourceKey<FeederFood> SALMON = FAFeederFoods.create("salmon");
    public static final ResourceKey<FeederFood> COOKED_SALMON = FAFeederFoods.create("cooked_salmon");
    public static final ResourceKey<FeederFood> TROPICAL_FISH = FAFeederFoods.create("tropical_fish");
    public static final ResourceKey<FeederFood> RAW_TRICERATOPS = FAFeederFoods.create("raw_triceratops");
    public static final ResourceKey<FeederFood> RAW_VELOCIRAPTOR = FAFeederFoods.create("raw_velociraptor");
    public static final ResourceKey<FeederFood> RAW_TYRANNOSAURUS = FAFeederFoods.create("raw_tyrannosaurus");
    public static final ResourceKey<FeederFood> RAW_PTERANODON = FAFeederFoods.create("raw_pteranodon");
    public static final ResourceKey<FeederFood> RAW_FUTABASAURUS = FAFeederFoods.create("raw_futabasaurus");
    public static final ResourceKey<FeederFood> RAW_MOSASAURUS = FAFeederFoods.create("raw_mosasaurus");
    public static final ResourceKey<FeederFood> RAW_STEGOSAURUS = FAFeederFoods.create("raw_stegosaurus");
    public static final ResourceKey<FeederFood> RAW_DILOPHOSAURUS = FAFeederFoods.create("raw_dilophosaurus");
    public static final ResourceKey<FeederFood> RAW_BRACHIOSAURUS = FAFeederFoods.create("raw_brachiosaurus");
    public static final ResourceKey<FeederFood> RAW_SMILODON = FAFeederFoods.create("raw_smilodon");
    public static final ResourceKey<FeederFood> RAW_MAMMOTH = FAFeederFoods.create("raw_mammoth");
    public static final ResourceKey<FeederFood> RAW_CARNOTAURUS = FAFeederFoods.create("raw_carnotaurus");
    public static final ResourceKey<FeederFood> RAW_CRYOLOPHOSAURUS = FAFeederFoods.create("raw_cryolophosaurus");
    public static final ResourceKey<FeederFood> RAW_THERIZINOSAURUS = FAFeederFoods.create("raw_therizinosaurus");
    public static final ResourceKey<FeederFood> RAW_PACHYCEPHALOSAURUS = FAFeederFoods.create("raw_pachycephalosaurus");
    public static final ResourceKey<FeederFood> RAW_COMPSOGNATHUS = FAFeederFoods.create("raw_compsognathus");
    public static final ResourceKey<FeederFood> RAW_DODO = FAFeederFoods.create("raw_dodo");
    public static final ResourceKey<FeederFood> RAW_MOA = FAFeederFoods.create("raw_moa");
    public static final ResourceKey<FeederFood> RAW_GALLIMIMUS = FAFeederFoods.create("raw_gallimimus");
    public static final ResourceKey<FeederFood> RAW_SPINOSAURUS = FAFeederFoods.create("raw_spinosaurus");
    public static final ResourceKey<FeederFood> RAW_ANKYLOSAURUS = FAFeederFoods.create("raw_ankylosaurus");
    public static final ResourceKey<FeederFood> RAW_DIMETRODON = FAFeederFoods.create("raw_dimetrodon");
    public static final ResourceKey<FeederFood> COOKED_TRICERATOPS = FAFeederFoods.create("cooked_triceratops");
    public static final ResourceKey<FeederFood> COOKED_VELOCIRAPTOR = FAFeederFoods.create("cooked_velociraptor");
    public static final ResourceKey<FeederFood> COOKED_TYRANNOSAURUS = FAFeederFoods.create("cooked_tyrannosaurus");
    public static final ResourceKey<FeederFood> COOKED_PTERANODON = FAFeederFoods.create("cooked_pteranodon");
    public static final ResourceKey<FeederFood> SIO_CHIU_LE = FAFeederFoods.create("sio_chiu_le");
    public static final ResourceKey<FeederFood> COOKED_FUTABASAURUS = FAFeederFoods.create("cooked_futabasaurus");
    public static final ResourceKey<FeederFood> COOKED_MOSASAURUS = FAFeederFoods.create("cooked_mosasaurus");
    public static final ResourceKey<FeederFood> COOKED_STEGOSAURUS = FAFeederFoods.create("cooked_stegosaurus");
    public static final ResourceKey<FeederFood> COOKED_DILOPHOSAURUS = FAFeederFoods.create("cooked_dilophosaurus");
    public static final ResourceKey<FeederFood> COOKED_BRACHIOSAURUS = FAFeederFoods.create("cooked_brachiosaurus");
    public static final ResourceKey<FeederFood> COOKED_SMILODON = FAFeederFoods.create("cooked_smilodon");
    public static final ResourceKey<FeederFood> COOKED_MAMMOTH = FAFeederFoods.create("cooked_mammoth");
    public static final ResourceKey<FeederFood> COOKED_CARNOTAURUS = FAFeederFoods.create("cooked_carnotaurus");
    public static final ResourceKey<FeederFood> COOKED_CRYOLOPHOSAURUS = FAFeederFoods.create("cooked_cryolophosaurus");
    public static final ResourceKey<FeederFood> COOKED_THERIZINOSAURUS = FAFeederFoods.create("cooked_therizinosaurus");
    public static final ResourceKey<FeederFood> COOKED_PACHYCEPHALOSAURUS = FAFeederFoods.create("cooked_pachycephalosaurus");
    public static final ResourceKey<FeederFood> COOKED_COMPSOGNATHUS = FAFeederFoods.create("cooked_compsognathus");
    public static final ResourceKey<FeederFood> COOKED_DODO = FAFeederFoods.create("cooked_dodo");
    public static final ResourceKey<FeederFood> COOKED_MOA = FAFeederFoods.create("cooked_moa");
    public static final ResourceKey<FeederFood> COOKED_GALLIMIMUS = FAFeederFoods.create("cooked_gallimimus");
    public static final ResourceKey<FeederFood> COOKED_SPINOSAURUS = FAFeederFoods.create("cooked_spinosaurus");
    public static final ResourceKey<FeederFood> COOKED_ANKYLOSAURUS = FAFeederFoods.create("cooked_ankylosaurus");
    public static final ResourceKey<FeederFood> COOKED_DIMETRODON = FAFeederFoods.create("cooked_dimetrodon");
    public static final ResourceKey<FeederFood> APPLE = FAFeederFoods.create("apple");
    public static final ResourceKey<FeederFood> WHEAT = FAFeederFoods.create("wheat");
    public static final ResourceKey<FeederFood> BREAD = FAFeederFoods.create("bread");
    public static final ResourceKey<FeederFood> SUGAR_CANE = FAFeederFoods.create("sugar_cane");
    public static final ResourceKey<FeederFood> WHEAT_SEEDS = FAFeederFoods.create("wheat_seeds");
    public static final ResourceKey<FeederFood> BEETROOT_SEEDS = FAFeederFoods.create("beetroot_seeds");
    public static final ResourceKey<FeederFood> MELON_SEEDS = FAFeederFoods.create("melon_seeds");
    public static final ResourceKey<FeederFood> PUMPKIN_SEEDS = FAFeederFoods.create("pumpkin_seeds");
    public static final ResourceKey<FeederFood> MELON_SLICE = FAFeederFoods.create("melon_slice");
    public static final ResourceKey<FeederFood> SWEET_BERRIES = FAFeederFoods.create("sweet_berries");
    public static final ResourceKey<FeederFood> GLOW_BERRIES = FAFeederFoods.create("glow_berries");
    public static final ResourceKey<FeederFood> CARROT = FAFeederFoods.create("carrot");
    public static final ResourceKey<FeederFood> POTATO = FAFeederFoods.create("potato");
    public static final ResourceKey<FeederFood> BAKED_POTATO = FAFeederFoods.create("baked_potato");
    public static final ResourceKey<FeederFood> BEETROOT = FAFeederFoods.create("beetroot");
    public static final ResourceKey<FeederFood> KELP = FAFeederFoods.create("kelp");
    public static final ResourceKey<FeederFood> JURASSIC_FERN_SPORES = FAFeederFoods.create("jurassic_fern_spores");

    public static ResourceKey<FeederFood> create(String name) {
        return ResourceKey.create(FARegistries.FEEDER_FOOD, FossilsLegacyUtils.resource(name));
    }

    private static void register(BootstrapContext<FeederFood> bootstrapContext, ResourceKey<FeederFood> resourceKey, ItemStack itemStack, int amount, FeederFood.FillType fillType) {
        bootstrapContext.register(resourceKey, new FeederFood(resourceKey.location(), itemStack, amount, fillType));
    }

    public static void bootstrap(BootstrapContext<FeederFood> bootstrapContext) {
        register(bootstrapContext, BEEF, new ItemStack(Items.BEEF), 40, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_BEEF, new ItemStack(Items.COOKED_BEEF), 20, FeederFood.FillType.MEAT);
        register(bootstrapContext, CHICKEN, new ItemStack(Items.CHICKEN), 30, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_CHICKEN, new ItemStack(Items.COOKED_CHICKEN), 10, FeederFood.FillType.MEAT);
        register(bootstrapContext, MUTTON, new ItemStack(Items.MUTTON), 30, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_MUTTON, new ItemStack(Items.COOKED_MUTTON), 10, FeederFood.FillType.MEAT);
        register(bootstrapContext, RABBIT, new ItemStack(Items.RABBIT), 30, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_RABBIT, new ItemStack(Items.COOKED_RABBIT), 10, FeederFood.FillType.MEAT);
        register(bootstrapContext, PORKCHOP, new ItemStack(Items.PORKCHOP), 20, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_PORKCHOP, new ItemStack(Items.COOKED_PORKCHOP), 30, FeederFood.FillType.MEAT);
        register(bootstrapContext, COD, new ItemStack(Items.COD), 40, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_COD, new ItemStack(Items.COOKED_COD), 60, FeederFood.FillType.MEAT);
        register(bootstrapContext, SALMON, new ItemStack(Items.SALMON), 40, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_SALMON, new ItemStack(Items.COOKED_SALMON), 60, FeederFood.FillType.MEAT);
        register(bootstrapContext, TROPICAL_FISH, new ItemStack(Items.TROPICAL_FISH), 40, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_TRICERATOPS, new ItemStack(FAItems.RAW_TRICERATOPS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_VELOCIRAPTOR, new ItemStack(FAItems.RAW_VELOCIRAPTOR.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_TYRANNOSAURUS, new ItemStack(FAItems.RAW_TYRANNOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_PTERANODON, new ItemStack(FAItems.RAW_PTERANODON.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_FUTABASAURUS, new ItemStack(FAItems.RAW_FUTABASAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_MOSASAURUS, new ItemStack(FAItems.RAW_MOSASAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_STEGOSAURUS, new ItemStack(FAItems.RAW_STEGOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_DILOPHOSAURUS, new ItemStack(FAItems.RAW_DILOPHOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_BRACHIOSAURUS, new ItemStack(FAItems.RAW_BRACHIOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_SMILODON, new ItemStack(FAItems.RAW_SMILODON.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_MAMMOTH, new ItemStack(FAItems.RAW_MAMMOTH.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_CARNOTAURUS, new ItemStack(FAItems.RAW_CARNOTAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_CRYOLOPHOSAURUS, new ItemStack(FAItems.RAW_CRYOLOPHOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_THERIZINOSAURUS, new ItemStack(FAItems.RAW_THERIZINOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_PACHYCEPHALOSAURUS, new ItemStack(FAItems.RAW_PACHYCEPHALOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_COMPSOGNATHUS, new ItemStack(FAItems.RAW_COMPSOGNATHUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_DODO, new ItemStack(FAItems.RAW_DODO.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_MOA, new ItemStack(FAItems.RAW_MOA.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_GALLIMIMUS, new ItemStack(FAItems.RAW_GALLIMIMUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_SPINOSAURUS, new ItemStack(FAItems.RAW_SPINOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_ANKYLOSAURUS, new ItemStack(FAItems.RAW_ANKYLOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, RAW_DIMETRODON, new ItemStack(FAItems.RAW_DIMETRODON.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_TRICERATOPS, new ItemStack(FAItems.COOKED_TRICERATOPS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_VELOCIRAPTOR, new ItemStack(FAItems.COOKED_VELOCIRAPTOR.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_TYRANNOSAURUS, new ItemStack(FAItems.COOKED_TYRANNOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_PTERANODON, new ItemStack(FAItems.COOKED_PTERANODON.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, SIO_CHIU_LE, new ItemStack(FAItems.SIO_CHIU_LE.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_FUTABASAURUS, new ItemStack(FAItems.COOKED_FUTABASAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_MOSASAURUS, new ItemStack(FAItems.COOKED_MOSASAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_STEGOSAURUS, new ItemStack(FAItems.COOKED_STEGOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_DILOPHOSAURUS, new ItemStack(FAItems.COOKED_DILOPHOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_BRACHIOSAURUS, new ItemStack(FAItems.COOKED_BRACHIOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_SMILODON, new ItemStack(FAItems.COOKED_SMILODON.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_MAMMOTH, new ItemStack(FAItems.COOKED_MAMMOTH.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_CARNOTAURUS, new ItemStack(FAItems.COOKED_CARNOTAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_CRYOLOPHOSAURUS, new ItemStack(FAItems.COOKED_CRYOLOPHOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_THERIZINOSAURUS, new ItemStack(FAItems.COOKED_THERIZINOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_PACHYCEPHALOSAURUS, new ItemStack(FAItems.COOKED_PACHYCEPHALOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_COMPSOGNATHUS, new ItemStack(FAItems.COOKED_COMPSOGNATHUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_DODO, new ItemStack(FAItems.COOKED_DODO.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_MOA, new ItemStack(FAItems.COOKED_MOA.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_GALLIMIMUS, new ItemStack(FAItems.COOKED_GALLIMIMUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_SPINOSAURUS, new ItemStack(FAItems.COOKED_SPINOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_ANKYLOSAURUS, new ItemStack(FAItems.COOKED_ANKYLOSAURUS.get()), 100, FeederFood.FillType.MEAT);
        register(bootstrapContext, COOKED_DIMETRODON, new ItemStack(FAItems.COOKED_DIMETRODON.get()), 100, FeederFood.FillType.MEAT);

        register(bootstrapContext, APPLE, new ItemStack(Items.APPLE), 100, FeederFood.FillType.PLANT);
        register(bootstrapContext, WHEAT, new ItemStack(Items.WHEAT), 40, FeederFood.FillType.PLANT);
        register(bootstrapContext, BREAD, new ItemStack(Items.BREAD), 120, FeederFood.FillType.PLANT);
        register(bootstrapContext, SUGAR_CANE, new ItemStack(Items.SUGAR_CANE), 20, FeederFood.FillType.PLANT);
        register(bootstrapContext, WHEAT_SEEDS, new ItemStack(Items.WHEAT_SEEDS), 20, FeederFood.FillType.PLANT);
        register(bootstrapContext, BEETROOT_SEEDS, new ItemStack(Items.BEETROOT_SEEDS), 20, FeederFood.FillType.PLANT);
        register(bootstrapContext, MELON_SEEDS, new ItemStack(Items.MELON_SEEDS), 20, FeederFood.FillType.PLANT);
        register(bootstrapContext, PUMPKIN_SEEDS, new ItemStack(Items.PUMPKIN_SEEDS), 20, FeederFood.FillType.PLANT);
        register(bootstrapContext, MELON_SLICE, new ItemStack(Items.MELON_SLICE), 25, FeederFood.FillType.PLANT);
        register(bootstrapContext, SWEET_BERRIES, new ItemStack(Items.SWEET_BERRIES), 15, FeederFood.FillType.PLANT);
        register(bootstrapContext, GLOW_BERRIES, new ItemStack(Items.GLOW_BERRIES), 15, FeederFood.FillType.PLANT);
        register(bootstrapContext, CARROT, new ItemStack(Items.CARROT), 100, FeederFood.FillType.PLANT);
        register(bootstrapContext, POTATO, new ItemStack(Items.POTATO), 100, FeederFood.FillType.PLANT);
        register(bootstrapContext, BAKED_POTATO, new ItemStack(Items.BAKED_POTATO), 75, FeederFood.FillType.PLANT);
        register(bootstrapContext, BEETROOT, new ItemStack(Items.BEETROOT), 25, FeederFood.FillType.PLANT);
        register(bootstrapContext, KELP, new ItemStack(Items.KELP), 15, FeederFood.FillType.PLANT);
        register(bootstrapContext, JURASSIC_FERN_SPORES, new ItemStack(FAItems.JURASSIC_FERN_SPORES.get()), 50, FeederFood.FillType.PLANT);
    }
}
