package willatendo.fossilslegacy.server.feeder_food;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Blocks;
import willatendo.fossilslegacy.server.block.FABlocks;
import willatendo.fossilslegacy.server.item.FAItems;
import willatendo.fossilslegacy.server.registry.FARegistries;
import willatendo.fossilslegacy.server.utils.FAUtils;

public final class FAFeederFoods {
    public static ResourceKey<FeederFood> create(String name) {
        return ResourceKey.create(FARegistries.FEEDER_FOOD, FAUtils.resource(name));
    }

    private static void register(BootstrapContext<FeederFood> bootstrapContext, ResourceKey<FeederFood> resourceKey, ItemLike itemLike, int fillAmount, FeederFood.FillType fillType) {
        bootstrapContext.register(resourceKey, new FeederFood(BuiltInRegistries.ITEM.getKey(itemLike.asItem()), new FeederFood.FeederInfo(fillAmount, fillType)));
    }

    private static void register(BootstrapContext<FeederFood> bootstrapContext, ItemLike itemLike, int fillAmount, FeederFood.FillType fillType) {
        FAFeederFoods.register(bootstrapContext, FAFeederFoods.create(BuiltInRegistries.ITEM.getKey(itemLike.asItem()).getPath()), itemLike, fillAmount, fillType);
    }

    public static void bootstrap(BootstrapContext<FeederFood> bootstrapContext) {
        FAFeederFoods.register(bootstrapContext, Items.BEEF, 40, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.COOKED_BEEF, 20, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.CHICKEN, 30, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.COOKED_CHICKEN, 10, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.MUTTON, 30, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.COOKED_MUTTON, 10, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.RABBIT, 30, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.COOKED_RABBIT, 10, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.PORKCHOP, 20, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.COOKED_PORKCHOP, 30, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.COD, 40, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.COOKED_COD, 60, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.SALMON, 40, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.COOKED_SALMON, 60, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, Items.TROPICAL_FISH, 40, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_TRICERATOPS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_VELOCIRAPTOR.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_TYRANNOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_PTERANODON.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_FUTABASAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_MOSASAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_STEGOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_DILOPHOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_BRACHIOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_SMILODON.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_MAMMOTH.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_CARNOTAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_CRYOLOPHOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_THERIZINOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_PACHYCEPHALOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_COMPSOGNATHUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_DODO.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_MOA.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_GALLIMIMUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_SPINOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_ANKYLOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_DIMETRODON.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_ICHTHYOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.RAW_ELASMOTHERIUM.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_TRICERATOPS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_VELOCIRAPTOR.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_TYRANNOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_PTERANODON.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.NAUTILUS_SIO_CHIU_LE.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.CENOCERAS_SIO_CHIU_LE.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_FUTABASAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_MOSASAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_STEGOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_DILOPHOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_BRACHIOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_SMILODON.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_MAMMOTH.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_CARNOTAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_CRYOLOPHOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_THERIZINOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_PACHYCEPHALOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_COMPSOGNATHUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_DODO.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_MOA.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_GALLIMIMUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_SPINOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_ANKYLOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_DIMETRODON.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_ICHTHYOSAURUS.get(), 100, FeederFood.FillType.MEAT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKED_ELASMOTHERIUM.get(), 100, FeederFood.FillType.MEAT);

        FAFeederFoods.register(bootstrapContext, Items.APPLE, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.GOLDEN_APPLE, 1000, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.ENCHANTED_GOLDEN_APPLE, 10000, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.WHEAT, 40, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.BREAD, 120, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.SUGAR_CANE, 20, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.WHEAT_SEEDS, 20, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.BEETROOT_SEEDS, 20, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.MELON_SEEDS, 20, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.PUMPKIN_SEEDS, 20, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.MELON_SLICE, 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.SWEET_BERRIES, 15, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.GLOW_BERRIES, 15, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.CARROT, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.GOLDEN_CARROT, 1000, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.POTATO, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.BAKED_POTATO, 75, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.BEETROOT, 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.KELP, 15, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.DRIED_KELP, 15, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.COOKIE, 15, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.COCOA_BEANS, 5, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.CAKE, 15, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Items.PUMPKIN_PIE, 150, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.OAK_LEAVES, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.SPRUCE_LEAVES, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.BIRCH_LEAVES, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.JUNGLE_LEAVES, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.ACACIA_LEAVES, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.DARK_OAK_LEAVES, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.MANGROVE_LEAVES, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.CHERRY_LEAVES, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.PALE_OAK_LEAVES, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.AZALEA_LEAVES, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.FLOWERING_AZALEA_LEAVES, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.OAK_SAPLING, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.SPRUCE_SAPLING, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.BIRCH_SAPLING, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.JUNGLE_SAPLING, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.ACACIA_SAPLING, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.DARK_OAK_SAPLING, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.MANGROVE_PROPAGULE, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.CHERRY_SAPLING, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.PALE_OAK_SAPLING, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.AZALEA, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.FLOWERING_AZALEA, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.BROWN_MUSHROOM, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.RED_MUSHROOM, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.SHORT_GRASS, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.FERN, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.DANDELION, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.POPPY, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.BLUE_ORCHID, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.ALLIUM, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.AZURE_BLUET, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.RED_TULIP, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.ORANGE_TULIP, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.WHITE_TULIP, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.PINK_TULIP, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.OXEYE_DAISY, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.CORNFLOWER, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.PINK_PETALS, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.SPORE_BLOSSOM, 250, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.BAMBOO, 50, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.VINE, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.TALL_GRASS, 200, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.LARGE_FERN, 200, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.SUNFLOWER, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.LILAC, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.ROSE_BUSH, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.PEONY, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.BIG_DRIPLEAF, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.SMALL_DRIPLEAF, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.GLOW_LICHEN, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.HANGING_ROOTS, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.LILY_PAD, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.SEAGRASS, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.SEA_PICKLE, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.MELON, 225, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.PUMPKIN, 200, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.HAY_BLOCK, 360, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.MOSS_BLOCK, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.MOSS_CARPET, 30, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.PALE_MOSS_BLOCK, 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.PALE_MOSS_CARPET, 30, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, Blocks.PALE_HANGING_MOSS, 30, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.ARAUCARIA_LEAVES.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.ARAUCARIOXYLON_LEAVES.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.ARCHAEOPTERIS_LEAVES.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.CALAMITES_LEAVES.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.CORDAITES_LEAVES.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.GINKGO_LEAVES.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.SIGILLARIA_LEAVES.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.WOLLEMIA_LEAVES.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.ARAUCARIA_SAPLING.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.ARAUCARIOXYLON_SAPLING.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.ARCHAEOPTERIS_SAPLING.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.CALAMITES_SAPLING.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.CORDAITES_SAPLING.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.GINKGO_SAPLING.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.SIGILLARIA_SAPLING.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.WOLLEMIA_SAPLING.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.ARAUCARIA_CONE.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.ARCHAEOPTERIS_SPORE.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.CALAMITES_SPORE.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.CYCAD_CONE.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.COOKSONIA_SPORES.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.CLAYTOSMUNDA_SPORES.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.SARCANDRA_BERRIES.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.GINKGO_SEED.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.HORSETAIL_SPORE.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.JURASSIC_FERN_SPORES.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.CYCADEOIDEA_SEED.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.LEPIDODENDRON_CONE.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FAItems.SIGILLARIA_SPORE.get(), 25, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.SHORT_HORSETAIL.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.TALL_HORSETAIL.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.CLAYTOSMUNDA.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.CYCADEOIDEA.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.ONYCHIOPSIS.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.JURASSIC_FERN.get(), 100, FeederFood.FillType.PLANT);
        FAFeederFoods.register(bootstrapContext, FABlocks.COOKSONIA.get(), 100, FeederFood.FillType.PLANT);
    }
}
